// Apply worked tasks (classification / decision scheme + answer key). Source:
// Apply_Verb_Task_Register.xlsx. The mentee applies the task's scheme to each item, choosing an
// `outcome` from the vocabulary; `noteMode` says when a note (rationale / treatment / gap note /
// rewrite / correction) is required. `outcome` is the answer key. Submission is gated on every
// item's outcome matching the key + required notes present (see ApplyWorkspace).

export type ApplyNoteMode = "all" | "nonClean" | "none";

export interface ApplyRow {
  id: number;
  cells: string[];
  /** Answer-key outcome for this item. */
  outcome: string;
}

export interface ApplyTask {
  title: string;
  standard: string;
  columns: string[];
  /** Outcome vocabulary the mentee picks from per item. */
  outcomes: string[];
  /** Outcome that needs no note (for `nonClean` mode); null otherwise. */
  clean: string | null;
  /** When a per-item note is required. */
  noteMode: ApplyNoteMode;
  /** Label for the note field, when used. */
  noteLabel: string | null;
  rows: ApplyRow[];
  feedsNext: string;
}

export const APPLY_TASKS: Record<string, ApplyTask> = {
  "AA-001/1.4": {
    title: "Information Asset Inventory & Classification",
    standard: "ISO/IEC 27001:2022 — A.5.12 Classification; A.5.9 Inventory; A.8.1 Endpoint devices",
    columns: ["Asset ID", "Asset Name", "Asset Type", "Owner (role)", "Personal data?"],
    outcomes: ["Public", "Internal", "Confidential"],
    clean: null,
    noteMode: "all",
    noteLabel: "Rationale",
    feedsNext: "Feeds the cross-reference & sign-off steps — the classified asset register.",
    rows: [
      { id: 1, cells: ["AST-0001", "Public marketing website", "Web/Content", "Head of Marketing", "N"], outcome: "Public" },
      { id: 2, cells: ["AST-0002", "Product brochures (published)", "Document", "Head of Marketing", "N"], outcome: "Public" },
      { id: 3, cells: ["AST-0003", "Public API documentation", "Document", "Developer Relations Lead", "N"], outcome: "Public" },
      { id: 4, cells: ["AST-0004", "Press releases", "Document", "Head of Communications", "N"], outcome: "Public" },
      { id: 5, cells: ["AST-0005", "Open-source SDK (public repo)", "Source Code", "Developer Relations Lead", "N"], outcome: "Public" },
      { id: 6, cells: ["AST-0006", "Public status / uptime page", "Web/Content", "SRE Lead", "N"], outcome: "Public" },
      { id: 7, cells: ["AST-0007", "Employee handbook", "Document", "HR Systems Manager", "N"], outcome: "Internal" },
      { id: 8, cells: ["AST-0008", "Internal wiki / Confluence", "Document Store", "Head of Engineering", "N"], outcome: "Internal" },
      { id: 9, cells: ["AST-0009", "Organisation chart", "Document", "HR Systems Manager", "N"], outcome: "Internal" },
      { id: 10, cells: ["AST-0010", "Project plans & roadmap drafts", "Document", "Head of Product", "N"], outcome: "Internal" },
      { id: 11, cells: ["AST-0011", "Team meeting minutes", "Document", "Chief of Staff", "N"], outcome: "Internal" },
      { id: 12, cells: ["AST-0012", "Internal training materials", "Document", "L&D Manager", "N"], outcome: "Internal" },
      { id: 13, cells: ["AST-0013", "IT runbooks / SOPs", "Document", "IT Operations Manager", "N"], outcome: "Internal" },
      { id: 14, cells: ["AST-0014", "Office floor plans", "Document", "Facilities Manager", "N"], outcome: "Internal" },
      { id: 15, cells: ["AST-0015", "Internal newsletters", "Document", "Head of Communications", "N"], outcome: "Internal" },
      { id: 16, cells: ["AST-0016", "Customer PII database", "Database", "Data Platform Lead", "Y"], outcome: "Confidential" },
      { id: 17, cells: ["AST-0017", "Application source code repository", "Source Code", "Head of Engineering", "N"], outcome: "Confidential" },
      { id: 18, cells: ["AST-0018", "ERP / financial system", "Application", "Financial Controller", "N"], outcome: "Confidential" },
      { id: 19, cells: ["AST-0019", "Payroll data", "Database", "Chief Human Resources Officer", "Y"], outcome: "Confidential" },
      { id: 20, cells: ["AST-0020", "Customer contracts", "Document Store", "General Counsel", "Y"], outcome: "Confidential" },
      { id: 21, cells: ["AST-0021", "Encryption keys / secrets store", "Key Material", "Chief Information Security Officer", "N"], outcome: "Confidential" },
      { id: 22, cells: ["AST-0022", "Security incident & case logs", "Database", "Chief Information Security Officer", "Y"], outcome: "Confidential" },
      { id: 23, cells: ["AST-0023", "HR employee records archive", "Document Store", "Chief Human Resources Officer", "Y"], outcome: "Confidential" },
      { id: 24, cells: ["AST-0024", "Penetration-test reports", "Document", "Chief Information Security Officer", "N"], outcome: "Confidential" },
      { id: 25, cells: ["AST-0025", "M&A / corporate strategy files", "Document Store", "Chief Strategy Officer", "N"], outcome: "Confidential" },
      { id: 26, cells: ["AST-0026", "Customer support tickets", "Database", "Head of Customer Success", "Y"], outcome: "Confidential" },
      { id: 27, cells: ["AST-0027", "Product roadmap (unreleased)", "Document", "Head of Product", "N"], outcome: "Confidential" },
      { id: 28, cells: ["AST-0028", "SIEM & log analytics data", "Database", "Chief Information Security Officer", "Y"], outcome: "Confidential" },
      { id: 29, cells: ["AST-0029", "Database backups", "Backup", "Data Platform Lead", "Y"], outcome: "Confidential" },
      { id: 30, cells: ["AST-0030", "Vendor / supplier contracts", "Document Store", "Procurement Manager", "N"], outcome: "Confidential" },
    ],
  },
  "GRM-001/4.5": {
    title: "Operational Risk Identification & Basic Risk Register",
    standard: "ISO/IEC 27001:2022 — Clause 6.1.2/6.1.3 (risk assessment & treatment); Annex A 5.9",
    columns: ["Risk ID", "Risk description", "Threat source", "Control domain", "L (1-5)", "I (1-5)", "Score"],
    outcomes: ["Low", "Medium", "High", "Critical"],
    clean: null,
    noteMode: "all",
    noteLabel: "Treatment (accept/mitigate/transfer/avoid)",
    feedsNext: "Feeds the treatment plan & top-5 management summary.",
    rows: [
      { id: 1, cells: ["R-01", "Phishing leads to consultant account compromise", "External attacker", "People", "5", "5", "25"], outcome: "Critical" },
      { id: 2, cells: ["R-02", "Client confidential report emailed to wrong recipient", "Human error", "People", "4", "4", "16"], outcome: "High" },
      { id: 3, cells: ["R-03", "Laptop lost/stolen with client data", "Theft", "Physical", "3", "4", "12"], outcome: "High" },
      { id: 4, cells: ["R-04", "Ransomware encrypts shared file server", "Cyber-criminal", "Technological", "3", "5", "15"], outcome: "High" },
      { id: 5, cells: ["R-05", "Unpatched VPN exploited", "External attacker", "Technological", "3", "4", "12"], outcome: "High" },
      { id: 6, cells: ["R-06", "Departing consultant takes client files", "Insider", "People", "3", "4", "12"], outcome: "High" },
      { id: 7, cells: ["R-07", "Cloud storage bucket left public", "Misconfiguration", "Technological", "2", "5", "10"], outcome: "Medium" },
      { id: 8, cells: ["R-08", "Weak/reused passwords on key SaaS", "User behaviour", "Technological", "4", "3", "12"], outcome: "High" },
      { id: 9, cells: ["R-09", "No MFA on email", "Config gap", "Technological", "4", "4", "16"], outcome: "High" },
      { id: 10, cells: ["R-10", "Vendor (sub-processor) breach exposes client data", "Third party", "Technological", "2", "4", "8"], outcome: "Medium" },
      { id: 11, cells: ["R-11", "Invoice fraud / business email compromise", "External attacker", "People", "3", "4", "12"], outcome: "High" },
      { id: 12, cells: ["R-12", "Backup not tested, fails on restore", "Process gap", "Technological", "2", "5", "10"], outcome: "Medium" },
      { id: 13, cells: ["R-13", "Shared admin account misused", "Insider", "Technological", "2", "3", "6"], outcome: "Medium" },
      { id: 14, cells: ["R-14", "Physical access to office by tailgating", "Intruder", "Physical", "2", "2", "4"], outcome: "Low" },
      { id: 15, cells: ["R-15", "Sensitive print-outs left on desks", "Human error", "Physical", "3", "2", "6"], outcome: "Medium" },
      { id: 16, cells: ["R-16", "Lost USB with client deliverables", "Theft/loss", "Physical", "2", "3", "6"], outcome: "Medium" },
      { id: 17, cells: ["R-17", "DDoS on client portal", "External attacker", "Technological", "2", "3", "6"], outcome: "Medium" },
      { id: 18, cells: ["R-18", "Outdated antivirus on endpoints", "Config gap", "Technological", "3", "3", "9"], outcome: "Medium" },
      { id: 19, cells: ["R-19", "No formal data-retention, over-retention", "Process gap", "Governance", "3", "2", "6"], outcome: "Medium" },
      { id: 20, cells: ["R-20", "Consultant uses unsanctioned AI tool with client data", "Shadow IT", "Governance", "4", "3", "12"], outcome: "High" },
      { id: 21, cells: ["R-21", "Key person dependency on one partner", "Resourcing", "Governance", "3", "3", "9"], outcome: "Medium" },
      { id: 22, cells: ["R-22", "GDPR breach notification missed (no process)", "Process gap", "Governance", "2", "4", "8"], outcome: "Medium" },
      { id: 23, cells: ["R-23", "Office fire damages on-prem records", "Natural/physical", "Physical", "1", "5", "5"], outcome: "Medium" },
      { id: 24, cells: ["R-24", "Misconfigured email forwarding rule (BEC persistence)", "Attacker", "Technological", "2", "3", "6"], outcome: "Medium" },
      { id: 25, cells: ["R-25", "Contractor without NDA accesses client data", "Governance gap", "Governance", "2", "3", "6"], outcome: "Medium" },
      { id: 26, cells: ["R-26", "Late patching of office workstations", "Process gap", "Technological", "3", "2", "6"], outcome: "Medium" },
      { id: 27, cells: ["R-27", "Social-engineering call to reception", "External attacker", "People", "2", "2", "4"], outcome: "Low" },
      { id: 28, cells: ["R-28", "Unencrypted laptop disk", "Config gap", "Technological", "2", "4", "8"], outcome: "Medium" },
      { id: 29, cells: ["R-29", "Excessive access rights (no least privilege)", "Governance gap", "Technological", "3", "3", "9"], outcome: "Medium" },
      { id: 30, cells: ["R-30", "Client data stored in personal cloud drive", "Shadow IT", "Governance", "3", "4", "12"], outcome: "High" },
    ],
  },
  "TPRM-001/3": {
    title: "Supplier/Vendor Inventory & Risk Rating",
    standard: "ISO/IEC 27001:2022 — A.5.19 / 5.20 / 5.22 (supplier relationships, agreements, monitoring)",
    columns: ["Vendor ID", "Vendor name", "Service", "Data(0-3)", "Sys(0-2)", "Crit(1-5)", "Geo(0/1)", "NoCert(0/1)", "Composite"],
    outcomes: ["Low", "Medium", "High"],
    clean: null,
    noteMode: "none",
    noteLabel: null,
    feedsNext: "Feeds the Supplier Register & High-Risk Vendor Summary.",
    rows: [
      { id: 1, cells: ["V-01", "Cloud Co", "Cloud IaaS provider", "3", "2", "5", "1", "0", "16"], outcome: "High" },
      { id: 2, cells: ["V-02", "Email/SaaS Co", "Email/SaaS suite", "3", "2", "4", "1", "0", "15"], outcome: "High" },
      { id: 3, cells: ["V-03", "Payroll Co", "Payroll processor", "3", "1", "4", "0", "0", "12"], outcome: "High" },
      { id: 4, cells: ["V-04", "CRM Co", "CRM SaaS", "3", "2", "4", "1", "0", "15"], outcome: "High" },
      { id: 5, cells: ["V-05", "Payment Co", "Payment gateway", "2", "1", "5", "1", "0", "12"], outcome: "High" },
      { id: 6, cells: ["V-06", "Helpdesk Co", "Helpdesk SaaS", "2", "1", "3", "0", "0", "9"], outcome: "Medium" },
      { id: 7, cells: ["V-07", "HR Co", "HR SaaS", "3", "1", "3", "0", "0", "11"], outcome: "High" },
      { id: 8, cells: ["V-08", "Marketing Co", "Marketing email tool", "2", "1", "2", "1", "1", "10"], outcome: "Medium" },
      { id: 9, cells: ["V-09", "Analytics Co", "Analytics platform", "2", "1", "3", "1", "1", "11"], outcome: "High" },
      { id: 10, cells: ["V-10", "Code Co", "Code repo / CI SaaS", "2", "2", "4", "1", "0", "13"], outcome: "High" },
      { id: 11, cells: ["V-11", "Pen-test Co", "Pen-test consultancy", "1", "2", "3", "0", "0", "9"], outcome: "Medium" },
      { id: 12, cells: ["V-12", "Office Co", "Office cleaning", "0", "0", "1", "0", "1", "2"], outcome: "Low" },
      { id: 13, cells: ["V-13", "Stationery Co", "Stationery supplier", "0", "0", "1", "0", "1", "2"], outcome: "Low" },
      { id: 14, cells: ["V-14", "Legal Co", "Legal advisors", "2", "0", "3", "0", "0", "7"], outcome: "Medium" },
      { id: 15, cells: ["V-15", "Accounting Co", "Accounting firm", "2", "0", "3", "0", "0", "7"], outcome: "Medium" },
      { id: 16, cells: ["V-16", "Translation Co", "Translation agency", "1", "0", "2", "1", "1", "6"], outcome: "Medium" },
      { id: 17, cells: ["V-17", "Background-check Co", "Background-check vendor", "2", "0", "3", "1", "1", "9"], outcome: "Medium" },
      { id: 18, cells: ["V-18", "Badge/access Co", "Badge/access control", "1", "1", "3", "0", "1", "8"], outcome: "Medium" },
      { id: 19, cells: ["V-19", "Video Co", "Video conferencing", "1", "1", "3", "1", "0", "8"], outcome: "Medium" },
      { id: 20, cells: ["V-20", "Document Co", "Document e-sign", "2", "1", "3", "1", "0", "10"], outcome: "Medium" },
      { id: 21, cells: ["V-21", "Backup/DR Co", "Backup/DR vendor", "3", "1", "5", "1", "0", "14"], outcome: "High" },
      { id: 22, cells: ["V-22", "Monitoring/SIEM Co", "Monitoring/SIEM SaaS", "2", "2", "4", "1", "0", "13"], outcome: "High" },
      { id: 23, cells: ["V-23", "Recruitment Co", "Recruitment agency", "2", "0", "2", "0", "1", "7"], outcome: "Medium" },
      { id: 24, cells: ["V-24", "Catering Co", "Catering", "0", "0", "1", "0", "1", "2"], outcome: "Low" },
      { id: 25, cells: ["V-25", "Courier/logistics Co", "Courier/logistics", "1", "0", "2", "0", "1", "5"], outcome: "Low" },
      { id: 26, cells: ["V-26", "Web Co", "Web hosting (marketing)", "1", "1", "2", "1", "1", "8"], outcome: "Medium" },
      { id: 27, cells: ["V-27", "Survey Co", "Survey tool", "1", "0", "2", "1", "1", "6"], outcome: "Medium" },
      { id: 28, cells: ["V-28", "Password Co", "Password manager", "3", "2", "4", "1", "0", "15"], outcome: "High" },
      { id: 29, cells: ["V-29", "Endpoint Co", "Endpoint AV vendor", "1", "2", "4", "1", "0", "11"], outcome: "High" },
      { id: 30, cells: ["V-30", "Telecoms Co", "Telecoms provider", "1", "0", "3", "0", "0", "5"], outcome: "Low" },
    ],
  },
  "CA-002/5": {
    title: "Management Compliance Status Report",
    standard: "ISO/IEC 27001:2022 — Clause 9.3 (Management review); 9.1 (Monitoring); A.5.35",
    columns: ["Draft line (before)"],
    outcomes: ["OK", "Needs revision"],
    clean: "OK",
    noteMode: "nonClean",
    noteLabel: "Plain-English rewrite",
    feedsNext: "Feeds the one-page Executive Compliance Status Report.",
    rows: [
      { id: 1, cells: ["We will leverage synergies to operationalize a robust security posture going forward."], outcome: "Needs revision" },
      { id: 2, cells: ["Compliance is good."], outcome: "Needs revision" },
      { id: 3, cells: ["We utilize a holistic, best-in-class framework."], outcome: "Needs revision" },
      { id: 4, cells: ["Overall compliance status is Amber."], outcome: "OK" },
      { id: 5, cells: ["Our paradigm is to facilitate actionable, granular insights."], outcome: "Needs revision" },
      { id: 6, cells: ["Top risk: phishing — likelihood high."], outcome: "Needs revision" },
      { id: 7, cells: ["We closed several findings."], outcome: "Needs revision" },
      { id: 8, cells: ["MFA rollout is in progress."], outcome: "Needs revision" },
      { id: 9, cells: ["We need budget for tooling."], outcome: "Needs revision" },
      { id: 10, cells: ["The team has good bandwidth to circle back on low-hanging fruit."], outcome: "Needs revision" },
      { id: 11, cells: ["Patch compliance improved."], outcome: "Needs revision" },
      { id: 12, cells: ["Risk posture is robust."], outcome: "Needs revision" },
      { id: 13, cells: ["Incident response time is acceptable."], outcome: "Needs revision" },
      { id: 14, cells: ["We achieved a quantum leap in maturity."], outcome: "Needs revision" },
      { id: 15, cells: ["Third-party risk is being managed."], outcome: "Needs revision" },
      { id: 16, cells: ["Decision needed: approve the new policy."], outcome: "OK" },
      { id: 17, cells: ["We will ideate on next steps."], outcome: "Needs revision" },
      { id: 18, cells: ["Training completion is trending positively."], outcome: "Needs revision" },
      { id: 19, cells: ["Our ecosystem is mission-critical."], outcome: "Needs revision" },
      { id: 20, cells: ["Audit went well."], outcome: "Needs revision" },
      { id: 21, cells: ["30-day outlook: continued focus on remediation."], outcome: "Needs revision" },
      { id: 22, cells: ["Data classification is largely complete."], outcome: "Needs revision" },
      { id: 23, cells: ["We are GDPR-aligned."], outcome: "Needs revision" },
      { id: 24, cells: ["Open decision: vendor offboarding."], outcome: "OK" },
      { id: 25, cells: ["Things are improving across the board."], outcome: "Needs revision" },
    ],
  },
  "LRC-001/2": {
    title: "Privacy Notice Review & Gap Assessment",
    standard: "GDPR (EU) 2016/679 — Article 13 & 14 (information to be provided)",
    columns: ["Mandatory element (Art 13/14)", "Article"],
    outcomes: ["Present", "Partially present", "Absent"],
    clean: "Present",
    noteMode: "nonClean",
    noteLabel: "Gap note",
    feedsNext: "Feeds the Gap-Check Report & revised privacy notice draft.",
    rows: [
      { id: 1, cells: ["Identity & contact details of the controller", "13(1)(a)"], outcome: "Present" },
      { id: 2, cells: ["Contact details of the Data Protection Officer", "13(1)(b)"], outcome: "Absent" },
      { id: 3, cells: ["Purposes of the processing", "13(1)(c)"], outcome: "Present" },
      { id: 4, cells: ["Legal basis for the processing", "13(1)(c)"], outcome: "Partially present" },
      { id: 5, cells: ["Legitimate interests pursued (if that basis used)", "13(1)(d)"], outcome: "Absent" },
      { id: 6, cells: ["Recipients or categories of recipients", "13(1)(e)"], outcome: "Partially present" },
      { id: 7, cells: ["Transfers to third countries + safeguards", "13(1)(f)"], outcome: "Absent" },
      { id: 8, cells: ["Retention period or criteria", "13(2)(a)"], outcome: "Absent" },
      { id: 9, cells: ["Data-subject rights (access, erasure, etc.)", "13(2)(b)"], outcome: "Partially present" },
      { id: 10, cells: ["Right to withdraw consent", "13(2)(c)"], outcome: "Present" },
      { id: 11, cells: ["Right to lodge a complaint with a supervisory authority", "13(2)(d)"], outcome: "Absent" },
      { id: 12, cells: ["Whether provision is statutory/contractual + consequences", "13(2)(e)"], outcome: "Absent" },
      { id: 13, cells: ["Existence of automated decision-making / profiling", "13(2)(f)"], outcome: "Partially present" },
      { id: 14, cells: ["Source of the data (where not collected from the subject)", "14(2)(f)"], outcome: "Absent" },
    ],
  },
  "AA-003/3.5": {
    title: "Privacy Data-Flow Mapping & GDPR Applicability",
    standard: "GDPR (EU) 2016/679 — Art 35 (DPIA) + EDPB nine-criteria; Art 4/13/14/30",
    columns: ["Process", "EDPB criterion"],
    outcomes: ["Not met", "Met"],
    clean: "Not met",
    noteMode: "none",
    noteLabel: null,
    feedsNext: "Feeds the DPIA Screening Form disposition (DPIA required / not required).",
    rows: [
      { id: 1, cells: ["Student enrolment & account registration", "Evaluation or scoring (incl. profiling/prediction)"], outcome: "Not met" },
      { id: 2, cells: ["Student enrolment & account registration", "Automated decision-making with legal/similar effect"], outcome: "Not met" },
      { id: 3, cells: ["Student enrolment & account registration", "Systematic monitoring"], outcome: "Not met" },
      { id: 4, cells: ["Student enrolment & account registration", "Sensitive data or data of a highly personal nature"], outcome: "Met" },
      { id: 5, cells: ["Student enrolment & account registration", "Data processed on a large scale"], outcome: "Met" },
      { id: 6, cells: ["Student enrolment & account registration", "Matching or combining datasets"], outcome: "Not met" },
      { id: 7, cells: ["Student enrolment & account registration", "Data concerning vulnerable data subjects"], outcome: "Met" },
      { id: 8, cells: ["Student enrolment & account registration", "Innovative use / new technology"], outcome: "Not met" },
      { id: 9, cells: ["Student enrolment & account registration", "Prevents data subjects exercising a right / using a service"], outcome: "Not met" },
      { id: 10, cells: ["Online proctoring / exam monitoring", "Evaluation or scoring (incl. profiling/prediction)"], outcome: "Met" },
      { id: 11, cells: ["Online proctoring / exam monitoring", "Automated decision-making with legal/similar effect"], outcome: "Not met" },
      { id: 12, cells: ["Online proctoring / exam monitoring", "Systematic monitoring"], outcome: "Met" },
      { id: 13, cells: ["Online proctoring / exam monitoring", "Sensitive data or data of a highly personal nature"], outcome: "Met" },
      { id: 14, cells: ["Online proctoring / exam monitoring", "Data processed on a large scale"], outcome: "Not met" },
      { id: 15, cells: ["Online proctoring / exam monitoring", "Matching or combining datasets"], outcome: "Not met" },
      { id: 16, cells: ["Online proctoring / exam monitoring", "Data concerning vulnerable data subjects"], outcome: "Met" },
      { id: 17, cells: ["Online proctoring / exam monitoring", "Innovative use / new technology"], outcome: "Met" },
      { id: 18, cells: ["Online proctoring / exam monitoring", "Prevents data subjects exercising a right / using a service"], outcome: "Not met" },
      { id: 19, cells: ["Marketing newsletter sign-up", "Evaluation or scoring (incl. profiling/prediction)"], outcome: "Not met" },
      { id: 20, cells: ["Marketing newsletter sign-up", "Automated decision-making with legal/similar effect"], outcome: "Not met" },
      { id: 21, cells: ["Marketing newsletter sign-up", "Systematic monitoring"], outcome: "Not met" },
      { id: 22, cells: ["Marketing newsletter sign-up", "Sensitive data or data of a highly personal nature"], outcome: "Not met" },
      { id: 23, cells: ["Marketing newsletter sign-up", "Data processed on a large scale"], outcome: "Not met" },
      { id: 24, cells: ["Marketing newsletter sign-up", "Matching or combining datasets"], outcome: "Not met" },
      { id: 25, cells: ["Marketing newsletter sign-up", "Data concerning vulnerable data subjects"], outcome: "Not met" },
      { id: 26, cells: ["Marketing newsletter sign-up", "Innovative use / new technology"], outcome: "Not met" },
      { id: 27, cells: ["Marketing newsletter sign-up", "Prevents data subjects exercising a right / using a service"], outcome: "Not met" },
    ],
  },
  "QA-001/2": {
    title: "GRC Document Quality Review",
    standard: "ISO/IEC 27001:2022 — Clause 7.5.2/7.5.3 (documented information); Annex A 5.36",
    columns: ["Document", "Quality criterion"],
    outcomes: ["Pass", "Deficiency"],
    clean: "Pass",
    noteMode: "nonClean",
    noteLabel: "Correction request",
    feedsNext: "Feeds the Quality Review Report & Correction Tracking Log.",
    rows: [
      { id: 1, cells: ["Information Security Policy", "Document control block complete"], outcome: "Pass" },
      { id: 2, cells: ["Information Security Policy", "Version number present & correct"], outcome: "Pass" },
      { id: 3, cells: ["Information Security Policy", "Approval signatures present"], outcome: "Pass" },
      { id: 4, cells: ["Information Security Policy", "Current review date (not overdue)"], outcome: "Deficiency" },
      { id: 5, cells: ["Information Security Policy", "Scope accurately stated"], outcome: "Pass" },
      { id: 6, cells: ["Information Security Policy", "Policy statement complete"], outcome: "Pass" },
      { id: 7, cells: ["Information Security Policy", "Internal consistency (no contradictions)"], outcome: "Pass" },
      { id: 8, cells: ["Information Security Policy", "Plain-language compliance"], outcome: "Deficiency" },
      { id: 9, cells: ["Information Security Policy", "ISO 27001 control references correct"], outcome: "Deficiency" },
      { id: 10, cells: ["Information Security Policy", "Roles & responsibilities defined"], outcome: "Pass" },
      { id: 11, cells: ["Access Control Procedure", "Document control block complete"], outcome: "Deficiency" },
      { id: 12, cells: ["Access Control Procedure", "Version number present & correct"], outcome: "Pass" },
      { id: 13, cells: ["Access Control Procedure", "Approval signatures present"], outcome: "Deficiency" },
      { id: 14, cells: ["Access Control Procedure", "Current review date (not overdue)"], outcome: "Pass" },
      { id: 15, cells: ["Access Control Procedure", "Scope accurately stated"], outcome: "Pass" },
      { id: 16, cells: ["Access Control Procedure", "Policy statement complete"], outcome: "Pass" },
      { id: 17, cells: ["Access Control Procedure", "Internal consistency (no contradictions)"], outcome: "Deficiency" },
      { id: 18, cells: ["Access Control Procedure", "Plain-language compliance"], outcome: "Pass" },
      { id: 19, cells: ["Access Control Procedure", "ISO 27001 control references correct"], outcome: "Pass" },
      { id: 20, cells: ["Access Control Procedure", "Roles & responsibilities defined"], outcome: "Deficiency" },
      { id: 21, cells: ["Incident Response Procedure", "Document control block complete"], outcome: "Pass" },
      { id: 22, cells: ["Incident Response Procedure", "Version number present & correct"], outcome: "Deficiency" },
      { id: 23, cells: ["Incident Response Procedure", "Approval signatures present"], outcome: "Pass" },
      { id: 24, cells: ["Incident Response Procedure", "Current review date (not overdue)"], outcome: "Deficiency" },
      { id: 25, cells: ["Incident Response Procedure", "Scope accurately stated"], outcome: "Deficiency" },
      { id: 26, cells: ["Incident Response Procedure", "Policy statement complete"], outcome: "Pass" },
      { id: 27, cells: ["Incident Response Procedure", "Internal consistency (no contradictions)"], outcome: "Pass" },
      { id: 28, cells: ["Incident Response Procedure", "Plain-language compliance"], outcome: "Pass" },
      { id: 29, cells: ["Incident Response Procedure", "ISO 27001 control references correct"], outcome: "Deficiency" },
      { id: 30, cells: ["Incident Response Procedure", "Roles & responsibilities defined"], outcome: "Pass" },
    ],
  },
};

export function getApplyTask(taskCode?: string, activityCode?: string): ApplyTask | undefined {
  if (!taskCode || !activityCode) return undefined;
  return APPLY_TASKS[`${taskCode}/${activityCode}`];
}
