// Identify-verb worked tasks (dataset + answer key). Source: Identify_Verb_Task_Register.xlsx.
// Each task: the mentee states the flagging criterion, scans the dataset, flags rows meeting
// the criterion, and gives every flag a proposed action + accountable role. `shouldFlag` is the
// answer key. Layer 1 = action+owner on every flag + criterion stated; submission is gated on
// flagging exactly the answer-key rows (see IdentifyWorkspace).

export interface IdentifyRow {
  id: number;
  /** Descriptive column values, aligned to `columns`. */
  cells: string[];
  /** Answer key: whether this row meets the flagging criterion. */
  shouldFlag: boolean;
}

export interface IdentifyTask {
  title: string;
  standard: string;
  /** The flagging criterion the mentee states before scanning (Layer 1). */
  criterion: string;
  /** Header labels for the descriptive columns. */
  columns: string[];
  rows: IdentifyRow[];
  /** Accountable-role options for the per-flag owner picker. */
  owners: string[];
  /** Where the flagged list feeds next. */
  feedsNext: string;
}

export const IDENTIFY_TASKS: Record<string, IdentifyTask> = {
  "AA-001/1.6": {
    title: "Identify Ownerless Assets",
    standard: "ISO 27001 A.5.9 Inventory; A.5.2 Roles & responsibilities",
    criterion: "Flag any asset where the Owner field is blank or 'Unassigned'.",
    columns: ["Asset", "Owner (current)"],
    owners: ["Department Head / IT Operations Manager", "Data Platform Lead", "Head of Engineering", "CISO", "HR Systems Manager"],
    feedsNext: "Feeds the Review / Present steps — the flagged ownerless-asset list with owners.",
    rows: [
      { id: 1, cells: ["CRM SaaS platform", "Service Owner – CRM"], shouldFlag: false },
      { id: 2, cells: ["Billing/ERP system", "Financial Controller"], shouldFlag: false },
      { id: 3, cells: ["Customer PII database", "Data Platform Lead"], shouldFlag: false },
      { id: 4, cells: ["Source code repository", "Head of Engineering"], shouldFlag: false },
      { id: 5, cells: ["Marketing analytics SaaS", "Unassigned"], shouldFlag: true },
      { id: 6, cells: ["Legacy reporting server", ""], shouldFlag: true },
      { id: 7, cells: ["Email/SaaS suite", "IT Operations Manager"], shouldFlag: false },
      { id: 8, cells: ["Payroll system", "Chief Human Resources Officer"], shouldFlag: false },
      { id: 9, cells: ["Shadow Jira instance", ""], shouldFlag: true },
      { id: 10, cells: ["Internal wiki", "Head of Engineering"], shouldFlag: false },
      { id: 11, cells: ["Backup vault", "Data Platform Lead"], shouldFlag: false },
      { id: 12, cells: ["Contractor laptop pool", "Unassigned"], shouldFlag: true },
      { id: 13, cells: ["SIEM platform", "Chief Information Security Officer"], shouldFlag: false },
      { id: 14, cells: ["Public website", "Head of Marketing"], shouldFlag: false },
      { id: 15, cells: ["Test CRM sandbox", ""], shouldFlag: true },
      { id: 16, cells: ["IdP / SSO", "Chief Information Security Officer"], shouldFlag: false },
      { id: 17, cells: ["Container registry", "Head of Engineering"], shouldFlag: false },
      { id: 18, cells: ["Data warehouse", "Unassigned"], shouldFlag: true },
      { id: 19, cells: ["Office file server", "IT Operations Manager"], shouldFlag: false },
      { id: 20, cells: ["Monitoring/Grafana", "SRE Lead"], shouldFlag: false },
      { id: 21, cells: ["Old VPN appliance", ""], shouldFlag: true },
      { id: 22, cells: ["HR SaaS", "HR Systems Manager"], shouldFlag: false },
      { id: 23, cells: ["Document e-sign tool", "Unassigned"], shouldFlag: true },
      { id: 24, cells: ["Code signing keys", "Chief Information Security Officer"], shouldFlag: false },
    ],
  },
  "CRM-002/8.7": {
    title: "Identify Top Uncontrolled Risks",
    standard: "ISO 27001:2022 — Annex A (93 controls, 4 themes)",
    criterion: "Flag risks where control coverage = Gap AND exposure = High.",
    columns: ["Risk (from matrix gap)", "Process", "Control coverage", "Exposure"],
    owners: ["Compliance Manager / Process Owner", "CISO", "IT Manager", "Process Owner"],
    feedsNext: "Feeds the matrix review — the top uncontrolled-risk list with mitigation owner.",
    rows: [
      { id: 1, cells: ["No encryption of backups", "Customer data backup", "Gap", "High"], shouldFlag: true },
      { id: 2, cells: ["Unrestricted prod DB access", "User onboarding", "Gap", "High"], shouldFlag: true },
      { id: 3, cells: ["No code review gate", "Software release", "Partial", "Medium"], shouldFlag: false },
      { id: 4, cells: ["Vendor with no security review", "Vendor onboarding", "Gap", "High"], shouldFlag: true },
      { id: 5, cells: ["No log monitoring", "Incident handling", "Gap", "High"], shouldFlag: true },
      { id: 6, cells: ["Shared admin credentials", "User onboarding", "Gap", "High"], shouldFlag: true },
      { id: 7, cells: ["Manual offboarding only", "User offboarding", "Partial", "Medium"], shouldFlag: false },
      { id: 8, cells: ["No DR test", "Customer data backup", "Gap", "Medium"], shouldFlag: false },
      { id: 9, cells: ["Unpatched build server", "Software release", "Partial", "Medium"], shouldFlag: false },
      { id: 10, cells: ["No data classification", "Customer data backup", "Partial", "Low"], shouldFlag: false },
      { id: 11, cells: ["Default cloud config", "Software release", "Gap", "High"], shouldFlag: true },
      { id: 12, cells: ["No MFA on VPN", "Remote access", "Gap", "High"], shouldFlag: true },
      { id: 13, cells: ["Email auto-forward allowed", "Comms", "Partial", "Low"], shouldFlag: false },
      { id: 14, cells: ["No vendor DPA", "Vendor onboarding", "Gap", "Medium"], shouldFlag: false },
      { id: 15, cells: ["Excessive access rights", "User onboarding", "Partial", "Medium"], shouldFlag: false },
      { id: 16, cells: ["No incident runbook", "Incident handling", "Gap", "Medium"], shouldFlag: false },
      { id: 17, cells: ["Unencrypted laptops", "Remote access", "Gap", "High"], shouldFlag: true },
      { id: 18, cells: ["No change approval", "Software release", "Partial", "Low"], shouldFlag: false },
    ],
  },
  "CRM-003/9.4": {
    title: "Identify Unmapped SOC 2 Criteria",
    standard: "SOC 2 Type II (AICPA TSC) — CC1–CC9",
    criterion: "Flag any CC point where 'Internal control mapped?' = N.",
    columns: ["SOC 2 CC point", "Internal control mapped? (Y/N)"],
    owners: ["Control Owner / Information Security Auditor", "Compliance Manager", "CISO", "IT Manager"],
    feedsNext: "Feeds the ISO cross-reference / readiness dashboard — the unmapped-CC list.",
    rows: [
      { id: 1, cells: ["CC1.1 Integrity & ethics", "Y"], shouldFlag: false },
      { id: 2, cells: ["CC1.2 Board oversight", "Y"], shouldFlag: false },
      { id: 3, cells: ["CC1.4 Competence/training", "Y"], shouldFlag: false },
      { id: 4, cells: ["CC2.1 Quality information", "Y"], shouldFlag: false },
      { id: 5, cells: ["CC3.1 Risk objectives", "N"], shouldFlag: true },
      { id: 6, cells: ["CC3.2 Risk identification", "Y"], shouldFlag: false },
      { id: 7, cells: ["CC4.1 Monitoring controls", "N"], shouldFlag: true },
      { id: 8, cells: ["CC5.2 Technology controls", "Y"], shouldFlag: false },
      { id: 9, cells: ["CC6.1 Logical access", "Y"], shouldFlag: false },
      { id: 10, cells: ["CC6.2 Registration/authorisation", "Y"], shouldFlag: false },
      { id: 11, cells: ["CC6.3 Access removal", "N"], shouldFlag: true },
      { id: 12, cells: ["CC6.6 Boundary protection", "N"], shouldFlag: true },
      { id: 13, cells: ["CC6.7 Data in transit", "Y"], shouldFlag: false },
      { id: 14, cells: ["CC7.1 Vulnerability detection", "Y"], shouldFlag: false },
      { id: 15, cells: ["CC7.2 Security monitoring", "N"], shouldFlag: true },
      { id: 16, cells: ["CC7.4 Incident response", "Y"], shouldFlag: false },
      { id: 17, cells: ["CC8.1 Change management", "N"], shouldFlag: true },
      { id: 18, cells: ["CC9.2 Vendor risk", "Y"], shouldFlag: false },
    ],
  },
  "TPRM-001/6": {
    title: "Identify Vendors Missing a DPA",
    standard: "ISO 27001 A.5.19/5.20; GDPR Art 28 (DPA)",
    criterion: "Flag vendors where DPA is None/Expired AND data access is process or store.",
    columns: ["Vendor", "Data access", "DPA status"],
    owners: ["Vendor/Third-Party Risk Analyst / Procurement", "Procurement", "Compliance Manager", "DPO"],
    feedsNext: "Feeds the Supplier Register summary — the missing-DPA vendor list with owner.",
    rows: [
      { id: 1, cells: ["Cloud IaaS Co", "store", "Signed"], shouldFlag: false },
      { id: 2, cells: ["Email SaaS Co", "store", "None"], shouldFlag: true },
      { id: 3, cells: ["Payroll Co", "store", "Expired"], shouldFlag: true },
      { id: 4, cells: ["CRM SaaS Co", "store", "Signed"], shouldFlag: false },
      { id: 5, cells: ["Marketing email Co", "process", "None"], shouldFlag: true },
      { id: 6, cells: ["Helpdesk SaaS Co", "process", "Signed"], shouldFlag: false },
      { id: 7, cells: ["Analytics Co", "process", "None"], shouldFlag: true },
      { id: 8, cells: ["Background-check Co", "store", "None"], shouldFlag: true },
      { id: 9, cells: ["Translation Co", "view", "None"], shouldFlag: false },
      { id: 10, cells: ["Office cleaning Co", "none", "None"], shouldFlag: false },
      { id: 11, cells: ["Stationery Co", "none", "None"], shouldFlag: false },
      { id: 12, cells: ["Legal advisors Co", "view", "Signed"], shouldFlag: false },
      { id: 13, cells: ["Accounting Co", "process", "Expired"], shouldFlag: true },
      { id: 14, cells: ["Survey tool Co", "process", "None"], shouldFlag: true },
      { id: 15, cells: ["Recruitment Co", "process", "None"], shouldFlag: true },
      { id: 16, cells: ["Backup/DR Co", "store", "Signed"], shouldFlag: false },
      { id: 17, cells: ["SIEM SaaS Co", "process", "Signed"], shouldFlag: false },
      { id: 18, cells: ["Catering Co", "none", "None"], shouldFlag: false },
      { id: 19, cells: ["Courier Co", "view", "None"], shouldFlag: false },
      { id: 20, cells: ["E-sign Co", "store", "None"], shouldFlag: true },
      { id: 21, cells: ["Password mgr Co", "store", "Signed"], shouldFlag: false },
      { id: 22, cells: ["Telecoms Co", "view", "Signed"], shouldFlag: false },
    ],
  },
  "BCRP-001/5": {
    title: "Identify Single Points of Failure",
    standard: "ISO 27001 A.5.29 (Security during disruption); A.5.30 (ICT readiness)",
    criterion: "Flag any dependency where 'Backup/alternative?' = N (single point of failure).",
    columns: ["Critical function", "Key dependency", "Backup/alternative? (Y/N)"],
    owners: ["Business Continuity Analyst / Function Owner", "Function Owner", "IT Manager", "Operations Manager"],
    feedsNext: "Feeds the BIA Summary Table — the flagged SPOF list with workaround + owner.",
    rows: [
      { id: 1, cells: ["Inbound call handling", "ACD/telephony platform", "N"], shouldFlag: true },
      { id: 2, cells: ["Agent authentication", "Single SSO provider", "N"], shouldFlag: true },
      { id: 3, cells: ["Ticketing", "Helpdesk SaaS", "Y"], shouldFlag: false },
      { id: 4, cells: ["Payroll run", "Payroll vendor", "N"], shouldFlag: true },
      { id: 5, cells: ["Knowledge base", "Internal wiki", "Y"], shouldFlag: false },
      { id: 6, cells: ["Customer data access", "Primary CRM", "N"], shouldFlag: true },
      { id: 7, cells: ["Workforce scheduling", "WFM tool", "Y"], shouldFlag: false },
      { id: 8, cells: ["Email", "Email SaaS", "Y"], shouldFlag: false },
      { id: 9, cells: ["Quality monitoring", "Call-recording system", "N"], shouldFlag: true },
      { id: 10, cells: ["Network connectivity", "Single ISP link", "N"], shouldFlag: true },
      { id: 11, cells: ["Reporting", "BI platform", "Y"], shouldFlag: false },
      { id: 12, cells: ["Identity provisioning", "One IT admin (key person)", "N"], shouldFlag: true },
      { id: 13, cells: ["Document storage", "File server FS01", "Y"], shouldFlag: false },
      { id: 14, cells: ["Backups", "Single backup vendor", "Y"], shouldFlag: false },
      { id: 15, cells: ["Escalation comms", "Manager phone tree", "Y"], shouldFlag: false },
      { id: 16, cells: ["Power", "Single UPS, no generator", "N"], shouldFlag: true },
      { id: 17, cells: ["VPN remote access", "One VPN appliance", "N"], shouldFlag: true },
      { id: 18, cells: ["Translation/localisation", "Sole vendor", "N"], shouldFlag: true },
    ],
  },

  // ── Selection and gap-scan steps ──────────────────────────────────────────────────────────
  // Several of these steps read as "select N items with the mentor", which has no answer key
  // unless the criterion is made objective. Each criterion below is therefore written as a rule
  // the dataset can be tested against, so the selection is defensible rather than a preference.
  "CRM-002/8.1": {
    title: "Select In-Scope Business Processes",
    standard: "ISO 27001 Cl 4.3 Scope; A.5.9 Inventory",
    criterion: "Flag a process only where it BOTH handles in-scope information AND has a named process owner. A process with no owner cannot be assessed against a control, and one that touches no in-scope information is out of scope however important it is.",
    columns: ["Business process", "Handles in-scope information?", "Named process owner"],
    owners: ["Compliance Manager", "IT Manager", "HR Manager", "Head of Engineering", "Financial Controller"],
    feedsNext: "Feeds Step 8.2 (control applicability) and 8.3 (mapping).",
    rows: [
      { id: 1, cells: ["User onboarding / joiner access", "Yes — identity and HR data", "IT Manager"], shouldFlag: true },
      { id: 2, cells: ["Software release and deployment", "Yes — source and production config", "Head of Engineering"], shouldFlag: true },
      { id: 3, cells: ["Customer data backup and restore", "Yes — customer records", "Data Platform Lead"], shouldFlag: true },
      { id: 4, cells: ["Vendor contracting", "Yes — contracts and vendor data", "Compliance Manager"], shouldFlag: true },
      { id: 5, cells: ["Incident logging and triage", "Yes — incident records", "CISO"], shouldFlag: true },
      { id: 6, cells: ["Office facilities booking", "No", "Facilities Coordinator"], shouldFlag: false },
      { id: 7, cells: ["Marketing campaign design", "No — no personal data at this stage", "Marketing Lead"], shouldFlag: false },
      { id: 8, cells: ["Expenses reimbursement", "Yes — employee bank details", "Unassigned"], shouldFlag: false },
      { id: 9, cells: ["Travel booking", "No", "Unassigned"], shouldFlag: false },
      { id: 10, cells: ["Payroll processing", "Yes — but operated by the parent entity", "Not ours — group Payroll"], shouldFlag: false },
    ],
  },
  "CRM-002/8.2": {
    title: "Identify Applicable Annex A Controls",
    standard: "ISO 27001 Annex A (all four themes); Cl 6.1.3 Statement of Applicability",
    criterion: "Flag a control where at least one of the five in-scope processes could not operate securely without it. Applicability follows the process, not the theme — a control is not applicable merely because the organisation is large enough to have heard of it.",
    columns: ["Annex A control", "Theme", "Touches an in-scope process?"],
    owners: ["Compliance Manager", "IT Manager", "CISO", "Head of Engineering"],
    feedsNext: "Feeds Step 8.3 (mapping) and 8.4 (implementation status).",
    rows: [
      { id: 1, cells: ["A.5.18 Access rights", "Organisational", "Yes — user onboarding"], shouldFlag: true },
      { id: 2, cells: ["A.8.2 Privileged access rights", "Technological", "Yes — deployment and backup"], shouldFlag: true },
      { id: 3, cells: ["A.8.13 Information backup", "Technological", "Yes — customer data backup"], shouldFlag: true },
      { id: 4, cells: ["A.8.32 Change management", "Technological", "Yes — software release"], shouldFlag: true },
      { id: 5, cells: ["A.5.19 Supplier relationships", "Organisational", "Yes — vendor contracting"], shouldFlag: true },
      { id: 6, cells: ["A.5.26 Response to incidents", "Organisational", "Yes — incident logging"], shouldFlag: true },
      { id: 7, cells: ["A.7.4 Physical security monitoring", "Physical", "No — no in-scope process is site-dependent"], shouldFlag: false },
      { id: 8, cells: ["A.7.13 Equipment maintenance", "Physical", "No"], shouldFlag: false },
      { id: 9, cells: ["A.6.4 Disciplinary process", "People", "No — supports policy, not these processes"], shouldFlag: false },
      { id: 10, cells: ["A.8.30 Outsourced development", "Technological", "No — development is in-house"], shouldFlag: false },
      { id: 11, cells: ["A.5.7 Threat intelligence", "Organisational", "No — no in-scope process consumes it yet"], shouldFlag: false },
      { id: 12, cells: ["A.8.24 Use of cryptography", "Technological", "Yes — backup and customer data"], shouldFlag: true },
    ],
  },
  "CRM-001/7.6": {
    title: "Identify Obligation Gaps",
    standard: "ISO 27001 A.5.31 Legal and contractual requirements",
    criterion: "Flag an obligation where there is NO named control owner, OR no evidence that compliance is actually demonstrated. Either one alone is a gap: an owner with no evidence cannot prove compliance, and evidence with no owner will not survive that person leaving.",
    columns: ["Obligation", "Control owner", "Evidence of compliance"],
    owners: ["Compliance Manager", "DPO", "CISO", "Financial Controller"],
    feedsNext: "Feeds Step 7.7 (mentor review) and 7.8 (register and review scheduling).",
    rows: [
      { id: 1, cells: ["GDPR Art. 30 — records of processing", "DPO", "RoPA maintained, last reviewed this quarter"], shouldFlag: false },
      { id: 2, cells: ["GDPR Art. 33 — breach notification within 72h", "CISO", "None — no documented notification procedure"], shouldFlag: true },
      { id: 3, cells: ["Customer contract — annual security attestation", "Unassigned", "Provided last year, ad hoc"], shouldFlag: true },
      { id: 4, cells: ["Tax law — 7-year retention of financial records", "Financial Controller", "Archive policy and retention log"], shouldFlag: false },
      { id: 5, cells: ["Employment law — right-to-work record retention", "HR Manager", "HR system records with retention rule"], shouldFlag: false },
      { id: 6, cells: ["ISO 27001 Cl 9.2 — internal audit programme", "Compliance Manager", "None — no audit has been run"], shouldFlag: true },
      { id: 7, cells: ["Customer contract — sub-processor disclosure", "Unassigned", "None"], shouldFlag: true },
      { id: 8, cells: ["Sector code — incident reporting to the regulator", "CISO", "One reported incident on file"], shouldFlag: false },
      { id: 9, cells: ["GDPR Art. 32 — security of processing", "CISO", "MFA and SSO configuration evidence"], shouldFlag: false },
      { id: 10, cells: ["Vendor contract — right to audit exercised annually", "Compliance Manager", "None — never exercised"], shouldFlag: true },
    ],
  },
  "GRM-003/6.6": {
    title: "Identify Gaps Against Tier 2",
    standard: "NIST CSF 2.0 Implementation Tiers; ISO 27001 Cl 10.2",
    criterion: "Flag any CSF Function currently assessed below Tier 2 (Risk-Informed). Tier 2 is the stated minimum target, so a Function at Tier 1 is a gap by definition — regardless of how well the department performs elsewhere.",
    columns: ["CSF Function / Category", "Assessed Tier", "Evidence behind the score"],
    owners: ["GRC Program Manager", "Department Head", "CISO", "IT Manager"],
    feedsNext: "Feeds Step 6.7 (improvement roadmap) and 6.8 (presentation).",
    rows: [
      { id: 1, cells: ["GOVERN — roles and responsibilities", "Tier 2", "Named owners, reviewed annually"], shouldFlag: false },
      { id: 2, cells: ["GOVERN — risk management strategy", "Tier 1", "No documented appetite or strategy"], shouldFlag: true },
      { id: 3, cells: ["IDENTIFY — asset management", "Tier 2", "Inventory maintained, owner assigned"], shouldFlag: false },
      { id: 4, cells: ["IDENTIFY — risk assessment", "Tier 1", "Ad hoc; no repeatable method"], shouldFlag: true },
      { id: 5, cells: ["PROTECT — identity and access", "Tier 3", "MFA, SSO, documented joiner process"], shouldFlag: false },
      { id: 6, cells: ["PROTECT — awareness and training", "Tier 2", "Annual training with completion records"], shouldFlag: false },
      { id: 7, cells: ["DETECT — continuous monitoring", "Tier 1", "Alerts exist; no triage record or thresholds"], shouldFlag: true },
      { id: 8, cells: ["RESPOND — incident management", "Tier 2", "Group procedure applies and is known"], shouldFlag: false },
      { id: 9, cells: ["RECOVER — recovery planning", "Tier 2", "Backups run; restore process documented"], shouldFlag: false },
    ],
  },
  "TV-002/1": {
    title: "Select Policies for Spot-Check Testing",
    standard: "ISO 27001 A.5.35 Independent review; Cl 9.2",
    criterion: "Flag a policy only where it is BOTH formally approved and in force, AND would produce testable evidence. A draft policy has no compliance to test, and an approved one that produces no record cannot be spot-checked however important it is.",
    columns: ["Policy", "Status", "Produces testable evidence?"],
    owners: ["Compliance Manager", "IT Manager", "HR Manager", "CISO"],
    feedsNext: "Feeds Step 2 (control statements) and Step 3 (evidence request).",
    rows: [
      { id: 1, cells: ["Acceptable Use Policy", "Approved, in force", "Yes — signed acknowledgements"], shouldFlag: true },
      { id: 2, cells: ["Remote Working Policy", "Approved, in force", "Yes — endpoint encryption reports"], shouldFlag: true },
      { id: 3, cells: ["Security Awareness Policy", "Approved, in force", "Yes — training completion records"], shouldFlag: true },
      { id: 4, cells: ["Data Classification Policy", "Draft — not yet approved", "Would be, once approved"], shouldFlag: false },
      { id: 5, cells: ["Clear Desk Policy", "Approved, in force", "No — no record is generated"], shouldFlag: false },
      { id: 6, cells: ["Incident Reporting Procedure", "Draft — pending from DD-001", "Not yet"], shouldFlag: false },
      { id: 7, cells: ["Password Policy", "Superseded by the AUP", "N/A"], shouldFlag: false },
      { id: 8, cells: ["Social Media Guidance", "Guidance, not policy", "No"], shouldFlag: false },
    ],
  },
  "IE-001/1": {
    title: "Select IG1 Safeguards for Remediation",
    standard: "CIS Controls v8 IG1; ISO 27001 Cl 8.1",
    criterion: "Flag a Safeguard that is currently Not Implemented AND achievable inside the three-week window with tooling the organisation already has. A safeguard needing procurement or a system change belongs on the roadmap, not in this sprint — and one already implemented is not remediation.",
    columns: ["IG1 Safeguard", "Current state", "Deliverable in 3 weeks with existing tooling?"],
    owners: ["IT Manager", "Compliance Manager", "Head of Platform", "Security Eng. Lead"],
    feedsNext: "Feeds Step 2 (task cards) and Step 3 (weekly tracking).",
    rows: [
      { id: 1, cells: ["4.7 Manage default accounts", "Not Implemented", "Yes — configuration change only"], shouldFlag: true },
      { id: 2, cells: ["6.5 Require MFA for administrative access", "Not Implemented", "Yes — identity provider already supports it"], shouldFlag: true },
      { id: 3, cells: ["5.1 Establish an account inventory", "Not Implemented", "Yes — export and reconcile"], shouldFlag: true },
      { id: 4, cells: ["3.3 Configure data access control lists", "Not Implemented", "Yes — permissions review"], shouldFlag: true },
      { id: 5, cells: ["8.2 Collect audit logs", "Not Implemented", "Yes — logging exists but is switched off"], shouldFlag: true },
      { id: 6, cells: ["1.1 Establish an enterprise asset inventory", "Implemented", "N/A"], shouldFlag: false },
      { id: 7, cells: ["2.1 Establish a software inventory", "Implemented", "N/A"], shouldFlag: false },
      { id: 8, cells: ["7.3 Perform automated patch management", "Not Implemented", "No — needs a tool the organisation does not have"], shouldFlag: false },
      { id: 9, cells: ["11.2 Perform automated backups", "Partial", "No — needs storage procurement"], shouldFlag: false },
      { id: 10, cells: ["14.1 Establish a security awareness programme", "Not Implemented", "No — content build is DD-002, weeks away"], shouldFlag: false },
    ],
  },
  "PE-002/2": {
    title: "Identify Expected Audit Evidence",
    standard: "ISO 27001 Cl 9.2 Internal audit; A.5.35",
    criterion: "Flag an evidence item an auditor would expect for the selected controls. Expectation follows the control's own wording: if the control says the activity is performed periodically, the auditor expects a record for the period, not a snapshot taken the day before the audit.",
    columns: ["Evidence item", "Control it evidences", "Would an auditor expect this?"],
    owners: ["Information Security Auditor", "Compliance Manager", "IT Manager", "CISO"],
    feedsNext: "Feeds Step 3 (collection) and Step 4 (labelling).",
    rows: [
      { id: 1, cells: ["Signed periodic access review, with reviewer and date", "A.5.18 Access rights", "Yes — the control says periodic"], shouldFlag: true },
      { id: 2, cells: ["Identity-provider export showing MFA enforced", "A.8.5 Secure authentication", "Yes"], shouldFlag: true },
      { id: 3, cells: ["Leaver list reconciled to account disable timestamps", "A.5.18 Access rights", "Yes — timeliness is testable"], shouldFlag: true },
      { id: 4, cells: ["Restore test record with achieved recovery time", "A.8.13 Information backup", "Yes — 'tested regularly'"], shouldFlag: true },
      { id: 5, cells: ["Change approval records linked to deployments", "A.8.32 Change management", "Yes"], shouldFlag: true },
      { id: 6, cells: ["Screenshot of the backup schedule taken yesterday", "A.8.13 Information backup", "No — proves configuration, not operation over the period"], shouldFlag: false },
      { id: 7, cells: ["Marketing site uptime report", "—", "No — not in scope"], shouldFlag: false },
      { id: 8, cells: ["Vendor's marketing brochure claiming certification", "A.5.19 Supplier relationships", "No — a claim, not assurance"], shouldFlag: false },
      { id: 9, cells: ["Verbal confirmation from the system owner", "A.5.18 Access rights", "No — inquiry alone is not evidence of operation"], shouldFlag: false },
      { id: 10, cells: ["Incident tickets with timeline and closure", "A.5.26 Response to incidents", "Yes"], shouldFlag: true },
    ],
  },
  "QA-001/1": {
    title: "Select Documents for Quality Review",
    standard: "ISO 27001 Cl 7.5.2 Creating and updating; Cl 7.5.3",
    criterion: "Flag a document that is approved and in force AND is at or past its review date. A draft has no controlled version to review against, and a document reviewed last month will consume the exercise without finding anything.",
    columns: ["Document", "Status", "Review date"],
    owners: ["Compliance Manager", "Policy & Governance Analyst", "CISO", "DPO"],
    feedsNext: "Feeds Step 2 (review against the checklist) and Step 3 (correction requests).",
    rows: [
      { id: 1, cells: ["Information Security Policy v2.1", "Approved, in force", "Overdue by 4 months"], shouldFlag: true },
      { id: 2, cells: ["Acceptable Use Policy v1.3", "Approved, in force", "Due this month"], shouldFlag: true },
      { id: 3, cells: ["Data Retention Schedule v1.0", "Approved, in force", "Overdue by 7 months"], shouldFlag: true },
      { id: 4, cells: ["Incident Reporting Procedure", "Draft", "No review date set"], shouldFlag: false },
      { id: 5, cells: ["Remote Working Policy v2.0", "Approved, in force", "Reviewed last month"], shouldFlag: false },
      { id: 6, cells: ["Supplier Security Standard v1.1", "Approved, in force", "Not due for 8 months"], shouldFlag: false },
      { id: 7, cells: ["Business Continuity Plan", "Draft", "No review date set"], shouldFlag: false },
      { id: 8, cells: ["Password Policy v1.0", "Superseded", "N/A"], shouldFlag: false },
    ],
  },
};

export function getIdentifyTask(taskCode?: string, activityCode?: string): IdentifyTask | undefined {
  if (!taskCode || !activityCode) return undefined;
  return IDENTIFY_TASKS[`${taskCode}/${activityCode}`];
}
