// Review worked tasks (mentor quality-gate). Source: Review_Verb_Task_Register.xlsx.
// Mentee submits a near-final artefact with a cover note + confirms prior feedback addressed (Layer 1,
// the submit gate). The 5-dimension rubric, outcome (SIGN-OFF/REVISE) and RA-MENTOR coaching are the
// mentor's demo result shown after submitting for review.

export interface ReviewDim { dim: string; score: string; anchor: string; }

export interface ReviewTask {
  title: string; standard: string; reviewer: string;
  artefact: string; attempt: string;
  /** Example cover note (placeholder for the mentee's own). */
  coverExample: string;
  /** Prior grading feedback to confirm addressed (empty on a first submission). */
  feedback: string[];
  rubric: ReviewDim[]; aggregate: string; lowest: string;
  outcome: string; coaching: string; feedsNext: string;
}

export const REVIEW_TASKS: Record<string, ReviewTask> = {
  "AA-001/1.7": {
    title: "Information Asset Register", standard: "ISO 27001 A.5.9 Inventory; A.5.12 Classification", reviewer: "Policy & Governance Analyst · Analytical Sleuth",
    artefact: "Information Asset Register v1.0 (185 assets, classified, owners assigned)", attempt: "1 of 3",
    coverExample: "First submission. All 185 assets recorded and classified; 8 ownerless assets flagged with remediation owners; CIA rationale added for all Confidential items.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "All assets named with system/location; no vague entries." },
      { dim: "Standards Alignment", score: "4", anchor: "Three-tier scheme applied per A.5.12; personal-data items not Public." },
      { dim: "Reasoning Quality", score: "3", anchor: "Classification rationale sound; ownerless-asset findings logically derived." },
      { dim: "Communication Quality", score: "3", anchor: "Register readable; minor inconsistency in owner-role naming." },
      { dim: "Risk Awareness", score: "3", anchor: "Sensitivity recognised; could note retention risk for archived PII." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "SIGN-OFF",
    coaching: "You classified well — but ask yourself: are two of your 'Internal' shared drives really free of personal data? Walk me through how you'd confirm that before we sign off.", feedsNext: "Present the register for sign-off.",
  },
  "GRM-001/4.7": {
    title: "Basic Risk Register", standard: "ISO 27001 Clause 6.1.2/6.1.3 (risk assessment & treatment)", reviewer: "Cyber Risk Manager · Analytical Sleuth",
    artefact: "Basic Risk Register v2.0 (30 risks, 5×5 scored, treatments drafted)", attempt: "2 of 3",
    coverExample: "Revised after round-1 feedback: added threat sources to all risks, corrected 3 mis-banded categories, and added treatment owners + target dates.",
    feedback: ["Add an explicit threat source to every risk", "Fix 3 risks where the 5×5 category didn't match the score", "Assign a treatment owner and target date per risk"],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Risks specific with named assets and threat sources." },
      { dim: "Standards Alignment", score: "4", anchor: "Scoring and treatment align with Clause 6.1.2/6.1.3." },
      { dim: "Reasoning Quality", score: "4", anchor: "5×5 categories now match the arithmetic; treatment logic sound." },
      { dim: "Communication Quality", score: "3", anchor: "Clear; one-page management summary still a little dense." },
      { dim: "Risk Awareness", score: "4", anchor: "Top risks correctly prioritised by exposure." },
    ],
    aggregate: "3.8", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Strong recovery from round 1. Before you present: which single risk would you escalate first, and can you justify it from the matrix alone? Rehearse that answer.", feedsNext: "Present the top-5 risks to management.",
  },
  "CRM-002/8.8": {
    title: "ISO 27001 Control Matrix", standard: "ISO 27001 Annex A (93 controls, 4 themes)", reviewer: "Compliance Manager · Analytical Sleuth",
    artefact: "ISO 27001 Control Matrix v1.0 (5 processes × 93 controls)", attempt: "1 of 3",
    coverExample: "First submission. Applicability marked for all 5 processes; implementation status and evidence type documented; top-5 uncontrolled risks identified.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "3", anchor: "Most controls mapped specifically; a few 'N/A' lack rationale." },
      { dim: "Standards Alignment", score: "4", anchor: "Annex A mapping accurate across all four themes." },
      { dim: "Reasoning Quality", score: "3", anchor: "Gap-to-risk derivation logical." },
      { dim: "Communication Quality", score: "3", anchor: "Matrix legible; legend could be clearer." },
      { dim: "Risk Awareness", score: "2", anchor: "Under-weights the prod-DB access gap — a high-impact exposure treated as Medium." },
    ],
    aggregate: "3", lowest: "2", outcome: "SIGN-OFF",
    coaching: "Your mapping is solid, but look again at the production-database access gap. What's the worst-case if it's exploited? Re-justify its rating before we finalise.", feedsNext: "Feeds the readiness dashboard / briefing.",
  },
  "TV-001/7": {
    title: "Access Control Testing Report", standard: "ISO 27001 A.8.2/8.3/8.5/5.18 (access)", reviewer: "Information Security Auditor · Guardian Watchdog",
    artefact: "Access Control Testing Report v1.0 (30 accounts reviewed)", attempt: "1 of 3",
    coverExample: "First submission. Findings table complete with percentages; remediation actions listed for orphaned and dormant accounts.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "3", anchor: "Findings specific per account." },
      { dim: "Standards Alignment", score: "3", anchor: "Aligned with A.8.2 privileged-access expectations." },
      { dim: "Reasoning Quality", score: "3", anchor: "Logic mostly sound." },
      { dim: "Communication Quality", score: "3", anchor: "Report clear and well-structured." },
      { dim: "Risk Awareness", score: "1", anchor: "CRITICAL MISS: an orphaned ADMIN account (lapsed employee) was logged as low priority — fails to recognise the severity; this is the headline risk." },
    ],
    aggregate: "2.6", lowest: "1", outcome: "REVISE",
    coaching: "Stop before issuing. You found an orphaned admin account for someone who left — why is that not your number-one finding? Re-rank by blast radius and resubmit; we don't sign off with that buried.", feedsNext: "Issue the Access Control Testing Report to the IT Manager.",
  },
  "BCRP-001/8": {
    title: "BIA Report", standard: "ISO 27001 A.5.29/5.30 (continuity & ICT readiness)", reviewer: "Business Continuity & Resilience Analyst · Operational Maestro",
    artefact: "BIA Report v1.0 (1 department, 5 critical functions)", attempt: "1 of 3",
    coverExample: "First submission. Five critical functions ranked by impact; RTO/RPO set; 10 single points of failure flagged with proposed workarounds and owners.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Functions and dependencies specifically described." },
      { dim: "Standards Alignment", score: "3", anchor: "RTO/RPO consistent with A.5.30 readiness expectations." },
      { dim: "Reasoning Quality", score: "4", anchor: "Impact ranking well-reasoned." },
      { dim: "Communication Quality", score: "3", anchor: "Report clear; RTO/RPO table could note assumptions." },
      { dim: "Risk Awareness", score: "4", anchor: "SPOFs and continuity risks well recognised." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Good analysis. The single-ISP-link SPOF — what's the realistic cost of an hour's outage to call handling? Put a number on it; the manager will ask, and it strengthens your case for redundancy.", feedsNext: "Finalise and present the BIA Report.",
  },
  "CA-002/6": {
    title: "Executive Compliance Status Report", standard: "ISO 27001 Clause 9.3 (management review); 9.1", reviewer: "Compliance Manager · Bridge Builder",
    artefact: "Executive Compliance Status Report v2.0 (one page)", attempt: "2 of 3",
    coverExample: "Revised after round-1 feedback: removed jargon (leverage/synergy/posture), added concrete percentages to every claim, and sharpened the open-decisions section.",
    feedback: ["Replace jargon with plain English", "Add concrete numbers/percentages to every status claim", "Make the 'decision needed' items explicit with dates"],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Each claim now backed by a specific figure." },
      { dim: "Standards Alignment", score: "3", anchor: "RAG status consistent with the underlying tasks." },
      { dim: "Reasoning Quality", score: "3", anchor: "Conclusions follow from the data." },
      { dim: "Communication Quality", score: "4", anchor: "Plain, jargon-free, fits one page — clear improvement." },
      { dim: "Risk Awareness", score: "3", anchor: "Top risks surfaced; outlook reasonable." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Much clearer than round 1. One last thing: your 'Amber' overall status — if the CEO asks 'what one decision turns this Green?', can you answer in a sentence? Lead with that.", feedsNext: "Email the one-page report to management.",
  },

  // ── Reading / familiarisation reviews ─────────────────────────────────────────────────────
  // These open a task rather than close one: the mentee reviews source material and produces a
  // reading note. `feedback` is empty because there is no prior attempt to have addressed — the
  // gate is the cover note. The rubric is the mentor's demo grade on the note itself.
  "GRM-001/4.1": {
    title: "Risk Surface Note", standard: "ISO 27001 Cl 6.1.2 Risk assessment; A.5.9 Inventory",
    reviewer: "Cyber Risk Manager · Analytical Sleuth",
    artefact: "Risk surface note derived from the asset register", attempt: "1 of 3",
    coverExample: "Reviewed the asset register and grouped assets by what an attacker would want from them, not by asset type. Three concentrations stand out; two assets carry data whose loss is a regulatory event rather than an operational one.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Assets named individually; concentrations quantified." },
      { dim: "Standards Alignment", score: "3", anchor: "Risk surface framed per Cl 6.1.2; could cite the classification scheme." },
      { dim: "Reasoning Quality", score: "4", anchor: "Grouping by attacker value, not asset type — the right frame." },
      { dim: "Communication Quality", score: "3", anchor: "Readable; the concentration argument needs a lead sentence." },
      { dim: "Risk Awareness", score: "4", anchor: "Distinguishes regulatory loss from operational loss." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "You grouped by attacker value rather than asset type, which is the right instinct. Now push it: which single asset, if it went, takes two other functions with it? That dependency is the risk the register does not show you.",
    feedsNext: "Feeds Step 4.2 (risk identification workshop).",
  },
  "AA-002/2.1": {
    title: "IG1 Safeguard Familiarisation", standard: "CIS Controls v8 IG1",
    reviewer: "Compliance Manager · Compliance Sentinel",
    artefact: "IG1 Safeguard familiarisation note, scoped to the organisation", attempt: "1 of 3",
    coverExample: "Worked through all 56 IG1 Safeguards and marked which are plausibly in scope here. Four look inapplicable on first read; I have noted why rather than dropping them silently.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "3", anchor: "Safeguards cited by number; scoping notes brief in places." },
      { dim: "Standards Alignment", score: "4", anchor: "IG1 boundary understood; no IG2 safeguards pulled in." },
      { dim: "Reasoning Quality", score: "3", anchor: "Inapplicability reasoning stated but thin on two." },
      { dim: "Communication Quality", score: "4", anchor: "Clear, scannable, grouped by Control." },
      { dim: "Risk Awareness", score: "3", anchor: "Recognises that 'not applicable' is a claim needing evidence." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "SIGN-OFF",
    coaching: "You marked four Safeguards inapplicable. Before the assessment, test one of them properly: what would have to be true about this organisation for that Safeguard to genuinely not apply — and can you evidence it?",
    feedsNext: "Feeds Step 2.2 (evidence request) and 2.3 (assessment).",
  },
  "GRM-002/5.1": {
    title: "Policy Convention Analysis", standard: "ISO 27001 Cl 5.2 Policy; Cl 7.5.2",
    reviewer: "Policy & Governance Analyst · Bridge Builder",
    artefact: "Convention analysis of two existing policies", attempt: "1 of 3",
    coverExample: "Read two existing policies and extracted the house conventions: numbering, how obligations are phrased, where control references sit, and the review-block format. One inconsistency between them, which I have flagged rather than picking a side.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Conventions extracted with examples from both documents." },
      { dim: "Standards Alignment", score: "3", anchor: "Cl 7.5.2 elements identified; could map more explicitly." },
      { dim: "Reasoning Quality", score: "4", anchor: "Inconsistency surfaced rather than smoothed over." },
      { dim: "Communication Quality", score: "3", anchor: "Analysis clear; would benefit from a side-by-side." },
      { dim: "Risk Awareness", score: "3", anchor: "Notes that inconsistent phrasing weakens enforceability." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Good catch on the inconsistency. Here is the harder question: the two policies phrase obligations differently — 'must' in one, 'should' in the other. Which one would you follow if you were an employee, and what does that tell you about which convention to adopt?",
    feedsNext: "Feeds Step 5.2 (drafting) and Step 5.8 (Policy Register).",
  },
  "CRM-001/7.1": {
    title: "Regulatory Landscape Scan", standard: "ISO 27001 A.5.31 Legal and contractual requirements",
    reviewer: "Compliance Manager · Compliance Sentinel",
    artefact: "Regulatory landscape scan", attempt: "1 of 3",
    coverExample: "Scanned the jurisdictions and sector this organisation operates in. Identified the primary supervisory authority, the sector-specific instrument, and two obligations that arise from where customers are rather than where we are.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Regulators and instruments named, not categories." },
      { dim: "Standards Alignment", score: "4", anchor: "A.5.31 scope covered: statutory, regulatory and contractual." },
      { dim: "Reasoning Quality", score: "3", anchor: "Extraterritorial reasoning correct but briefly stated." },
      { dim: "Communication Quality", score: "3", anchor: "Scan readable; jurisdiction grouping would help." },
      { dim: "Risk Awareness", score: "4", anchor: "Spots that customer location creates obligations." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "You caught that obligations follow the customer, not just the office. Push once more: which of those obligations would still bind us if we closed the local entity tomorrow — and which would not?",
    feedsNext: "Feeds Step 7.3 (obligations long-list).",
  },
  "DD-003/2": {
    title: "Legal Retention Research", standard: "GDPR Art. 5(1)(e); local employment and tax law",
    reviewer: "Data Protection Officer · Compliance Sentinel",
    artefact: "Legal retention research", attempt: "1 of 3",
    coverExample: "Researched statutory minimum retention across employment, tax and sector rules for this jurisdiction. Two categories have a legal minimum longer than our current practice; one has no statutory period at all, which is a business decision rather than a legal one.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Periods cited with the instrument that sets them." },
      { dim: "Standards Alignment", score: "4", anchor: "Storage limitation applied correctly as a maximum, not a target." },
      { dim: "Reasoning Quality", score: "4", anchor: "Separates legal minimum from business preference." },
      { dim: "Communication Quality", score: "3", anchor: "Research clear; a summary table would carry it better." },
      { dim: "Risk Awareness", score: "3", anchor: "Notes over-retention risk; under-retention risk less developed." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "You separated the legal minimum from the business preference, which most people conflate. Now the trap: where a legal minimum and a data-minimisation duty point in opposite directions, which wins — and how would you word the schedule so nobody has to guess?",
    feedsNext: "Feeds Step 4 (retention schedule) and Step 5 (triggers).",
  },
  "GRM-003/6.1": {
    title: "NIST CSF Tier Calibration", standard: "NIST CSF 2.0 Implementation Tiers",
    reviewer: "GRC Program Manager · Operational Maestro",
    artefact: "NIST CSF 2.0 Tier familiarisation, calibrated to the organisation", attempt: "1 of 3",
    coverExample: "Worked through Tiers 1–4 and wrote what each would look like specifically in this department, so the assessment scores against observable behaviour rather than against the generic definitions.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Each Tier described in this department's own terms." },
      { dim: "Standards Alignment", score: "4", anchor: "Tier definitions used as written; no drift." },
      { dim: "Reasoning Quality", score: "3", anchor: "Calibration sound; Tier 3 vs 4 boundary still fuzzy." },
      { dim: "Communication Quality", score: "3", anchor: "Clear; examples uneven across Functions." },
      { dim: "Risk Awareness", score: "3", anchor: "Recognises Tier 4 is rarely appropriate at this scale." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Calibrating the Tiers before scoring is exactly right — it is what stops the assessment becoming an opinion poll. Your Tier 3/4 boundary is still soft: what would this department have to be doing that it demonstrably is not, for a 4 to be honest?",
    feedsNext: "Feeds Step 6.2 (questionnaire adaptation) and 6.5 (scoring).",
  },
  "DD-001/1": {
    title: "Existing Incident Material Review", standard: "ISO 27001 A.5.24 Incident management planning",
    reviewer: "Incident Response & Crisis Manager · Crisis Commander",
    artefact: "Review of existing incident-related material", attempt: "1 of 3",
    coverExample: "Reviewed helpdesk tickets, email chains and informal guidance. There is no documented procedure, but there is a de facto one: three tickets show the same escalation path being used from memory. That path is the starting point, not a blank page.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Ticket references cited; the de facto path reconstructed." },
      { dim: "Standards Alignment", score: "3", anchor: "A.5.24 elements identified; reporting duty less covered." },
      { dim: "Reasoning Quality", score: "4", anchor: "Recognises undocumented practice as evidence, not absence." },
      { dim: "Communication Quality", score: "3", anchor: "Findings clear; timeline would strengthen it." },
      { dim: "Risk Awareness", score: "4", anchor: "Notes that memory-based escalation fails when the person is away." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Treating undocumented practice as evidence rather than absence is the mature read — most people start from a blank page and write something nobody follows. Now: which part of that de facto path only works because one specific person knows it?",
    feedsNext: "Feeds Step 2 (procedure drafting) and Step 4 (quick reference card).",
  },
  "CRM-003/9.1": {
    title: "SOC 2 Type II Report — Annotated Reading", standard: "SOC 2 Type II (AICPA TSC)",
    reviewer: "Information Security Auditor · Guardian Watchdog",
    artefact: "Annotated reading of the SOC 2 Type II report", attempt: "1 of 3",
    coverExample: "Annotated the sample report: the opinion type, the exceptions raised, the scope boundary, and the carve-out treatment of sub-service organisations. The carve-out is the part most readers skip and it changes what the report actually covers.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Sections cited; exceptions quoted rather than summarised." },
      { dim: "Standards Alignment", score: "4", anchor: "Opinion, scope and carve-out read correctly." },
      { dim: "Reasoning Quality", score: "3", anchor: "Carve-out significance identified; implication under-developed." },
      { dim: "Communication Quality", score: "3", anchor: "Annotations useful; a one-line verdict up front would help." },
      { dim: "Risk Awareness", score: "4", anchor: "Sees that a clean opinion can still hide inherited risk." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "You spotted the carve-out, which most first readers miss entirely. Follow it through: if the sub-service organisation is carved out, whose controls are actually being relied on for that criterion — and who has tested them?",
    feedsNext: "Feeds Step 9.2 (Common Criteria listing) and 9.3 (mapping).",
  },
  "DD-002/1": {
    title: "Onboarding and Guidance Review", standard: "ISO 27001 A.6.3 Awareness, education and training",
    reviewer: "Training & Awareness Lead · Bridge Builder",
    artefact: "Review of onboarding materials and existing security guidance", attempt: "1 of 3",
    coverExample: "Reviewed HR onboarding and what security guidance exists. Security appears once, as a policy acknowledgement tick-box. Nothing teaches; it only records consent. That gap defines what the module has to do.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Materials named; the tick-box finding evidenced." },
      { dim: "Standards Alignment", score: "3", anchor: "A.6.3 read correctly as awareness, not acknowledgement." },
      { dim: "Reasoning Quality", score: "4", anchor: "Distinguishes recording consent from creating capability." },
      { dim: "Communication Quality", score: "3", anchor: "Clear; the implication could lead rather than close." },
      { dim: "Risk Awareness", score: "3", anchor: "Notes acknowledgement gives no assurance of behaviour." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "SIGN-OFF",
    coaching: "A tick-box that records consent but teaches nothing is the most common awareness failure there is, and you named it. So: what is the smallest thing the module could change about someone's Monday morning — and how would you know it had?",
    feedsNext: "Feeds Step 2 (learning objectives) and Step 3 (content outline).",
  },
  "IE-002/1": {
    title: "Document Estate Review", standard: "ISO 27001 Cl 7.5.3 Control of documented information",
    reviewer: "Policy & Governance Analyst · Operational Maestro",
    artefact: "Review of the current document estate", attempt: "1 of 3",
    coverExample: "Reviewed where GRC documents currently live. Three storage locations, two naming habits and at least one document existing in two versions with no way to tell which is current. Counted rather than estimated.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Locations and counts stated, not characterised." },
      { dim: "Standards Alignment", score: "3", anchor: "Cl 7.5.3 requirements identified; access control lighter." },
      { dim: "Reasoning Quality", score: "3", anchor: "Duplicate-version finding sound; root cause not yet named." },
      { dim: "Communication Quality", score: "4", anchor: "Concise and countable." },
      { dim: "Risk Awareness", score: "4", anchor: "Sees that an ambiguous current version is itself a control failure." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Counting rather than estimating is what makes this reviewable — well done. Now: if two versions exist and nobody can tell which is current, what has already gone wrong that you cannot see from the file system?",
    feedsNext: "Feeds Step 2 (Document Control Policy) and Step 3 (Document Register).",
  },
  "RR-001/1": {
    title: "Pre-Exercise Procedure Review", standard: "ISO 27001 A.5.24 Incident management planning",
    reviewer: "Incident Response & Crisis Manager · Crisis Commander",
    artefact: "Pre-exercise review of the procedure and scenario brief", attempt: "1 of 3",
    coverExample: "Read the procedure and the scenario brief before the exercise and wrote down what I expect to see happen, including two points where I think the procedure will not survive contact. Recorded in advance so my observation is not written with hindsight.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Predictions tied to named procedure clauses." },
      { dim: "Standards Alignment", score: "3", anchor: "A.5.24 elements traced; communication duty lighter." },
      { dim: "Reasoning Quality", score: "4", anchor: "Predicting before observing — the right discipline." },
      { dim: "Communication Quality", score: "3", anchor: "Clear; expectations could be stated as testable claims." },
      { dim: "Risk Awareness", score: "3", anchor: "Identifies likely failure points plausibly." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Writing predictions before the exercise is what separates an observer from a commentator — hindsight would have given you a tidier note and taught you nothing. During the debrief, be equally honest about the prediction you got wrong.",
    feedsNext: "Feeds Step 2 (attendance) and Step 3 (observation sheet).",
  },
  "MM-001/1": {
    title: "Candidate Indicator Identification", standard: "ISO 27001 Cl 9.1 Monitoring and measurement",
    reviewer: "GRC Program Manager · Operational Maestro",
    artefact: "Candidate indicator identification", attempt: "1 of 3",
    coverExample: "Identified candidate indicators from what this organisation already generates, rather than from a generic KPI list. Two candidates were rejected because nothing produces the data, which is a finding in itself.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Candidates tied to named systems that emit the data." },
      { dim: "Standards Alignment", score: "3", anchor: "Cl 9.1 'what to monitor' addressed; 'when' less so." },
      { dim: "Reasoning Quality", score: "4", anchor: "Rejecting unmeasurable candidates is the right discipline." },
      { dim: "Communication Quality", score: "3", anchor: "Clear list; rationale uneven between candidates." },
      { dim: "Risk Awareness", score: "3", anchor: "Notes that a metric nobody can produce becomes a fiction." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Starting from what the organisation already emits, rather than from a KPI catalogue, is why this will survive month two. One challenge: of the candidates you kept, which would still be collectable if the person who runs that report left next week?",
    feedsNext: "Feeds Step 2 (KPI definition cards).",
  },
  "KT-002/1": {
    title: "Rotation Deliverable Review", standard: "ISO 27001 Cl 10.2 Continual improvement",
    reviewer: "GRC Program Manager · Bridge Builder",
    artefact: "Review of all rotation deliverables", attempt: "1 of 3",
    coverExample: "Re-read every deliverable from the rotation in order. The change between the early and late artefacts is mostly in how much I now state explicitly that I used to leave implied. Two early deliverables I would now redo.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Named deliverables and concrete differences between them." },
      { dim: "Standards Alignment", score: "3", anchor: "Improvement framed per Cl 10.2; evidence lighter." },
      { dim: "Reasoning Quality", score: "4", anchor: "Identifies a pattern across artefacts, not a list of events." },
      { dim: "Communication Quality", score: "3", anchor: "Honest and readable; slightly long." },
      { dim: "Risk Awareness", score: "3", anchor: "Recognises the early artefacts are still in use downstream." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Naming two deliverables you would redo is the useful part — most retrospectives report growth without evidence. Since those two are still being consumed downstream, what is your obligation now: leave them, flag them, or fix them?",
    feedsNext: "Feeds Step 2 (lessons learned worksheet) and Step 5 (report).",
  },
  "BCRP-002/2": {
    title: "Backup Configuration Review", standard: "ISO 27001 A.8.13 Information backup; A.5.30",
    reviewer: "Business Continuity & Resilience Analyst · Guardian Watchdog",
    artefact: "Backup configuration review", attempt: "1 of 3",
    coverExample: "Reviewed backup configuration against what the checklist will need to assert. Backups run and are encrypted; no restore has been tested, and the retention window is shorter than the RPO the BIA assumes. Both recorded as findings, not smoothed over.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Schedule, retention and encryption stated as configured." },
      { dim: "Standards Alignment", score: "4", anchor: "A.8.13's 'tested regularly' applied, not just 'taken'." },
      { dim: "Reasoning Quality", score: "3", anchor: "RPO mismatch spotted; consequence stated briefly." },
      { dim: "Communication Quality", score: "3", anchor: "Findings clear; a config-versus-requirement table would help." },
      { dim: "Risk Awareness", score: "4", anchor: "Untested backup treated as an assumption, not a control." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "You caught that the retention window is shorter than the RPO the BIA assumes — that contradiction is the whole finding. Who currently believes the RPO is met, and what would it take to tell them otherwise?",
    feedsNext: "Feeds Step 3 (checklist drafting) and Step 5 (success criteria).",
  },
  "TPRM-002/4": {
    title: "Questionnaire Response Review", standard: "ISO 27001 A.5.19 Supplier relationships",
    reviewer: "Vendor Risk Analyst · Guardian Watchdog",
    artefact: "Review of responses for completeness and credibility", attempt: "1 of 3",
    coverExample: "Reviewed the vendor's returned questionnaire for completeness and, separately, for credibility. Three answers are complete but not credible — they claim a control the vendor's own public documentation contradicts. Flagged for follow-up rather than accepted.",
    feedback: [],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Contradictions cited against a named source." },
      { dim: "Standards Alignment", score: "3", anchor: "A.5.19 assessment duty applied; A.5.22 monitoring lighter." },
      { dim: "Reasoning Quality", score: "4", anchor: "Separates completeness from credibility — the key distinction." },
      { dim: "Communication Quality", score: "3", anchor: "Clear; follow-up questions could be drafted here." },
      { dim: "Risk Awareness", score: "4", anchor: "Does not treat a filled-in answer as an assured one." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Separating completeness from credibility is the whole skill in vendor assurance — a fully completed questionnaire is the easiest thing in the world to produce. For the three contradictions: what evidence would settle each one, and are you entitled to ask for it under the contract?",
    feedsNext: "Feeds Step 5 (risk rating) and Step 8 (assessment report).",
  },

  // ── Mentor quality gates ──────────────────────────────────────────────────────────────────
  // These close a task: a near-final artefact goes to the named reviewer. `feedback` carries the
  // prior round's comments, so the mentee confirms each was actioned before resubmitting — the
  // gate is that confirmation plus a cover note that says what changed.
  "AA-003/3.7": {
    title: "RoPA Entry and Screening Form", standard: "GDPR Art. 30; Art. 35 DPIA screening",
    reviewer: "Data Protection Officer · Compliance Sentinel",
    artefact: "RoPA entry v0.2 and Article 35 screening form", attempt: "2 of 3",
    coverExample: "Second submission. Lawful basis corrected from consent to contract for the account-provisioning purpose; transfer safeguard now named rather than implied; the screening threshold question answered rather than left blank.",
    feedback: [
      "Lawful basis says 'consent' for processing we could not stop doing if consent were withdrawn — re-examine.",
      "Transfers section names a country but not the safeguard relied on.",
      "Screening form: the large-scale question is unanswered, not 'no'.",
      "Retention period reads 'as required' — that is not a period.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Art. 30(1) fields populated with values, not placeholders." },
      { dim: "Standards Alignment", score: "4", anchor: "Lawful basis now defensible; transfer safeguard named." },
      { dim: "Reasoning Quality", score: "3", anchor: "Basis reasoning sound; the consent/contract argument could be shown." },
      { dim: "Communication Quality", score: "3", anchor: "Entry readable; controller and processor rows could be clearer." },
      { dim: "Risk Awareness", score: "4", anchor: "Gaps recorded as 'not defined' rather than left blank." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "The consent-to-contract correction was the important one — consent you cannot honour a withdrawal of was never consent. Before we file it: if a data subject withdrew today, what in this entry tells the service desk what to do?",
    feedsNext: "Feeds Step 3.8 (sign-off) and DD-003, LRC-001, TPRM-001.",
  },
  "GRM-002/5.5": {
    title: "Policy Draft — Consolidated Review Returns", standard: "ISO 27001 Cl 5.2 Policy",
    reviewer: "IT Manager, HR representative and Legal · Bridge Builder",
    artefact: "Information Security Policy v0.3 with consolidated review comments", attempt: "2 of 3",
    coverExample: "Circulated to IT, HR and Legal and consolidated the returns. Where IT and Legal disagreed on the exceptions clause I have set out both positions rather than choosing silently, because that decision belongs to the approver.",
    feedback: [
      "IT: the exceptions route has no time limit — an exception granted once lasts forever.",
      "HR: disciplinary consequence is implied but never stated; that makes it unenforceable.",
      "Legal: 'personal data' used where the policy means 'confidential information'.",
      "IT and Legal disagree on whether exceptions need CISO or Legal approval.",
    ],
    rubric: [
      { dim: "Specificity", score: "3", anchor: "Comments consolidated with attribution; two lack a proposed resolution." },
      { dim: "Standards Alignment", score: "4", anchor: "Cl 5.2 elements intact through revision." },
      { dim: "Reasoning Quality", score: "4", anchor: "Surfaces the IT/Legal disagreement instead of resolving it silently." },
      { dim: "Communication Quality", score: "3", anchor: "Comment sheet clear; the open decision needs to lead." },
      { dim: "Risk Awareness", score: "3", anchor: "Sees that an unlimited exception is a standing control bypass." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "REVISE",
    coaching: "Escalating the IT/Legal disagreement rather than picking a side was right — that is an approver's decision, not a drafter's. Now make it decidable: put the two options in front of them with the consequence of each, so the meeting takes two minutes rather than twenty.",
    feedsNext: "Feeds Step 5.6 (revision) and Step 5.7 (approval).",
  },
  "CRM-001/7.7": {
    title: "Obligations Register", standard: "ISO 27001 A.5.31 Legal and contractual requirements",
    reviewer: "Compliance Manager · Compliance Sentinel",
    artefact: "Obligations Register v1.0 with control mapping", attempt: "2 of 3",
    coverExample: "Second submission. Every obligation now carries an accountable role; the four contractual obligations that had no mapped control are shown as gaps rather than omitted; category definitions added so the four-way split is reproducible.",
    feedback: [
      "Several obligations have no named owner — 'Compliance' is not a role.",
      "Contractual obligations with no mapped control were dropped from the register entirely.",
      "The line between 'sector regulation' and 'legislation' is applied inconsistently.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Obligations cite the instrument and clause." },
      { dim: "Standards Alignment", score: "4", anchor: "All four A.5.31 categories represented and defined." },
      { dim: "Reasoning Quality", score: "3", anchor: "Categorisation now reproducible; two edge cases still arguable." },
      { dim: "Communication Quality", score: "3", anchor: "Register usable; gap rows could be visually distinct." },
      { dim: "Risk Awareness", score: "4", anchor: "Unmapped obligations kept visible as gaps." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Putting the unmapped obligations back in as gaps was the right call — dropping them made the register look complete and left the exposure invisible. Which of those four gaps would bite first, and is anyone currently accountable for it?",
    feedsNext: "Feeds Step 7.8 (register and review scheduling).",
  },
  "CRM-003/9.7": {
    title: "SOC 2 Control Awareness Summary", standard: "SOC 2 Type II (AICPA TSC)",
    reviewer: "Information Security Auditor · Guardian Watchdog",
    artefact: "SOC 2 Control Awareness Summary with RAG dashboard", attempt: "2 of 3",
    coverExample: "Second submission. Executive summary now leads with the readiness verdict; every criterion carries expected evidence; the ISO cross-reference disagreement on access removal is shown with the reading I follow and why.",
    feedback: [
      "The summary builds to the verdict instead of leading with it.",
      "Several criteria are marked partial without saying what the limitation is.",
      "Where ISO shows a control covered and SOC 2 shows a gap, the summary picks one without explaining.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Criteria carry test, evidence and control or an explicit GAP." },
      { dim: "Standards Alignment", score: "4", anchor: "TSC applied correctly; ISO cross-walk consistent." },
      { dim: "Reasoning Quality", score: "4", anchor: "Design gaps separated from operating gaps and sequenced on it." },
      { dim: "Communication Quality", score: "3", anchor: "Verdict now leads; the dashboard legend is still implicit." },
      { dim: "Risk Awareness", score: "4", anchor: "Recurring exceptions understood as costlier than point findings." },
    ],
    aggregate: "3.8", lowest: "3", outcome: "SIGN-OFF",
    coaching: "The design-versus-operating distinction is what makes this readable as a readiness position rather than a checklist. One thing to carry into the briefing: the IT team will hear 'not ready' as criticism. How do you say it so they hear a plan?",
    feedsNext: "Feeds Step 9.8 (IT team briefing) and PE-002.",
  },
  "SPA-001/7": {
    title: "12-Month GRC Roadmap", standard: "ISO 27001 Cl 6.2 Objectives and planning",
    reviewer: "Cybersecurity Program Manager · Operational Maestro",
    artefact: "12-Month GRC Improvement Roadmap with Gantt and briefing", attempt: "2 of 3",
    coverExample: "Second submission. Excluded systems now named with rationale; each action carries an hours estimate and a dated success metric; the sequencing argument for putting a low-scoring governance action first is stated rather than assumed.",
    feedback: [
      "Scope says nothing about what is excluded, so the boundary looks accidental.",
      "Actions carry owners but no effort estimate, which makes the resourcing ask unanswerable.",
      "The risk assessment is sequenced first but scores low — the reasoning is not on the page.",
      "Compliance uplift target is stated with no assumptions behind it.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Named systems and roles throughout; estimates in hours." },
      { dim: "Standards Alignment", score: "4", anchor: "Cl 6.2 shape complete: what, resources, who, when, evaluation." },
      { dim: "Reasoning Quality", score: "4", anchor: "Dependency-over-risk sequencing argued, not asserted." },
      { dim: "Communication Quality", score: "3", anchor: "Briefing holds one page; the Gantt legend needs work." },
      { dim: "Risk Awareness", score: "3", anchor: "Uplift assumptions stated; sensitivity to a slip not shown." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Sequencing the governance foundation ahead of higher-scoring exposures, and arguing for it, is the judgement this task is really testing. Now stress it: if the risk assessment slips by two months, which of your later actions become undeliverable rather than merely late?",
    feedsNext: "Feeds Step 8 (management endorsement).",
  },
  "SPA-002/7": {
    title: "Stakeholder Map and Communication Plan", standard: "ISO 27001 Cl 4.2; Cl 7.4 Communication",
    reviewer: "Policy & Governance Analyst · Bridge Builder",
    artefact: "Stakeholder Register, influence-interest grid and communication plan", attempt: "2 of 3",
    coverExample: "Second submission. Legal added after your challenge; placements now justified by evidence rather than assumption; the communication plan states an escalation route for stakeholders who do not respond.",
    feedback: [
      "Legal is missing entirely — they hold veto over half of this.",
      "Two stakeholders are placed high-influence with nothing to support it.",
      "The plan says what to send and how often, but not what happens when nobody replies.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Stakeholders named by role with evidenced placements." },
      { dim: "Standards Alignment", score: "3", anchor: "Cl 4.2 coverage good; Cl 7.4 'who communicates' implicit." },
      { dim: "Reasoning Quality", score: "4", anchor: "Placement reasoning testable rather than intuitive." },
      { dim: "Communication Quality", score: "4", anchor: "Grid and plan read together cleanly." },
      { dim: "Risk Awareness", score: "3", anchor: "Escalation route added; the silent-veto risk under-developed." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Adding Legal changed the shape of the map, which is exactly why the challenge was worth making. One more: your highest-influence stakeholder is also the least interested. What does your plan do when they neither block nor engage?",
    feedsNext: "Feeds Step 8 (sponsor sign-off) and SPA-001, CA-003.",
  },
  "PE-002/5": {
    title: "Audit Evidence Pack", standard: "ISO 27001 Cl 9.2 Internal audit; A.5.35",
    reviewer: "Information Security Auditor · Guardian Watchdog",
    artefact: "Audit Evidence Pack v0.2 with index", attempt: "2 of 3",
    coverExample: "Second submission. Every item now carries the period it covers; three items reused from prior tasks are cross-referenced rather than duplicated; two items are marked restricted and redacted before issue.",
    feedback: [
      "Evidence items have dates but not the period they cover — an auditor cannot tell what a screenshot proves.",
      "The same document is filed three times under different IDs.",
      "One item contains personal data that the auditor has no basis to receive.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Items labelled with control, date, version, source and period." },
      { dim: "Standards Alignment", score: "3", anchor: "Cl 9.2 evidence expectations met; sampling basis not stated." },
      { dim: "Reasoning Quality", score: "4", anchor: "Single-filing with cross-reference reasoned, not just tidied." },
      { dim: "Communication Quality", score: "4", anchor: "Index navigable; a reader can find any control's evidence." },
      { dim: "Risk Awareness", score: "4", anchor: "Treats the pack itself as a data-protection object." },
    ],
    aggregate: "3.8", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Spotting that the pack itself carries personal data is the finding most people miss entirely — assembling evidence is processing too. Before issue: who signs off the redaction, and where is that decision recorded?",
    feedsNext: "Feeds Step 6 (indexing) and Step 7 (self-review).",
  },
  "LRC-001/7": {
    title: "Privacy Notice Gap Assessment", standard: "GDPR Arts. 12–14 Transparency",
    reviewer: "Data Protection Officer · Compliance Sentinel",
    artefact: "Privacy notice gap assessment and redraft", attempt: "2 of 3",
    coverExample: "Second submission. Each gap now cites the Article it fails; the redraft uses the benchmark's structure without borrowing its wording; two processing activities described in the old notice that we no longer perform have been removed.",
    feedback: [
      "Gaps are described but not tied to the Article they breach.",
      "Some redrafted wording is lifted from the benchmark notice and describes processing we do not do.",
      "The notice still describes a data-sharing arrangement that ended last year.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Gaps cite Articles; redraft describes our actual processing." },
      { dim: "Standards Alignment", score: "4", anchor: "Arts. 12–14 elements traced individually." },
      { dim: "Reasoning Quality", score: "3", anchor: "Structural adoption reasoned; two choices unexplained." },
      { dim: "Communication Quality", score: "4", anchor: "Plain language appropriate to the audience." },
      { dim: "Risk Awareness", score: "3", anchor: "Sees that describing processing we do not do is itself a misstatement." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Copying a good notice is the fastest way to publish an inaccurate one, and you caught it. The ended data-sharing arrangement raises a separate question: how long was the notice wrong, and does anyone need to be told?",
    feedsNext: "Feeds Step 8 (approval and publication).",
  },
  "QA-001/8": {
    title: "Quality Review Closure Report", standard: "ISO 27001 Cl 7.5.2; Cl 10.1 Corrective action",
    reviewer: "Compliance Manager · Compliance Sentinel",
    artefact: "Quality Review Closure Report", attempt: "2 of 3",
    coverExample: "Second submission. Closure evidence attached per correction request; the two CRs the owner disputed are recorded with the reclassification and the reasoning; the recurring defect type is named as a process observation rather than logged six times.",
    feedback: [
      "Corrections are marked closed with no evidence of what changed.",
      "The disputed CRs are shown as closed, which hides that they were reclassified.",
      "The same defect appears in six documents and is reported six times, not once.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Each CR carries closure evidence and a date." },
      { dim: "Standards Alignment", score: "3", anchor: "Cl 10.1 corrective-action shape present; root cause light." },
      { dim: "Reasoning Quality", score: "4", anchor: "Recurring defect elevated to a process observation." },
      { dim: "Communication Quality", score: "3", anchor: "Report clear; the disputes deserve their own section." },
      { dim: "Risk Awareness", score: "3", anchor: "Notes the template is the cause, not the authors." },
    ],
    aggregate: "3.4", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Turning six identical findings into one observation about the template is the difference between a reviewer and an auditor. So: who owns the template, and have you told them — or does the report leave that to be discovered?",
    feedsNext: "Closes QA-001; feeds IE-002 and the document control cycle.",
  },
  "RR-001/7": {
    title: "Post-Exercise Report", standard: "ISO 27001 A.5.27 Learning from incidents",
    reviewer: "Incident Response & Crisis Manager · Crisis Commander",
    artefact: "Post-exercise lessons learned report and procedure amendments", attempt: "2 of 3",
    coverExample: "Second submission. Deviations now cite the clause breached; capability gaps separated from timing gaps; the prediction I got wrong is stated as plainly as the ones I got right.",
    feedback: [
      "Deviations are described but not tied to the procedure clause they departed from.",
      "'Too slow' and 'could not' are mixed together — they need different fixes.",
      "The report reads as though every prediction you made beforehand was correct.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Timestamped decisions against clause expectations." },
      { dim: "Standards Alignment", score: "3", anchor: "A.5.27 learning cycle covered; A.5.24 planning link lighter." },
      { dim: "Reasoning Quality", score: "4", anchor: "Capability and timing gaps separated and treated differently." },
      { dim: "Communication Quality", score: "4", anchor: "Timeline readable by someone who was not there." },
      { dim: "Risk Awareness", score: "3", anchor: "Amendments routed to owners; re-test scheduled." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Recording the prediction you got wrong costs nothing now and is worth more than the ones you got right — it is the only part of the report that tells us where the procedure surprised an informed reader. Which amendment would have prevented that surprise?",
    feedsNext: "Feeds Step 8 (filing and amendments) and DD-001.",
  },
  "KT-001/5": {
    title: "Onboarding Pack Review", standard: "ISO 27001 A.6.3 Awareness, education and training",
    reviewer: "HR Manager and GRC Program Manager · Bridge Builder",
    artefact: "New joiner checklist, Day-1 briefing and reference guide", attempt: "2 of 3",
    coverExample: "Second submission. Blocking and non-blocking checklist items are now distinguished; the Day-1 slides carry speaker notes so a non-specialist manager can deliver them; each rule states why it exists.",
    feedback: [
      "The checklist does not say which items block system access and which do not.",
      "The Day-1 slides assume the presenter knows security — most line managers do not.",
      "Rules are stated without reasons, so a new joiner learns compliance rather than judgement.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Day 1 / 7 / 30 actions assigned to joiner or manager." },
      { dim: "Standards Alignment", score: "3", anchor: "A.6.3 awareness intent met; A.5.18 access link implicit." },
      { dim: "Reasoning Quality", score: "4", anchor: "Every rule carries its reason." },
      { dim: "Communication Quality", score: "4", anchor: "Deliverable cold by a non-specialist manager." },
      { dim: "Risk Awareness", score: "3", anchor: "Blocking items identified; the day-one access window not addressed." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Writing for a manager who is not a security specialist is what will make this actually get delivered. One gap left: between the joiner starting and the Day-1 briefing happening, what access do they already have?",
    feedsNext: "Feeds Step 6 (pilot) and Step 8 (handover to HR).",
  },
  "CA-003/7": {
    title: "Stakeholder Interview Findings", standard: "ISO 27001 Cl 4.2 Interested parties",
    reviewer: "GRC Program Manager · Bridge Builder",
    artefact: "Stakeholder interview findings and insight routing", attempt: "2 of 3",
    coverExample: "Second submission. Findings are now attributed where the stakeholder agreed and anonymised where they did not; each insight is routed to a register or roadmap change rather than left as narrative; the commitment I made in one interview is shown as kept.",
    feedback: [
      "Findings are reported as a narrative with nothing changing as a result.",
      "One stakeholder's criticism is attributed by name — check that was agreed.",
      "You promised to raise something in one interview; the report does not show that you did.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Insights quoted and tied to a named change." },
      { dim: "Standards Alignment", score: "3", anchor: "Cl 4.2 needs captured; expectations less structured." },
      { dim: "Reasoning Quality", score: "4", anchor: "Converts interview material into register and roadmap change." },
      { dim: "Communication Quality", score: "3", anchor: "Clear; attribution rules could be stated up front." },
      { dim: "Risk Awareness", score: "4", anchor: "Handles attribution as a trust obligation, not a formatting choice." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Keeping the commitment you made in the room is what determines whether anyone tells you anything useful next time. On attribution: what is your default when a stakeholder says nothing either way — named or anonymous, and why?",
    feedsNext: "Feeds Step 8 (routing into SPA-002 and SPA-001).",
  },
  "TPRM-001/8": {
    title: "Supplier Register Issue", standard: "ISO 27001 A.5.19; A.5.20 Supplier agreements",
    reviewer: "Vendor Risk Analyst · Guardian Watchdog",
    artefact: "Supplier Register v1.0 and high-risk summary", attempt: "2 of 3",
    coverExample: "Second submission. Vendors with no internal owner are flagged rather than assigned to Procurement by default; risk ratings state what drives them; 'not required' DPA determinations carry a reason.",
    feedback: [
      "Ownerless vendors were quietly assigned to Procurement — that is an assumption, not a fact.",
      "Risk ratings are given with no visible driver, so nobody can challenge one.",
      "Several DPAs are marked 'not required' with no reasoning.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Vendors carry service, data access, systems and contact." },
      { dim: "Standards Alignment", score: "4", anchor: "A.5.19/5.20 coverage complete; DPA position stated per vendor." },
      { dim: "Reasoning Quality", score: "3", anchor: "Rating drivers now visible; two remain unexplained." },
      { dim: "Communication Quality", score: "3", anchor: "Register usable; the high-risk summary could lead with the count." },
      { dim: "Risk Awareness", score: "4", anchor: "Ownerless vendors flagged rather than assumed away." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Refusing to assign ownerless vendors by default is the right instinct — a fabricated owner is worse than a visible gap because nobody goes looking for it. Of those, which has the deepest data access, and who should own it?",
    feedsNext: "Feeds TPRM-002 (due diligence) and CRM-003, SPA-001.",
  },
  "QA-002/6": {
    title: "Control Testing Methodology", standard: "ISO 27001 Cl 9.2 Internal audit; A.5.35",
    reviewer: "Information Security Auditor · Guardian Watchdog",
    artefact: "Control Testing Methodology and three worked test sheets", attempt: "2 of 3",
    coverExample: "Second submission. Each test states its approach and why a weaker one would miss the failure mode; sampling is defined with a basis; pass/fail criteria are written so two testers would reach the same verdict.",
    feedback: [
      "Two of the three tests rely on inquiry alone, which cannot prove operation.",
      "Sample sizes are given with no basis — why five and not fifty?",
      "Pass/fail criteria are subjective; two testers would disagree.",
    ],
    rubric: [
      { dim: "Specificity", score: "4", anchor: "Test steps executable by someone who did not write them." },
      { dim: "Standards Alignment", score: "4", anchor: "Cl 9.2 approaches applied appropriately per control." },
      { dim: "Reasoning Quality", score: "4", anchor: "Approach choice argued against what a weaker one misses." },
      { dim: "Communication Quality", score: "3", anchor: "Methodology clear; the overview is slightly over a page." },
      { dim: "Risk Awareness", score: "3", anchor: "Recognises inquiry-only testing gives false assurance." },
    ],
    aggregate: "3.6", lowest: "3", outcome: "SIGN-OFF",
    coaching: "Moving off inquiry-only was the change that makes this a methodology rather than a questionnaire. The reproducibility test is the one that matters now: hand a sheet to someone else, have them run it, and see whether they reach your verdict.",
    feedsNext: "Feeds Step 7 (final revision and QA library entry).",
  },
};

export function getReviewTask(taskCode?: string, activityCode?: string): ReviewTask | undefined {
  if (!taskCode || !activityCode) return undefined;
  return REVIEW_TASKS[`${taskCode}/${activityCode}`];
}
