// Per-task catalogue (GRC101_Tasks_Activities.docx) — fixed reference for the Working Desk tree + task overview.
export interface TaskMeta { name: string; methodCategory: string; standardId: string; standardLabel: string; standardTone: string; description: string; deliverable: string; badge: string; mentorRole: string; persona: string; duration: string; nistCrossRef: string; }

export const TASK_META: Record<string, TaskMeta> = {
  "AA-001": {
    "name": "Information Asset Inventory & Classification",
    "methodCategory": "Assessment and Analysis",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee identifies, documents, and classifies all information assets within one assigned business unit of a LOW-criticality organisation. This task builds the foundational habit of understanding what data exists, where it lives, and how sensitive it is — a prerequisite for all subsequent GRC work.",
    "deliverable": "Information Asset Register — a signed-off spreadsheet listing all identified assets with classification, owner, location, and residual gaps.",
    "badge": "Process Mapping Specialist",
    "mentorRole": "Policy & Governance Analyst",
    "persona": "Analytical Sleuth",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — ID.AM-01 (Inventories of hardware maintained); ID.AM-02 (Inventories of software maintained); ID.AM-05 (Assets are prioritised)"
  },
  "AA-002": {
    "name": "Security Controls Gap Analysis — CIS Controls v8 IG1",
    "methodCategory": "Assessment and Analysis",
    "standardId": "cisv8",
    "standardLabel": "CIS Controls v8",
    "standardTone": "emerald",
    "description": "The mentee performs a structured gap analysis of the organisation's current security controls against the 56 IG1 Safeguards of CIS Controls v8. The output gives management a clear picture of where basic cyber-hygiene is missing before moving to more complex frameworks.",
    "deliverable": "CIS Controls v8 IG1 Gap Analysis Report — scored assessment per Control group, gap list with remediation priorities, and an executive summary.",
    "badge": "Control Framework Understanding",
    "mentorRole": "Compliance Manager",
    "persona": "Compliance Sentinel",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — ID.AM, PR.AA, PR.DS (Protect: Identity Management; Data Security)"
  },
  "AA-003": {
    "name": "Privacy Data-Flow Mapping & GDPR Applicability Assessment",
    "methodCategory": "Assessment and Analysis",
    "standardId": "gdpr",
    "standardLabel": "GDPR",
    "standardTone": "rose",
    "description": "The mentee maps personal data flows across one operational process (e.g., student enrolment or user-account registration), determines the lawful basis for processing, and completes a RoPA entry and DPIA screening form — the two most fundamental GDPR compliance artefacts at an intern level.",
    "deliverable": "Completed RoPA Entry (for one process) + DPIA Screening Form with disposition (full DPIA required / not required) and supporting data-flow diagram.",
    "badge": "Compliance Readiness",
    "mentorRole": "Policy & Governance Analyst",
    "persona": "Compliance Sentinel",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.OC-05 (Legal, regulatory and contractual requirements are understood); ID.AM-08 (Systems/services involving external parties are inventoried)"
  },
  "GRM-001": {
    "name": "Operational Risk Identification & Basic Risk Register",
    "methodCategory": "Governance and Risk Management",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee conducts a structured risk identification exercise across two business units, populates a basic risk register with likelihood and impact scores, and presents findings to the unit manager. This is the cornerstone task for any GRC intern — understanding how to think about risk systematically.",
    "deliverable": "Basic Risk Register — spreadsheet with all identified risks scored on a 5×5 matrix, ISO 27001 control domain mapping, risk treatment options, and a one-page management summary.",
    "badge": "Risk Assessment Specialist",
    "mentorRole": "Cyber Risk Manager",
    "persona": "Analytical Sleuth",
    "duration": "3 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.RM-01 (Risk management objectives established); ID.RA-01 (Vulnerabilities identified); ID.RA-04 (Potential impacts and likelihoods determined)"
  },
  "GRM-002": {
    "name": "Information Security Policy Drafting",
    "methodCategory": "Governance and Risk Management",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee drafts one foundational information security policy (Acceptable Use Policy or Remote Working Policy) from scratch using an approved template, goes through a structured review cycle, and publishes the final version through the organisation's document control process.",
    "deliverable": "Approved Information Security Policy (AUP or Remote Working Policy) — final version with ISO 27001 control references, management signature, and Policy Register entry.",
    "badge": "Documentation Excellence",
    "mentorRole": "Policy & Governance Analyst",
    "persona": "Collaborative Coach",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.PO-01 (Policy for managing cybersecurity risks established); GV.PO-02 (Policy reviewed, updated, and communicated)"
  },
  "GRM-003": {
    "name": "GRC Maturity Assessment — Departmental Level",
    "methodCategory": "Governance and Risk Management",
    "standardId": "nistcsf",
    "standardLabel": "NIST CSF 2.0",
    "standardTone": "violet",
    "description": "The mentee conducts a lightweight GRC maturity assessment for one department using the NIST CSF 2.0 Tier model, produces a current-state maturity profile, and identifies the top priority improvement areas — providing management with a structured starting point for their GRC journey.",
    "deliverable": "GRC Maturity Assessment Report — CSF Tier scoring per Function, spider diagram (current vs. target state), top-three gap narrative, and a prioritised improvement roadmap.",
    "badge": "Foundation GRC Discovery",
    "mentorRole": "Compliance Manager",
    "persona": "Metrics Maven",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — All six Functions (Govern, Identify, Protect, Detect, Respond, Recover) assessed at Tier level; ISO 27001:2022 — Clause 9.1 (Monitoring, measurement, analysis and evaluation)"
  },
  "CRM-001": {
    "name": "Regulatory Requirements Inventory & Obligations Register",
    "methodCategory": "Compliance and Regulatory Management",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee builds a Regulatory Obligations Register by identifying all applicable legal, regulatory, and contractual information-security requirements for the organisation — the foundational compliance-management artefact that all subsequent GRC work references.",
    "deliverable": "Regulatory Obligations Register — a signed-off spreadsheet listing all applicable requirements with control mapping, compliance status, owner, and gap flags.",
    "badge": "Compliance Readiness",
    "mentorRole": "Compliance Manager",
    "persona": "Compliance Sentinel",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.OC-03 (Legal, regulatory, and contractual requirements understood and managed); GV.OC-05 (Outcomes, capabilities, and services that the organisation depends on are understood)"
  },
  "CRM-002": {
    "name": "ISO 27001 Control Framework Mapping to Business Processes",
    "methodCategory": "Compliance and Regulatory Management",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee maps ISO 27001:2022 Annex A controls to five critical business processes of the organisation, building a control matrix that shows which controls apply to which process — a core skill for any intern supporting compliance assessments.",
    "deliverable": "ISO 27001 Control Matrix (Process-to-Control Mapping) — a spreadsheet mapping 5 business processes × 93 Annex A controls with applicability, implementation status, control owner, and gap summary.",
    "badge": "Control Framework Understanding",
    "mentorRole": "Compliance Manager",
    "persona": "Analytical Sleuth",
    "duration": "3 weeks",
    "nistCrossRef": "NIST CSF 2.0 — All Functions (cross-walk between ISO 27001 Annex A and NIST CSF Categories/Subcategories)"
  },
  "CRM-003": {
    "name": "SOC 2 Awareness — Trust Services Criteria Mapping",
    "methodCategory": "Compliance and Regulatory Management",
    "standardId": "soc2",
    "standardLabel": "SOC 2",
    "standardTone": "amber",
    "description": "The mentee reviews the organisation's SOC 2 report (or a sample Type II report), maps the Common Criteria control points to existing internal controls, and produces a SOC 2 Control Awareness Summary — building foundational audit-literacy for a GRC intern.",
    "deliverable": "SOC 2 Control Awareness Summary — traffic-light dashboard per Common Criteria cluster, control-gap list, and a two-page IT-team briefing document.",
    "badge": "Control Framework Understanding",
    "mentorRole": "Information Security Auditor",
    "persona": "Guardian Watchdog",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.PO, PR.AA, PR.DS (Policy; Identity Management; Data Security) cross-walked to TSC Common Criteria"
  },
  "DD-001": {
    "name": "Procedure Development — Incident Reporting Procedure",
    "methodCategory": "Design and Development",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee designs and writes an Incident Reporting Procedure that tells all staff how to recognise and report a suspected security incident — the first-response artefact that enables every other incident-management activity to function.",
    "deliverable": "Incident Reporting Procedure (full document) + Incident Reporting Quick Reference Card (one-page PDF-ready) + Staff Communication Draft.",
    "badge": "Documentation Excellence",
    "mentorRole": "Policy & Governance Analyst",
    "persona": "Collaborative Coach",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — RS.CO-02 (Incidents reported); RS.MA-01 (Incident response activities aligned with plans); DE.AE-06 (Information on adverse events communicated)"
  },
  "DD-002": {
    "name": "Security Awareness Training Content Development",
    "methodCategory": "Design and Development",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee designs a 30-minute onboarding security awareness module covering three core topics (phishing recognition, password hygiene, and data handling) and a five-question knowledge check — a foundational deliverable for any GRC intern in a people-facing environment.",
    "deliverable": "Security Awareness Training Module — 10–12 slide deck, five-question knowledge check, one-page Facilitator Guide, and a training attendance register template.",
    "badge": "Documentation Excellence",
    "mentorRole": "Security Awareness & Training Specialist",
    "persona": "Innovation Catalyst",
    "duration": "3 weeks",
    "nistCrossRef": "NIST CSF 2.0 — PR.AT-01 (Personnel are provided awareness and training); PR.AT-02 (Individuals with elevated privileges are provided awareness and training); CIS Controls v8 — Control 14 (Security Awareness and Skills Training)"
  },
  "DD-003": {
    "name": "Data Retention Schedule Development",
    "methodCategory": "Design and Development",
    "standardId": "gdpr",
    "standardLabel": "GDPR",
    "standardTone": "rose",
    "description": "The mentee develops a Data Retention Schedule for one category of personal data (e.g., employee records or client contact records), specifying how long each data element must be kept, the legal basis for retention, and the disposal method — a direct GDPR storage-limitation compliance artefact.",
    "deliverable": "Data Retention Schedule (for one data category) — approved spreadsheet with retention triggers, periods, legal basis, disposal method, and responsible owner; plus a Data Disposal Instruction document.",
    "badge": "Documentation Excellence",
    "mentorRole": "Policy & Governance Analyst",
    "persona": "Compliance Sentinel",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — PR.DS-01 (Data at rest protected); PR.DS-10 (Data in use protected); CIS Controls v8 — Control 3.11 (Encrypt Sensitive Data at Rest) complementary to retention lifecycle"
  },
  "SPA-001": {
    "name": "GRC Programme Roadmap — 12-Month Plan for One Organisation",
    "methodCategory": "Strategic Planning and Architecture",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee develops a draft 12-month GRC improvement roadmap for one LOW-criticality organisation based on the gap analysis findings from earlier tasks — translating compliance gaps into an actionable, phased plan that management can adopt.",
    "deliverable": "12-Month GRC Improvement Roadmap — phased action plan (Gantt chart), per-action detail spreadsheet, and a one-page Management Briefing.",
    "badge": "Foundation Discovery",
    "mentorRole": "Cybersecurity Program Manager",
    "persona": "Operational Maestro",
    "duration": "3 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.RM-06 (Risk tolerance determined and communicated); GV.OC (Organisational Context understood and used to prioritise cybersecurity risk)"
  },
  "SPA-002": {
    "name": "Stakeholder Mapping for a GRC Initiative",
    "methodCategory": "Strategic Planning and Architecture",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee maps all stakeholders for a specific GRC compliance initiative (e.g., ISO 27001 gap closure or privacy programme launch), producing a Stakeholder Register and Influence-Interest Matrix — core project-governance artefacts for any GRC intern supporting a compliance project.",
    "deliverable": "Stakeholder Register + Influence-Interest Matrix + Stakeholder Communication Plan for the selected GRC initiative.",
    "badge": "Foundation Discovery",
    "mentorRole": "Policy & Governance Analyst",
    "persona": "Bridge Builder",
    "duration": "1 week",
    "nistCrossRef": "NIST CSF 2.0 — GV.OC-02 (Internal and external stakeholders identified); GV.SC-04 (Suppliers and third parties are informed of their roles)"
  },
  "IE-001": {
    "name": "CIS Controls IG1 Remediation — Basic Implementation Tracking",
    "methodCategory": "Implementation and Execution",
    "standardId": "cisv8",
    "standardLabel": "CIS Controls v8",
    "standardTone": "emerald",
    "description": "Following the gap analysis (AA-002), the mentee coordinates the implementation of five specific CIS IG1 Safeguards, tracking evidence of completion for each — providing hands-on experience of turning a compliance gap into an implemented control.",
    "deliverable": "Control Implementation Tracker (updated with evidence references) + Evidence Repository (filed artefacts) + Implementation Progress Report.",
    "badge": "Control Framework Understanding",
    "mentorRole": "Compliance Manager",
    "persona": "Operational Maestro",
    "duration": "3 weeks",
    "nistCrossRef": "NIST CSF 2.0 — PR.AA-01 (Identities managed); PR.DS-01 (Data at rest protected); PR.DS-02 (Data in transit protected)"
  },
  "IE-002": {
    "name": "Policy Roll-Out — Version Control and Document Control Setup",
    "methodCategory": "Implementation and Execution",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee establishes a version-controlled document management system for GRC policies and procedures — setting up folder structures, naming conventions, version numbering, and document lifecycle rules so that the organisation's GRC documentation is consistently managed going forward.",
    "deliverable": "Document Control Policy (approved) + Document Register (populated) + Implemented folder structure on the shared drive + Training summary note.",
    "badge": "Documentation Excellence",
    "mentorRole": "Policy & Governance Analyst",
    "persona": "Operational Maestro",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.PO-02 (Policy reviewed, updated, communicated); GV.OC (Organisational context maintained through documented information)"
  },
  "TV-001": {
    "name": "Access Control Review — User Account Validation",
    "methodCategory": "Testing and Validation",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee performs a structured user-access review for one system or application — validating that active accounts belong to current employees, that access rights match job roles, and that no dormant or orphaned accounts exist. This is the most common first-level audit test for any GRC intern.",
    "deliverable": "Access Control Testing Report — findings table (account status, issue type, recommendation), executive summary with remediation priority, and a signed remediation acknowledgement from the IT Manager.",
    "badge": "Audit Preparation Support",
    "mentorRole": "Information Security Auditor",
    "persona": "Guardian Watchdog",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — PR.AA-01 (Identities and credentials managed); PR.AA-02 (Identities are proofed and bound to credentials); CIS Controls v8 — Control 5 (Account Management), Control 6 (Access Control Management)"
  },
  "TV-002": {
    "name": "Policy Compliance Spot-Check — Desk-Based Control Testing",
    "methodCategory": "Testing and Validation",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee conducts a desk-based compliance spot-check against three policies (e.g., Acceptable Use Policy, Remote Working Policy, Clean Desk Policy), using evidence-sampling to determine whether staff are following the policies in practice.",
    "deliverable": "Policy Compliance Spot-Check Report — control testing workpapers (one per policy), compliance rate summary, findings table, and remediation recommendations.",
    "badge": "Audit Preparation Support",
    "mentorRole": "Information Security Auditor",
    "persona": "Analytical Sleuth",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.PO-02 (Policy reviewed and communicated); PR.AT-01 (Personnel provided awareness and training); DE.CM (Monitoring performed)"
  },
  "MM-001": {
    "name": "GRC KPI Definition and Basic Metrics Tracking Setup",
    "methodCategory": "Monitoring and Management",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee defines a set of five GRC KPIs for one organisation, builds a monthly tracking spreadsheet, and produces the first monthly GRC Metrics Report — establishing the measurement habit that underpins all continuous improvement in a GRC programme.",
    "deliverable": "GRC KPI Definition Pack (five KPI Definition Cards) + Monthly GRC Metrics Tracking Spreadsheet + Month 1 GRC Metrics Report (one-page).",
    "badge": "Foundation GRC Discovery",
    "mentorRole": "Compliance Manager",
    "persona": "Metrics Maven",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.RM-06 (Risk management outcomes communicated); DE.CM-09 (Computing hardware and software monitored); PR.PS-04 (Logs of events created)"
  },
  "MM-002": {
    "name": "Risk Register Maintenance — Monthly Review Cycle",
    "methodCategory": "Monitoring and Management",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee facilitates the first monthly risk-register review meeting, updates risk scores based on new information, records treatment progress, and produces an updated register — learning the discipline of treating risk management as a live process rather than a one-time exercise.",
    "deliverable": "Updated Risk Register (version 2) + Monthly Risk Summary (one-page: portfolio overview, score movements, new risks, overdue treatments) + Meeting Minutes.",
    "badge": "Risk Assessment Specialist",
    "mentorRole": "Cyber Risk Manager",
    "persona": "Metrics Maven",
    "duration": "1 week (recurring monthly)",
    "nistCrossRef": "NIST CSF 2.0 — ID.RA-06 (Risks identified); GV.RM-07 (Risk responses managed); DE.CM (Adverse events monitored)"
  },
  "CA-001": {
    "name": "Security Awareness Briefing — Staff Presentation Delivery",
    "methodCategory": "Communication and Advisory",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee delivers the security awareness module developed in DD-002 to a live audience of 10–20 staff, facilitates the knowledge check, collects training completion records, and reports results — gaining experience in communicating GRC concepts to a non-technical audience.",
    "deliverable": "Training Completion Report — attendance list, knowledge-check score summary, pass rate, qualitative observations, and recommendations for any staff requiring remedial guidance.",
    "badge": "Foundation GRC Discovery",
    "mentorRole": "Security Awareness & Training Specialist",
    "persona": "Collaborative Coach",
    "duration": "1 week (includes scheduling and delivery)",
    "nistCrossRef": "NIST CSF 2.0 — PR.AT-01 (Personnel provided awareness and training); CIS Controls v8 — Control 14.2 (Training for all roles with security responsibilities) and 14.7 (Training for all users on identifying social engineering)"
  },
  "CA-002": {
    "name": "Management Compliance Status Report",
    "methodCategory": "Communication and Advisory",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee compiles and writes a one-page executive compliance status report for the organisation's management team, synthesising findings from all completed tasks into a format that non-GRC managers can act on — building the critical skill of translating technical findings into business language.",
    "deliverable": "Executive Compliance Status Report (one-page, management-ready) covering: RAG status, top risks, achievements, open decisions, and 30-day outlook.",
    "badge": "Foundation GRC Discovery",
    "mentorRole": "Compliance Manager",
    "persona": "Bridge Builder",
    "duration": "1 week",
    "nistCrossRef": "NIST CSF 2.0 — GV.RM-06 (Risk management outcomes communicated); GV.OC-04 (Responsibilities are understood); ID.RA-09 (Third-party risk assessed — referenced in reporting)"
  },
  "CA-003": {
    "name": "Stakeholder Interview — GRC Needs Discovery",
    "methodCategory": "Communication and Advisory",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee conducts structured interviews with three internal stakeholders (IT Manager, HR Manager, and a business-unit lead) to discover their GRC-related concerns, knowledge gaps, and expectations — building empathy, communication skills, and a stakeholder-informed view of GRC needs.",
    "deliverable": "Stakeholder Needs Discovery Report — cross-interview theme analysis, key quotes, stakeholder-specific recommendations, and implications for GRC programme design.",
    "badge": "Foundation GRC Discovery",
    "mentorRole": "Policy & Governance Analyst",
    "persona": "Bridge Builder",
    "duration": "1 week",
    "nistCrossRef": "NIST CSF 2.0 — GV.OC-02 (Internal and external stakeholders identified); GV.OC-03 (Legal, regulatory and contractual requirements understood)"
  },
  "RR-001": {
    "name": "Tabletop Incident Simulation — Observer and Note-Taker Role",
    "methodCategory": "Response and Recovery",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee participates in a facilitated tabletop incident simulation as an observer and note-taker, documenting all decisions, escalations, and gaps identified during the exercise — providing foundational exposure to incident response without being placed in a decision-making role prematurely.",
    "deliverable": "Post-Exercise Lessons Learned Report — timeline of the exercise, structured observations, top-three improvement recommendations with proposed procedure amendments.",
    "badge": "Audit Preparation Support",
    "mentorRole": "Incident Response & Crisis Manager",
    "persona": "Crisis Commander",
    "duration": "1 week (including exercise day and write-up)",
    "nistCrossRef": "NIST CSF 2.0 — RS.MA-01 (Incident response activities aligned with plan); RS.CO-02 (Incidents reported); RC.RP-01 (Recovery plan executed); CIS Controls v8 — Control 17 (Incident Response Management)"
  },
  "BCRP-001": {
    "name": "Business Impact Analysis (BIA) — Single Department",
    "methodCategory": "Business Continuity and Resilience Planning",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee conducts a Business Impact Analysis for one department, identifying its critical functions, dependencies, and the maximum tolerable downtime — a foundational resilience artefact and the starting point for any business continuity plan.",
    "deliverable": "BIA Report (for one department) — critical functions list, impact scores, RTO/RPO table, single points of failure analysis, and recommended continuity measures.",
    "badge": "Risk Assessment Specialist",
    "mentorRole": "Business Continuity & Resilience Analyst",
    "persona": "Operational Maestro",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — RC.RP-01 (Recovery plan executed); RC.RP-03 (Recovery activities and progress communicated); CIS Controls v8 — Control 11 (Data Recovery)"
  },
  "BCRP-002": {
    "name": "ICT Disaster Recovery Checklist Development",
    "methodCategory": "Business Continuity and Resilience Planning",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee develops an ICT Disaster Recovery Checklist for one system or service, covering backup verification, failover steps, and restoration testing — a basic but essential operational artefact that ensures recovery procedures actually work.",
    "deliverable": "ICT DR Checklist (for one system) — step-by-step pre-incident, incident, restoration, and return-to-normal sections, with RTO/RPO success criteria and sign-off blocks.",
    "badge": "Control Framework Understanding",
    "mentorRole": "Business Continuity & Resilience Analyst",
    "persona": "Guardian Watchdog",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — RC.RP-02 (Recovery plan updated); PR.DS-11 (Data backups created); CIS Controls v8 — Control 11.1 (Establish and maintain a data recovery process) and 11.4 (Establish and maintain an isolated instance of recovery data)"
  },
  "TPRM-001": {
    "name": "Supplier / Vendor Inventory and Basic Security Risk Rating",
    "methodCategory": "Third-Party Risk Management",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee creates a Supplier Register by inventorying all third-party vendors that access, process, or store organisational information, then applies a basic five-criterion risk rating to each — producing the organisation's first formal third-party risk inventory.",
    "deliverable": "Supplier Register — full vendor inventory with risk ratings, data-access type, contract status, and DPA gap flags; plus a High-Risk Vendor Summary.",
    "badge": "Risk Assessment Specialist",
    "mentorRole": "Vendor / Third-Party Risk Analyst",
    "persona": "Analytical Sleuth",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.SC-04 (Suppliers and third parties informed of their roles); GV.SC-06 (Planning and due diligence performed); CIS Controls v8 — Control 15 (Service Provider Management)"
  },
  "TPRM-002": {
    "name": "Vendor Due-Diligence Questionnaire — Completion and Review",
    "methodCategory": "Third-Party Risk Management",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee sends a security due-diligence questionnaire to one Medium-risk vendor (identified in TPRM-001), reviews the response, identifies gaps, and prepares a Due-Diligence Assessment Report — gaining experience with the most common vendor risk workflow.",
    "deliverable": "Vendor Due-Diligence Assessment Report — completed questionnaire (with assessment annotations), Due-Diligence Score, gap list, risk rating confirmation, and recommended mitigations.",
    "badge": "Risk Assessment Specialist",
    "mentorRole": "Vendor / Third-Party Risk Analyst",
    "persona": "Guardian Watchdog",
    "duration": "3 weeks (including vendor response wait)",
    "nistCrossRef": "NIST CSF 2.0 — GV.SC-06 (Planning and due diligence performed); GV.SC-07 (Risks posed by suppliers assessed); CIS Controls v8 — Control 15.2 (Establish and maintain a process to address weaknesses in third-party service provider security)"
  },
  "LRC-001": {
    "name": "Privacy Notice Review and Gap Assessment",
    "methodCategory": "Legal and Regulatory Coordination",
    "standardId": "gdpr",
    "standardLabel": "GDPR",
    "standardTone": "rose",
    "description": "The mentee reviews the organisation's public-facing privacy notice against the mandatory content requirements of GDPR Articles 13 and 14, identifies gaps, and drafts a revised privacy notice for Legal/DPO review — building foundational legal-coordination skills without requiring legal expertise.",
    "deliverable": "Privacy Notice Gap-Check Report (checklist with gap findings) + Revised Privacy Notice Draft (ready for DPO/Legal sign-off).",
    "badge": "Compliance Readiness",
    "mentorRole": "Policy & Governance Analyst",
    "persona": "Compliance Sentinel",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.OC-05 (Legal, regulatory and contractual requirements understood); PR.DS-01 (Data at rest protected — contextual); CIS Controls v8 — Control 3.14 (Log sensitive data access — contextual)"
  },
  "PE-001": {
    "name": "GRC Project Charter — Compliance Initiative Kick-Off",
    "methodCategory": "Project Execution",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee develops a Project Charter for a real GRC compliance initiative (e.g., the gap-closure programme from AA-002), gaining hands-on experience with project-initiation discipline — a critical skill for GRC interns supporting programme delivery.",
    "deliverable": "Signed Project Charter + Milestone Gantt (high-level) + Kick-Off Meeting Minutes.",
    "badge": "Foundation Discovery",
    "mentorRole": "Cybersecurity Program Manager",
    "persona": "Operational Maestro",
    "duration": "1 week",
    "nistCrossRef": "NIST CSF 2.0 — GV.OC (Organisational Context); GV.RM-01 (Risk management objectives established)"
  },
  "PE-002": {
    "name": "Audit Evidence Preparation and Filing",
    "methodCategory": "Project Execution",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee prepares and organises an audit evidence pack for a specific ISO 27001 clause (e.g., Clause 9.1 or Annex A 5.1) as if preparing for an external certification audit — learning systematic evidence organisation, labelling, and quality-checking.",
    "deliverable": "Audit Evidence Pack — labelled evidence files, Evidence Index (spreadsheet), and a completed self-review Audit Evidence Checklist.",
    "badge": "Audit Preparation Support",
    "mentorRole": "Information Security Auditor",
    "persona": "Analytical Sleuth",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — GV.PO-02 (Policy reviewed, updated, communicated and enforced); ID.RA-01 (Vulnerabilities in assets identified); DE.CM-09 (Computing hardware and software monitored)"
  },
  "QA-001": {
    "name": "GRC Document Quality Review",
    "methodCategory": "Quality Assurance",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee performs a structured quality review of three GRC documents (policies or procedures) against a defined quality standard, identifying deficiencies and raising formal Correction Requests — learning the critical discipline of applying consistent quality standards to GRC documentation.",
    "deliverable": "Quality Review Report (deficiency list with severities and correction requests) + Correction Tracking Log + Quality Review Closure Report.",
    "badge": "Documentation Excellence",
    "mentorRole": "Compliance Manager",
    "persona": "Guardian Watchdog",
    "duration": "1 week",
    "nistCrossRef": "NIST CSF 2.0 — GV.PO-02 (Policy reviewed, updated, communicated); GV.OC (Organisational context maintained)"
  },
  "QA-002": {
    "name": "Control Testing Methodology Development",
    "methodCategory": "Quality Assurance",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee documents a repeatable control testing methodology for three controls (selected from the Control Matrix, CRM-002), specifying the exact test procedure, evidence requirements, and pass/fail criteria — ensuring that future spot-checks (TV-002) are consistent and defensible.",
    "deliverable": "Three Control Testing Methodology Sheets + Testing Methodology Overview (one page) filed in the GRC QA Library.",
    "badge": "Audit Preparation Support",
    "mentorRole": "Information Security Auditor",
    "persona": "Analytical Sleuth",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — DE.CM-09 (Computing hardware and software monitored); GV.PO-02 (Policy reviewed and enforced); CIS Controls v8 — Control 18 (Penetration Testing — awareness only at GRC 101 level)"
  },
  "KT-001": {
    "name": "GRC Onboarding Pack — New Joiner Reference Guide",
    "methodCategory": "Knowledge Transfer",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "The mentee develops a GRC Onboarding Pack for new staff joiners — a curated set of documents that tells a new employee everything they need to know about the organisation's security and privacy obligations in their first week — creating a reusable knowledge asset for the organisation.",
    "deliverable": "GRC Onboarding Pack — New Joiner GRC Reference Guide (4 pages), New Joiner GRC Checklist (Day 1/7/30), and Day-1 Security Briefing Slide Deck (5 slides); all handed over to HR.",
    "badge": "Documentation Excellence",
    "mentorRole": "Security Awareness & Training Specialist",
    "persona": "Collaborative Coach",
    "duration": "2 weeks",
    "nistCrossRef": "NIST CSF 2.0 — PR.AT-01 (Personnel provided awareness and training); GV.PO-02 (Policy communicated); CIS Controls v8 — Control 14.1 (Establish and maintain a security awareness programme)"
  },
  "KT-002": {
    "name": "Lessons Learned Documentation — End-of-Rotation Retrospective",
    "methodCategory": "Knowledge Transfer",
    "standardId": "iso27001",
    "standardLabel": "ISO/IEC 27001:2022",
    "standardTone": "indigo",
    "description": "At the end of the GRC 101 rotation, the mentee documents a structured retrospective of the full programme — capturing what they learned, what worked, what didn't, and what they would recommend to the next GRC 101 cohort — institutionalising continuous improvement in the mentorship programme itself.",
    "deliverable": "Lessons Learned Report (2–3 pages) + Mentee Portfolio Index (complete list of all GRC 101 deliverables produced) + Three Programme Improvement Recommendations.",
    "badge": "Foundation GRC Discovery",
    "mentorRole": "Policy & Governance Analyst",
    "persona": "Collaborative Coach",
    "duration": "1 week",
    "nistCrossRef": "NIST CSF 2.0 — GV.RM-07 (Risk responses managed and outcomes communicated); RC.IM-01 (Recovery plan incorporates lessons learned); CIS Controls v8 — Control 17.8 (Conduct post-incident reviews)"
  }
};

export const METHOD_CATEGORY_ORDER: string[] = ["Assessment and Analysis", "Governance and Risk Management", "Compliance and Regulatory Management", "Design and Development", "Strategic Planning and Architecture", "Implementation and Execution", "Testing and Validation", "Monitoring and Management", "Communication and Advisory", "Response and Recovery", "Business Continuity and Resilience Planning", "Third-Party Risk Management", "Legal and Regulatory Coordination", "Project Execution", "Quality Assurance", "Knowledge Transfer"];
