// Canonical 22-verb method — fixed product reference data (mirrors the original design).
// The backend owns which verb an activity uses (step.verb id); the frontend owns how a verb renders.

export interface VerbMeta {
  id: string; code: string; num: number; label: string;
  color: string; icon: string; when: string; layer1: string[]; layer2: string[];
}

export const VERBS: Record<string, VerbMeta> = {
  "request": {"id": "request", "code": "RQ", "num": 1, "label": "Request", "color": "indigo", "icon": "send", "when": "Mentee needs information from a stakeholder.", "layer1": ["To-field is a named role", "≥ 3 requested items", "Deadline present", "Subject ≤ 80 chars"], "layer2": ["Specificity", "Communication Quality"]},
  "conduct": {"id": "conduct", "code": "CD", "num": 2, "label": "Conduct", "color": "violet", "icon": "chat", "when": "Mentee runs a structured walkthrough or guided interaction.", "layer1": ["≥ 90 % of guide questions answered", "Named stakeholder recorded", "No blank fields without rationale"], "layer2": ["Specificity", "Reasoning Quality", "Communication Quality"]},
  "record": {"id": "record", "code": "RC", "num": 3, "label": "Record", "color": "emerald", "icon": "table", "when": "Mentee enters data into an authoritative register or template.", "layer1": ["Mandatory fields populated", "Schema conformance", "CIA consistency", "Owner is a role, not a department"], "layer2": ["Specificity", "Standards Alignment", "Reasoning Quality"]},
  "apply": {"id": "apply", "code": "AP", "num": 4, "label": "Apply", "color": "amber", "icon": "treeDown", "when": "Mentee applies a defined classification or decision scheme.", "layer1": ["Personal-data items not classified Public", "Distribution within expected range", "Every item has a rationale"], "layer2": ["Standards Alignment", "Reasoning Quality"]},
  "crossref": {"id": "crossref", "code": "XR", "num": 5, "label": "Cross-reference", "color": "rose", "icon": "layers", "when": "Mentee compares two data sources to identify discrepancies.", "layer1": ["≥ 1 discrepancy class identified", "Method field populated", "Checklist used"], "layer2": ["Reasoning Quality", "Specificity"]},
  "identify": {"id": "identify", "code": "ID", "num": 6, "label": "Identify", "color": "indigo", "icon": "flag", "when": "Mentee scans a register or dataset to find items meeting a criterion.", "layer1": ["Every flag has a proposed action", "Every flag has a named accountable role"], "layer2": ["Specificity", "Risk Awareness"]},
  "review": {"id": "review", "code": "RV", "num": 7, "label": "Review", "color": "violet", "icon": "eye", "when": "Mentee submits a near-final artefact for mentor quality check.", "layer1": ["Cover note present", "Prior feedback addressed", "Revisions ≤ 3"], "layer2": ["All five rubric dimensions"]},
  "present": {"id": "present", "code": "PR", "num": 8, "label": "Present", "color": "amber", "icon": "upload", "when": "Mentee communicates findings to a senior stakeholder for sign-off.", "layer1": ["Deck uploaded", "≥ 3 anticipated questions answered", "Sign-off decision with date"], "layer2": ["Communication Quality", "Risk Awareness", "Reasoning Quality"]},
  "draft": {"id": "draft", "code": "DR", "num": 9, "label": "Draft", "color": "emerald", "icon": "edit", "when": "Mentee writes a policy, procedure, plan, or recommendation.", "layer1": ["All required sections present and non-empty", "Standards cited correctly", "No unexplained jargon"], "layer2": ["Specificity", "Standards Alignment", "Communication Quality"]},
  "map": {"id": "map", "code": "MP", "num": 10, "label": "Map", "color": "indigo", "icon": "grid", "when": "Mentee links items across two domains.", "layer1": ["Every populated link has a rationale", "Unmatched items have explanations", "No orphan rows or columns"], "layer2": ["Standards Alignment", "Reasoning Quality"]},
  "calculate": {"id": "calculate", "code": "CL", "num": 11, "label": "Calculate", "color": "amber", "icon": "chart", "when": "Mentee derives a numerical metric from underlying data.", "layer1": ["Formula identifier cited", "All source-data fields named", "Result re-computes to ± 0"], "layer2": ["Specificity", "Reasoning Quality"]},
  "prioritise": {"id": "prioritise", "code": "PZ", "num": 12, "label": "Prioritise", "color": "rose", "icon": "sortDesc", "when": "Mentee ranks items by a defined criterion.", "layer1": ["Ranking is criterion-based", "No unresolved ties", "Aggregate arithmetic correct"], "layer2": ["Reasoning Quality", "Risk Awareness"]},
  "recommend": {"id": "recommend", "code": "RM", "num": 13, "label": "Recommend", "color": "emerald", "icon": "rocket", "when": "Mentee proposes a remediation or improvement action.", "layer1": ["Action-specific", "References a control", "Named owner role", "Target date"], "layer2": ["Specificity", "Standards Alignment", "Risk Awareness"]},
  "validate": {"id": "validate", "code": "VL", "num": 14, "label": "Validate", "color": "violet", "icon": "shield", "when": "Mentee verifies findings against a standard or independent source.", "layer1": ["Each finding has ≥ 1 citation", "Unverified items have follow-up", "No indeterminate findings"], "layer2": ["Standards Alignment", "Reasoning Quality"]},
  "schedule": {"id": "schedule", "code": "SC", "num": 15, "label": "Schedule", "color": "indigo", "icon": "calendar", "when": "Mentee arranges a future interaction with a stakeholder.", "layer1": ["Purpose stated", "Agenda attached", "≥ 1 time agreed", "Confirmation captured"], "layer2": ["Communication Quality"]},
  "assess": {"id": "assess", "code": "AS", "num": 16, "label": "Assess", "color": "amber", "icon": "bullseye", "when": "Mentee judges maturity, risk, or compliance against a defined scale.", "layer1": ["Every item has cited evidence", "Scale applied consistently", "Outliers explained"], "layer2": ["Standards Alignment", "Reasoning Quality", "Risk Awareness"]},
  "score": {"id": "score", "code": "SR", "num": 17, "label": "Score", "color": "rose", "icon": "sliders", "when": "Mentee assigns a quantitative score from a defined rubric.", "layer1": ["Aggregate matches weighted total", "All dimension justifications ≥ 15 chars"], "layer2": ["Reasoning Quality", "Specificity"]},
  "compile": {"id": "compile", "code": "CP", "num": 18, "label": "Compile", "color": "emerald", "icon": "cube", "when": "Mentee assembles a final deliverable from prior artefacts.", "layer1": ["All required sections present", "Executive summary non-empty", "Zero numeric conflicts"], "layer2": ["Communication Quality", "Specificity"]},
  "brief": {"id": "brief", "code": "BR", "num": 19, "label": "Brief", "color": "indigo", "icon": "info", "when": "Mentee delivers a short plain-language update to a non-technical audience.", "layer1": ["Audience field populated", "Explicit ask present", "Slide count ≤ 5 / page count = 1"], "layer2": ["Communication Quality", "Specificity"]},
  "signoff": {"id": "signoff", "code": "SO", "num": 20, "label": "Sign-off", "color": "amber", "icon": "handshake", "when": "Mentee obtains formal approval from a senior stakeholder.", "layer1": ["Decision recorded with date", "Conditions captured if applicable", "Revision plan if rejected"], "layer2": ["Reasoning Quality", "Communication Quality"]},
  "interview": {"id": "interview", "code": "IV", "num": 21, "label": "Interview", "color": "violet", "icon": "user", "when": "Mentee runs an unstructured or semi-structured stakeholder interview.", "layer1": ["≥ 5 open questions prepared", "Notes structured per question", "Quotes attributed"], "layer2": ["Specificity", "Reasoning Quality"]},
  "document": {"id": "document", "code": "DC", "num": 22, "label": "Document", "color": "emerald", "icon": "file", "when": "Mentee writes up a process, decision, or lessons-learned record.", "layer1": ["All sections complete", "Cross-references valid", "No broken links"], "layer2": ["Communication Quality", "Specificity"]},
};

export const VERB_LIST: VerbMeta[] = Object.values(VERBS).sort((a, b) => a.num - b.num);
