"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { Icon } from "@/components/ui/icon";
import { Card, Bar, Ring } from "@/components/ui/primitives";
import { DVerb } from "@/components/ui/dverb";
import { Drawer } from "@/components/ui/drawer";
import { DraggablePanel } from "@/components/ui/draggable-panel";
import { RefBody } from "@/components/app/reference-material";
import { Gloss } from "@/components/app/glossary";
import { StepBrief, WorkingSheet } from "@/components/app/deliverable";
import { VERBS, GATE_VERBS, isGateVerb } from "@/lib/verbs";
import { DocOpenStrip, FloatingDocs, useFloatingDocs } from "@/components/app/doc-windows";
import { deskApi, takeWarmStep, type ActivityDetail, type ActivityPayload, type SubmitResponse, type Review, type SubmissionDetail, type Layer1Result } from "@/lib/desk";
import { JudgmentCall, JudgmentAnswer, JudgmentVerdict, decisionReady } from "@/components/app/judgment-call";
import type { DecisionAnswer } from "@/lib/desk";
import { ApiError } from "@/lib/api";
import { VerbWorkspace } from "@/components/app/workspaces";
import { CONTROL_KEYS, isFilled } from "@/lib/checklist";
import { acceptanceStates, acceptanceTexts } from "@/lib/acceptance";
import { criteriaAt } from "@/lib/criterion-map";
import { CriterionProvider } from "@/components/app/criterion-mark";
import { useDeskBase, useDeskLearnings } from "@/components/app/desk-context";
import { dueChip, fmtDue } from "@/lib/schedule";
import { useTaskBundle, activityBrief } from "@/lib/task-bundle";
import { WORKSPACE_REFS } from "@/lib/workspace-refs";
import { GuidedTour, type TourStep } from "@/components/app/guided-tour";
import { fieldGuide } from "@/lib/guide-fields";
import { MentorDecision } from "@/components/app/mentor-decision";
import { LockedNotice } from "@/components/app/locked-notice";
import { StepBar } from "@/components/app/step-bar";
import { fitsWorkspace } from "@/lib/workspace-readback";
import { MachineNote, MachineTag } from "@/components/app/machine-note";
import { ModelAnswer } from "@/components/app/model-answer";
import { invalidateQuery } from "@/lib/use-query";
import { gateSummary, type GateEntry } from "@/lib/gate-summary";
import type { RuaTask } from "@/lib/rua-tasks";
import type { TaskReference } from "@/lib/taskmeta";

function ReviewPanel({ review }: { review: Review }) {
  const pass = review.decision === "pass";
  return (
    // Dotted violet outline: this is the model's grade, not a mentor's decision. The mentor's
    // sealed verdict renders below it with a solid band, and the difference is the point.
    <MachineNote className="space-y-4" label={`Generated by ${review.model} · not a mentor decision`}>
      <div className="flex items-center gap-4">
        <Ring pct={(review.overallScore / 5) * 100} size={72} stroke={8}>
          <span className="text-[15px] font-semibold text-slate-900">{review.overallScore.toFixed(1)}</span>
        </Ring>
        <div>
          <div className="flex items-center gap-2">
            <span className={`inline-flex items-center gap-1.5 px-2.5 h-6 rounded-full text-[11px] font-medium ring-1 ${pass ? "bg-emerald-50 text-emerald-700 ring-emerald-100" : "bg-amber-50 text-amber-700 ring-amber-100"}`}>
              <Icon name={pass ? "check" : "refresh"} size={12} /> {pass ? "Passed" : "Needs revision"}
            </span>
            <span className="text-[11px] text-slate-400">overall / 5</span>
          </div>
          {/* The model's name moved into the provenance tag at the top of the note — one place,
              not two, and it now reads as attribution rather than a footnote. */}
        </div>
      </div>

      <div className="space-y-3">
        {review.dimensions.map((d) => (
          <div key={d.id}>
            <div className="flex items-center justify-between mb-1">
              <span className="text-[12.5px] font-medium text-slate-700 tracking-tight">{d.label}</span>
              <span className="text-[11.5px] font-semibold text-slate-900 tabular-nums">{d.score.toFixed(1)}</span>
            </div>
            <Bar pct={(d.score / 5) * 100} tone={d.score >= 4.3 ? "emerald" : d.score >= 4 ? "indigo" : "amber"} />
            <p className="text-[11.5px] text-slate-500 mt-1 leading-relaxed tracking-tight" style={{ textWrap: "pretty" }}>{d.justification}</p>
            {/* The grader is required to name one concrete thing that would have scored higher.
                Showing it is what makes a revision aimed: without it the learner reads Socratic
                prose and guesses which change was meant. */}
            {d.missing ? (
              <p className="text-[11.5px] text-amber-800 bg-amber-50/60 ring-1 ring-amber-100 rounded-lg px-2.5 py-1.5 mt-1.5 leading-relaxed tracking-tight" style={{ textWrap: "pretty" }}>
                <span className="font-semibold">To score higher: </span>{d.missing}
              </p>
            ) : null}
          </div>
        ))}
      </div>

      {/* No tint and no ring of its own — it already sits inside the dotted note, and a second
          violet panel nested in the first just read as two objects. */}
      <div className="border-t border-violet-100 pt-3">
        <div className="flex items-center gap-1.5 mb-1.5 text-[11px] font-semibold tracking-[0.1em] uppercase text-violet-600">
          <Icon name="chat" size={12} /> Feedback
        </div>
        <p className="text-[12.5px] text-slate-700 leading-relaxed tracking-tight" style={{ textWrap: "pretty" }}>{review.feedback}</p>
      </div>
    </MachineNote>
  );
}

/** Attempts-left meter — depleting pips (lives metaphor) + count. Brand indigo with full attempts,
 *  amber on the last one, rose when exhausted. Pure-presentational; renders nothing without a cap. */
function AttemptsMeter({ used, max }: { used: number; max: number }) {
  if (!max || max <= 0) return null;
  const left = Math.max(0, max - used);
  const tone = left === 0 ? "rose" : left === 1 ? "amber" : "indigo";
  const text = { indigo: "text-slate-600", amber: "text-amber-700", rose: "text-rose-600" }[tone];
  const pip = { indigo: "bg-indigo-500", amber: "bg-amber-400", rose: "bg-rose-400" }[tone];
  const ring = { indigo: "ring-slate-200 bg-slate-50", amber: "ring-amber-200/70 bg-amber-50/60", rose: "ring-rose-200/70 bg-rose-50/60" }[tone];
  return (
    <span className={`inline-flex items-center gap-2 h-8 pl-2.5 pr-3 rounded-full ring-1 ${ring}`} title={`${left} of ${max} submission attempts remaining`}>
      <span className="flex items-center gap-1" aria-hidden>
        {Array.from({ length: max }).map((_, i) => (
          <span key={i} className={`w-4 h-1.5 rounded-full transition-colors ${i < left ? pip : "bg-slate-200"}`} />
        ))}
      </span>
      <span className={`text-[11.5px] font-medium tracking-tight tabular-nums ${text}`}>
        {left === 0 ? "No attempts left" : `${left} of ${max} attempts left`}
      </span>
    </span>
  );
}

/** Reference documents as an inline accordion (used inside the Resources drawer — no nested drawers). */
// Remounted (via `key`) when the focused ref changes, so `openId` initialises to the focused doc.
function RefAccordion({ references, focusId }: { references: TaskReference[]; focusId?: string | null }) {
  const [openId, setOpenId] = useState<string | null>(focusId ?? references[0]?.id ?? null);
  return (
    <div className="space-y-2">
      {references.map((r) => {
        const isOpen = openId === r.id;
        return (
          <div key={r.id} className="rounded-xl ring-1 ring-slate-200 overflow-hidden bg-white">
            <button
              onClick={() => setOpenId(isOpen ? null : r.id)}
              className="w-full flex items-center gap-3 text-left px-3.5 py-3 hover:bg-slate-50 transition-colors"
            >
              <span className="w-8 h-8 rounded-lg bg-indigo-50 ring-1 ring-indigo-100 text-indigo-600 flex items-center justify-center shrink-0"><Icon name="book" size={15} /></span>
              <span className="min-w-0 flex-1">
                <span className="flex items-center gap-2 flex-wrap">
                  <span className="text-[13px] font-medium text-slate-900 tracking-tight">{r.title}</span>
                  <span className="text-[9.5px] font-semibold tracking-[0.08em] uppercase text-slate-500 bg-slate-100 rounded px-1.5 py-0.5">{r.kind}</span>
                </span>
                <span className="block text-[12px] text-slate-500 tracking-tight mt-0.5" style={{ textWrap: "pretty" }}>{r.summary}</span>
              </span>
              <Icon name="chevronDown" size={15} className={`text-slate-400 shrink-0 transition-transform ${isOpen ? "rotate-180" : ""}`} />
            </button>
            {isOpen && <div className="px-3.5 pb-3.5 pt-1 border-t border-slate-100"><RefBody text={r.body} kind={r.kind} /></div>}
          </div>
        );
      })}
    </div>
  );
}

/** Field key → human label ("objectiveMet" → "Objective met", "formula_cite" → "Formula cite"). */
function humanKey(k: string): string {
  const s = k.replace(/[_-]+/g, " ").replace(/([a-z0-9])([A-Z])/g, "$1 $2").trim().toLowerCase();
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/** Render any lifted workspace value as plain text. Workspaces lift arbitrary JSON (strings,
 *  lists, row arrays, id-keyed maps), so this walks it generically rather than per-verb. */
function fieldText(v: unknown, depth = 0): string {
  if (v === null || v === undefined) return "";
  if (typeof v === "boolean") return v ? "Yes" : "No";
  const pad = "  ".repeat(depth);
  if (Array.isArray(v)) {
    return v.map((x) => { const t = fieldText(x, depth + 1).trimStart(); return t ? `${pad}• ${t}` : ""; }).filter(Boolean).join("\n");
  }
  if (typeof v === "object") {
    return Object.entries(v as Record<string, unknown>)
      .map(([k, val]) => { const t = fieldText(val, depth + 1); return t ? `${pad}${humanKey(k)}: ${t.includes("\n") ? `\n${t}` : t.trimStart()}` : ""; })
      .filter(Boolean).join("\n");
  }
  return String(v);
}

/** What the mentee actually sent for one submission — every graded field, any verb.
 *  The two task-boundary gates lift positional progress arrays that the generic walker renders as
 *  unlabelled bullets, so they get a purpose-built read-back (lib/gate-summary.ts) instead. */
function SubmittedFields({ payload, verbId, taskCode, rua }: {
  payload?: ActivityPayload; verbId: string; taskCode: string; rua?: RuaTask;
}) {
  const entries = gateSummary(verbId, payload?.fields ?? {}, taskCode, rua)
    ?? Object.entries(payload?.fields ?? {})
      .filter(([k]) => !CONTROL_KEYS.has(k))
      .map(([k, v]) => [humanKey(k), fieldText(v)] as GateEntry)
      .filter(([, t]) => t.trim() !== "");
  if (entries.length === 0) return null;
  return (
    <dl className="space-y-2.5">
      {entries.map(([k, text]) => (
        <div key={k}>
          <dt className="text-[10px] font-semibold tracking-[0.1em] uppercase text-slate-400">{k}</dt>
          <dd className="text-[12px] text-slate-700 leading-relaxed tracking-tight whitespace-pre-line mt-0.5">{text}</dd>
        </div>
      ))}
      {payload?.notes?.trim() && (
        <div>
          <dt className="text-[10px] font-semibold tracking-[0.1em] uppercase text-slate-400">Notes</dt>
          <dd className="text-[12px] text-slate-700 leading-relaxed tracking-tight whitespace-pre-line mt-0.5">{payload.notes}</dd>
        </div>
      )}
    </dl>
  );
}

/** What the checklist shows, row by row. One function for the strip and for the R-marks on the
 *  working sheet, so a mark can never report a different state from the row it points at. */
function checklistStates(verbId: string, values: Record<string, unknown>, layer1?: Layer1Result | null) {
  // The criteria and their met-tests come from the same place — lib/acceptance.ts — so a criterion
  // on screen is one this step's workspace can actually evidence.
  const criteria = acceptanceTexts(verbId);
  // Once graded, defer to the backend's deterministic result (when it lines up 1:1 with the criteria).
  const graded = !!layer1 && layer1.checks.length === criteria.length;
  const live = acceptanceStates(verbId, values);
  const states = criteria.map((c, i) => (graded ? layer1!.checks[i].passed : live[i]));
  return { criteria, graded, states };
}

/** Live acceptance-criteria checklist (always expanded). Heuristic before submit; authoritative after.
 *  Pass `onClose` to show a dismiss (✕) button (used by the floating HUD). `paired` names the rows
 *  (1-based) whose part of the deliverable has focus. */
function AcceptanceChecklist({ verbId, values, layer1, onClose, paired = [] }: {
  verbId: string;
  values: Record<string, unknown>;
  layer1?: Layer1Result | null;
  onClose?: () => void;
  paired?: number[];
}) {
  const { criteria, graded, states } = checklistStates(verbId, values, layer1);
  const met = states.filter(Boolean).length;
  const allMet = met === criteria.length;

  return (
    // The rule strip (form 04): your output is measured against this. The double rule top and
    // bottom is the whole signal — "measured against" — and it is why this carries no fill, no
    // tick circles and no progress bar: a criterion is met or it is open, and the word says which.
    // Steel rules rather than navy because these criteria are the programme's, not a standard's.
    // The panel keeps a blurred white ground only because it floats over the form as a HUD.
    <div className="bg-white/95 backdrop-blur-xl backdrop-saturate-150 border-x border-x-slate-200 border-y-4 border-y-sky-700 [border-top-style:double] [border-bottom-style:double] px-4 py-3 shadow-[0_16px_44px_-14px_rgba(15,23,42,0.28)]">
      {/* The one-line summary the form language puts with a rule strip, carrying the state the
          progress bar used to carry. Sits on top so the close button has a row to live in. */}
      <div className="mb-1 flex items-center gap-2">
        <div className="font-mono text-[10px] uppercase tracking-[0.06em] text-slate-500">
          {criteria.length} criteria · {met} met
          {allMet && <span className="text-emerald-600"> · all hold</span>}
          <span className="text-slate-400"> · {graded ? "from your last submission" : "live"}</span>
        </div>
        {onClose && (
          <button
            onClick={onClose}
            aria-label="Hide checklist"
            className="focus-ring ml-auto -mr-1 shrink-0 w-6 h-6 rounded-md flex items-center justify-center text-slate-400 hover:text-slate-700 hover:bg-slate-900/5 transition-colors cursor-pointer"
          >
            <Icon name="x" size={13} />
          </button>
        )}
      </div>

      <ol className="list-none p-0 m-0">
        {criteria.map((c, i) => {
          const ok = states[i];
          // Only a graded run can say "not met" — before submission an unticked row is merely
          // open, and colouring it as a failure would be a lie about work in progress.
          const failed = graded && !ok;
          // The row whose part of the deliverable has focus: counter and text lift and a steel rule
          // marks the margin. No fill — the strip carries its meaning in its rules, not a ground.
          const on = paired.includes(i + 1);
          return (
            <li
              key={i}
              className={`grid grid-cols-[26px_1fr_52px] gap-2 items-baseline py-[7px] -mx-2 px-2 border-b border-dashed border-slate-200 last:border-b-0 transition-shadow motion-reduce:transition-none ${on ? "shadow-[inset_2px_0_0_#0369a1]" : ""}`}
            >
              <span className={`font-mono text-[10.5px] tabular-nums ${on ? "text-sky-700 font-semibold" : "text-slate-400"}`}>R{i + 1}</span>
              <span className={`text-[13px] leading-snug tracking-tight ${on ? "text-slate-900" : "text-slate-700"}`}>
                <Gloss>{c}</Gloss>
              </span>
              <i
                className={`not-italic font-mono text-[10px] text-right ${
                  ok ? "text-emerald-600" : failed ? "text-amber-600" : "text-slate-400"
                }`}
              >
                {ok ? "met" : failed ? "not met" : "open"}
              </i>
            </li>
          );
        })}
      </ol>
    </div>
  );
}

/** Flags a workspace lifts *about* the attempt rather than as part of it. A payload holding only
 *  these carries no answers to read back. */
const CONTROL_FLAGS = new Set(["objectiveMet", "hintsUsed", "scripted", "slips", "slipRows"]);
const hasAnswers = (p?: ActivityPayload | null) =>
  Object.keys(p?.fields ?? {}).some((k) => !CONTROL_FLAGS.has(k));

/** The submission a completed step reads back: highest scored, newest on a tie (history is
 *  newest-first, and `>` keeps the one seen first). Scores re-roll between attempts, so the last
 *  attempt is not necessarily the best one.
 *
 *  Submissions carrying no answers are skipped rather than won with. A payload of nothing but
 *  control flags renders as an untouched workspace — on a gate, a tab rail reading 0/8 with every
 *  step after the first locked — under a banner claiming it is the work that was graded. Such a
 *  payload cannot come from a workspace (each lifts its own answers beside its flags), only from a
 *  submission made straight to the API, and showing the learner's own draft beats showing them a
 *  blank. */
function bestSubmission(history: SubmissionDetail[]): ActivityPayload | undefined {
  return history
    .filter((h) => hasAnswers(h.submission.payload))
    .reduce<SubmissionDetail | undefined>(
      (best, h) => (!best || (h.review?.overallScore ?? 0) > (best.review?.overallScore ?? 0) ? h : best),
      undefined,
    )?.submission.payload;
}

/**
 * How this screen gets its data, and what it is allowed to do with it.
 *
 * Defaults to the signed-in learner working their own step. A mentor reviewing it mounts the very
 * same screen against the mentee's data, read-only, with the decision in place of the submit bar —
 * because the learner's post-submission view already *is* a read-only rendering of this work, and
 * building a reviewer's paraphrase of it beside it would be a second description that drifts.
 */
export interface StepScreenSource {
  activity: () => Promise<ActivityDetail>;
  submissions: () => Promise<SubmissionDetail[]>;
}

export function StepScreen({ source }: { source?: StepScreenSource } = {}) {
  const { activityId } = useParams<{ activityId: string }>();
  const { learnings, refresh: refreshTree, scheduleByActivity } = useDeskLearnings();
  const base = useDeskBase();
  const due = scheduleByActivity.get(activityId);
  const [activity, setActivity] = useState<ActivityDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);

  const [values, setValues] = useState<Record<string, unknown>>({});
  // The judgment call lives OUTSIDE `values` on purpose. VerbWorkspace owns `values` through
  // useLift, which replaces the whole object on every keystroke — anything a sibling wrote into
  // it would be wiped on the next character typed. The two are merged only at payload time.
  const [decision, setDecision] = useState<DecisionAnswer>({ option: "", justification: "" });
  const [focusRefId, setFocusRefId] = useState<string | null>(null);
  // reference documents opened as draggable floating windows
  const fw = useFloatingDocs();
  const [busy, setBusy] = useState(false);
  const [savedAt, setSavedAt] = useState<string | null>(null);
  const [result, setResult] = useState<SubmitResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const [history, setHistory] = useState<SubmissionDetail[]>([]);
  const [briefOpen, setBriefOpen] = useState(false);
  const [feedbackOpen, setFeedbackOpen] = useState(false);
  const [briefShown, setBriefShown] = useState(true);
  // The criteria HUD stays closed until the user scrolls the deliverable into view (see observer below).
  const [criteriaHidden, setCriteriaHidden] = useState(false); // user dismissed it
  const [atDeliverable, setAtDeliverable] = useState(false);   // deliverable card is on screen
  // When a passed activity is reopened, lets the user choose to start the deliverable again.
  const [resubmit, setResubmit] = useState(false);
  // The read-back on screen is a draft, because the graded submission held no answers (see
  // bestSubmission). The banner must not then call it the work that was submitted.
  const [readbackIsDraft, setReadbackIsDraft] = useState(false);
  const [attemptKey, setAttemptKey] = useState(0); // bumped to remount the workspace blank
  const deliverableRef = useRef<HTMLDivElement>(null);
  // Watched by StepBar: while this heading is on screen the condensed title stays away.
  const headingRef = useRef<HTMLDivElement>(null);
  // Guided walkthrough: objective → what to do → checklist → deliverable. -1 = closed.
  const [tourStep, setTourStep] = useState(-1);
  // Checklist rows (1-based) whose part of the deliverable has focus — see the workspace fieldset.
  const [paired, setPaired] = useState<number[]>([]);
  const objectiveRef = useRef<HTMLDivElement>(null);
  const whatToDoRef = useRef<HTMLDivElement>(null);
  const referenceBtnRef = useRef<HTMLButtonElement>(null);
  const checklistHudRef = useRef<HTMLDivElement>(null);
  const checklistInlineRef = useRef<HTMLDivElement>(null);

  // `decision` is round-tripped inside the same fields blob, so lift it back out and keep it out
  // of `values` — leaving it there would render it as a stray deliverable field.
  const seed = (p?: ActivityPayload | null) => {
    const { decision: saved, ...rest } = (p?.fields ?? {}) as Record<string, unknown>;
    setValues(rest);
    setDecision(saved && typeof saved === "object" ? (saved as DecisionAnswer) : { option: "", justification: "" });
  };

  useEffect(() => {
    let cancelled = false;
    setTourStep(-1); // close the tour during navigation so it never shows a stale step
    setPaired([]);
    // A hover on the step's link in the tree may already have these in flight — see
    // `prefetchStep`. Learner's own desk only: a mentor's `source` reads a different learner.
    const warm = source ? null : takeWarmStep(activityId);
    Promise.all([
      warm?.activity ?? (source?.activity ?? (() => deskApi.activity(activityId)))(),
      // null = the fetch FAILED; [] = there genuinely are no submissions. Swallowing both as []
      // is how a transient network blip turned a finished step into a blank one: with no history
      // to read back, the seed below falls through to whatever draft is on file — for a gate,
      // usually the empty one autosaved on the way in — and the mentee is told nothing.
      warm?.submissions ?? (source?.submissions ?? (() => deskApi.submissions(activityId)))().catch(
        () => null,
      ),
    ])
      .then(([a, hist]) => {
        if (cancelled) return;
        const h = hist ?? [];
        setActivity(a);
        setHistory(h);
        setResubmit(false);
        if (!hist) setError("Couldn't load your previous submissions — reload the page to see the work you submitted.");
        // An unsubmitted draft refills the workspace to carry on with. Failing that, a step that
        // has been submitted reads its own work back — frozen once it passed, until Resubmit
        // blanks it for a fresh attempt.
        //
        // A passed step reads the SUBMISSION, never a draft. The draft is the current attempt, and
        // once a step is complete there is no current attempt — while a draft that is merely open
        // on the page autosaves, so an empty one could outrank the graded work and leave the
        // screen showing a blank deliverable under "This is the work you submitted — graded
        // 5.0 / 5". That is precisely what happened wherever a workspace failed to read its own
        // saved shape: it painted blank, autosaved the blank, and the blank then won every time.
        // Exactly the test the rest of the screen uses for `passed` — `status` alone is not it: a
        // step whose last review decided "pass" is finished even when the status has not caught up,
        // and reading the draft there is what showed a blank deliverable under "graded 5.0 / 5".
        const done = a.status === "complete" || a.latestReview?.decision === "pass";
        const submitted = bestSubmission(h);
        setReadbackIsDraft(done && !submitted && hasAnswers(a.draft));
        seed(done ? (submitted ?? a.draft) : (a.draft ?? submitted));
      })
      .catch((e) => !cancelled && setLoadError(e instanceof ApiError ? e.message : "Couldn't load this activity."))
      .finally(() => !cancelled && setLoading(false));
    return () => { cancelled = true; };
    // `source` is memoised by its caller, so this refetches when the mentor switches mentee even
    // if the step id happens to be identical. Leaving it out made the identity of the fetcher
    // invisible to the effect, which is how you serve one learner's work under another's name.
  }, [activityId, source]);

  // Nothing floats over the page until the deliverable scrolls into view — then the HUD opens
  // itself, once. A manual dismiss sticks for the rest of the activity: scrolling out and back used
  // to clear it, so the HUD kept reappearing over work the mentee had just pushed it off.
  // Re-attaches when the deliverable card mounts (after the activity loads).
  useEffect(() => {
    const el = deliverableRef.current;
    if (!el || typeof IntersectionObserver === "undefined") return;
    const io = new IntersectionObserver(
      ([entry]) => setAtDeliverable(entry.isIntersecting),
      // Thin band right under the header and the step bar (64 + 52): fires once the "Your deliverable"
      // heading scrolls up to the top of the screen, and stays open while the (tall)
      // card still overlaps the band — i.e. for the rest of the activity.
      { rootMargin: "-116px 0px -90% 0px" },
    );
    io.observe(el);
    return () => io.disconnect();
  }, [activity]);

  // Auto-run the guided walkthrough only on a new mentee's entry point — the first action of the
  // first task. Everywhere else it's on-demand via the Guide button (which blinks to hint it exists).
  useEffect(() => {
    if (!activity || !learnings) return;
    const firstStepId = learnings.orgs[0]?.projects[0]?.tasks[0]?.steps[0]?.id;
    if (activityId !== firstStepId) return;
    const id = setTimeout(() => setTourStep(0), 400); // let the brief animate in first
    return () => clearTimeout(id);
  }, [activity, learnings, activityId]);

  const closeTour = () => setTourStep(-1);

  // Curriculum content (brief + reference bodies) is fetched per-task from the gated endpoint,
  // not bundled — see task-bundle.ts.
  //
  // The task code used to come only from the loaded activity, which put the bundle behind
  // `GET /me/activities/{id}` in a two-hop chain on every step opened — and the brief is the first
  // thing on the page, so the whole step read as slow. The tree already says which task a step
  // belongs to and is fetched in parallel by the desk, so take it from there when it's known and
  // the two requests go out together. `activity` still wins once it lands: it is the authority on
  // its own task, and a mentor's desk is filtered to gates but carries the same codes.
  const treeTaskCode = learnings?.orgs
    .flatMap((o) => o.projects.flatMap((p) => p.tasks))
    .find((t) => t.steps.some((st) => st.id === activityId))?.code;
  const { bundle, loading: bundleLoading } = useTaskBundle(activity?.taskCode ?? treeTaskCode);

  const payload = (): ActivityPayload => ({
    fields: activity?.judgment ? { ...values, decision } : values,
    notes: "",
    attachments: [],
  });
  const openRef = (id?: string) => { setFocusRefId(id ?? null); setBriefOpen(true); };
  const hasContent = Object.entries(values).some(([k, v]) => !CONTROL_KEYS.has(k) && isFilled(v));
  // Workspaces that judge their own completion lift a flag: `objectiveMet` (answer-key validated,
  // e.g. the Request conversation) or `ready` (every required field filled). While either is
  // present and not yet true, submitting is blocked — otherwise a workspace that also lifts its
  // given/scripted data reads as "has content" and an untouched deliverable can be sent for grading.
  const workspaceBlocked = values.objectiveMet === false || values.ready === false;
  // Escape hatch. Every recovery path (gate_lifted's forced pass on the final attempt, the answer
  // key from _model_answer_if_stuck) triggers on attempts *spent* — so a workspace that never lets
  // Submit fire leaves a stuck mentee with no way out at all. After a while on an unmet objective
  // they may send it as it stands: honest Layer 1 miss, attempt burned, third one passes them on.
  // ponytail: a 10-minute timer, not a per-workspace "you got it wrong N times" signal — only
  // some workspaces count slips. Wire those in if the wait reads as arbitrary.
  const [override, setOverride] = useState(false);
  const [stuck, setStuck] = useState(false);
  useEffect(() => {
    setOverride(false); setStuck(false);
    const t = setTimeout(() => setStuck(true), 10 * 60_000);
    return () => clearTimeout(t);
  }, [activityId]);
  // A step carrying a judgment call cannot be submitted without one. The server has its own floor
  // (services/judgment.FLOOR) and would fail the step anyway — blocking here spends no attempt.
  // Not covered by `override`: the escape hatch exists for a workspace whose objective the mentee
  // cannot meet, and there is no way to be unable to state why you chose something.
  const judgmentBlocked = !decisionReady(activity?.judgment ?? null, decision);
  const objectiveBlocked = (workspaceBlocked && !override) || judgmentBlocked;
  const blockedHint = judgmentBlocked
    ? (decision.option
        ? "Say why you chose it — the judgment call is graded on the reasoning."
        : "Answer the judgment call below to submit.")
    : values.objectiveMet === false
    ? "Complete the guided steps successfully to submit."
    : "Complete every required field in the deliverable to submit.";

  // Autosave. An activity holds up to an hour of written work and the only other way to persist it
  // was a manual button click, so a closed tab, a crash or an expired session lost everything typed
  // since the last one. Fires 2s after typing stops; the Save draft button stays for reassurance.
  const savedSnapshot = useRef<string | null>(null);
  const saveChain = useRef<Promise<unknown>>(Promise.resolve());
  const touched = useRef(false); // set by the page's capture handlers on the first real interaction
  useEffect(() => { savedSnapshot.current = null; touched.current = false; }, [activityId]);
  useEffect(() => {
    if (!activity || activity.attemptsRemaining <= 0) return; // not loaded, or read-only
    if (activity.status === "complete" && !resubmit) return; // reading a passed step back, not editing it
    // The judgment call rides in the same draft blob as the deliverable, so an answer typed and
    // then abandoned survives a closed tab exactly as the rest of the work does.
    const fields = activity.judgment ? { ...values, decision } : values;
    const snapshot = JSON.stringify(fields);
    // First run after the activity loads is the seeded draft, not something the mentee typed.
    if (savedSnapshot.current === null) { savedSnapshot.current = snapshot; return; }
    if (!touched.current || snapshot === savedSnapshot.current) return;
    const id = setTimeout(() => {
      // Chained, so a slow save can never land after — and overwrite — a newer one.
      saveChain.current = saveChain.current
        .then(() => deskApi.saveDraft(activityId, { fields, notes: "", attachments: [] }))
        .then(() => { savedSnapshot.current = snapshot; setSavedAt(new Date().toLocaleTimeString()); })
        .catch(() => {}); // keep the stale snapshot so the next edit retries; the button still reports errors
    }, 2000);
    return () => clearTimeout(id);
  }, [values, decision, activity, activityId, resubmit]);

  const saveDraft = async () => {
    setBusy(true); setError(null);
    try {
      await deskApi.saveDraft(activityId, payload());
      savedSnapshot.current = JSON.stringify(payload().fields);
      setSavedAt(new Date().toLocaleTimeString());
    } catch (e) {
      setError(e instanceof Error ? e.message : "Couldn't save draft.");
    } finally { setBusy(false); }
  };

  // Resubmit is a fresh attempt, not an edit of the last one: clear the answers, drop the previous
  // grading, and remount the workspace so its internal state re-seeds from the blank value.
  const startResubmit = () => {
    setValues({});
    setDecision({ option: "", justification: "" });
    setResult(null);
    setError(null);
    setSavedAt(null);
    savedSnapshot.current = null; // don't autosave the blanking itself; the next edit saves
    setAttemptKey((k) => k + 1);
    setResubmit(true);
  };

  /**
   * Backing out of a resubmit puts the last submission back on screen.
   *
   * Re-seeding `values` is not enough on its own: a workspace holds its own state, seeded from
   * `value` when it mounts, and `startResubmit` bumps `attemptKey` precisely to remount it blank.
   * Cancel has to bump it too, or the workspace keeps the blank state it was given and the screen
   * stays empty — which is what "cancel" was doing: it undid the mode and not the blanking.
   */
  const cancelResubmit = () => {
    setResubmit(false);
    seed(bestSubmission(history));
    setAttemptKey((k) => k + 1);
  };

  const submit = async () => {
    if (objectiveBlocked) return; // guided objective not yet met
    setBusy(true); setError(null); setResult(null);
    try {
      const res = await deskApi.submit(activityId, payload());
      setResult(res);
      setFeedbackOpen(true); // surface the graded result immediately
      deskApi.submissions(activityId).then(setHistory).catch(() => {});
      setActivity((a) => (a ? { ...a, attemptsUsed: res.attemptsUsed, attemptsRemaining: res.attemptsRemaining, maxAttempts: res.maxAttempts, judgmentResult: res.judgmentResult ?? a.judgmentResult } : a));
      if (res.review) {
        setActivity((a) => (a ? { ...a, status: res.review!.decision === "pass" ? "complete" : "in-progress", latestReview: res.review } : a));
        if (res.review.decision === "pass") {
          setResubmit(false); // return to the completed view after a successful (re)submit
          await refreshTree(); // refresh tree so the next step unlocks in place
        }
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Submission failed.");
    } finally { setBusy(false); }
  };

  if (loading) {
    return (
      <div className="page-shell animate-pulse">
        {/* header */}
        <div className="mb-5">
          <div className="h-3 w-56 rounded bg-slate-200 mb-3" />
          <div className="flex items-center gap-3">
            <div className="w-12 h-7 rounded-md bg-slate-200" />
            <div className="h-5 w-72 max-w-[60%] rounded bg-slate-200" />
            <div className="h-5 w-20 rounded-full bg-slate-100" />
          </div>
        </div>
        {/* brief — two cards */}
        <div className="mb-5">
          <div className="h-3 w-48 rounded bg-slate-200 mb-2.5" />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {[0, 1].map((i) => (
              <div key={i} className="rounded-2xl ring-1 ring-slate-200 p-4 space-y-2.5">
                <div className="h-3 w-24 rounded bg-slate-200" />
                <div className="h-2.5 w-full rounded bg-slate-100" />
                <div className="h-2.5 w-[92%] rounded bg-slate-100" />
                <div className="h-2.5 w-3/4 rounded bg-slate-100" />
              </div>
            ))}
          </div>
        </div>
        {/* deliverable card */}
        <div className="rounded-2xl ring-1 ring-slate-200 p-5 space-y-4">
          <div className="h-4 w-40 rounded bg-slate-200" />
          <div className="h-3 w-64 max-w-full rounded bg-slate-100" />
          <div className="h-28 w-full rounded-xl bg-slate-100" />
          <div className="h-10 w-36 rounded-lg bg-slate-200" />
        </div>
      </div>
    );
  }
  if (loadError || !activity) {
    return (
      <div className="max-w-[680px] mx-auto px-6 py-10">
        <Card className="text-center py-12">
          <div className="w-11 h-11 mx-auto rounded-xl bg-rose-50 ring-1 ring-rose-100 flex items-center justify-center text-rose-500 mb-3"><Icon name="info" size={20} /></div>
          <div className="text-[13px] font-medium text-slate-700">{loadError ?? "Activity not found"}</div>
          <Link href="/app/learnings" className="inline-block mt-4 text-[12.5px] text-indigo-600 hover:text-indigo-700">← Back to My Learnings</Link>
        </Card>
      </div>
    );
  }

  // Typing a step URL ahead of yourself used to open the full workspace: brief, deliverable and a
  // Submit that 409s ("This step is locked") only once the work is done. The tree is authoritative
  // about what is open, so say so before any of that. Only when we positively know it is locked —
  // an unloaded tree must not flash the notice — and never on a mentor's desk, where the step
  // belongs to somebody else and read-only is the point.
  const treeStep = learnings?.orgs
    .flatMap((o) => o.projects)
    .flatMap((p) => p.tasks)
    .flatMap((t) => t.steps)
    .find((s) => s.id === activityId);
  if (!source && treeStep?.status === "locked") {
    return (
      <div className="max-w-[680px] mx-auto px-6 py-10">
        <LockedNotice what="step" />
      </div>
    );
  }

  const verb = VERBS[activity.verb.id] ?? GATE_VERBS[activity.verb.id];
  const content = bundle ? activityBrief(bundle, activity.code, activity.verb.id) : undefined;
  const layer1 = result?.layer1;
  const review = result?.review ?? activity.latestReview;
  // Same precedence as `review`: this submit's verdict if there was one, else the last stored one.
  const judgmentResult = result?.judgmentResult ?? activity.judgmentResult;
  const passed = review?.decision === "pass" || activity.status === "complete";
  const attemptsRemaining = result?.attemptsRemaining ?? activity.attemptsRemaining;
  const attemptsUsed = result?.attemptsUsed ?? activity.attemptsUsed;
  const maxAttempts = result?.maxAttempts ?? activity.maxAttempts;
  const noAttemptsLeft = attemptsRemaining <= 0;
  // Attempts exhausted → the workspace goes read-only. So does a passed step: it shows the work
  // that earned the pass, frozen, until Resubmit blanks it. The two task-boundary gates are
  // excluded — their tab rail is buttons, and a disabled fieldset would strand the mentee on
  // whichever tab loaded first with no way to read the rest of what they wrote.
  const readback = passed && !resubmit;
  // Whether the work on screen is the learner's own, reloaded into the workspace, or a payload the
  // workspace has no way to read (a demo/API row, or work submitted against an older workspace).
  const workspaceFits = fitsWorkspace(activity.verb.id, values);
  const locked = noAttemptsLeft || (readback && !isGateVerb(activity.verb.id));
  // The Guide walks the deliverable field by field, so it is withheld while the workspace is
  // frozen — there is nothing there to type into. Resubmit is the thing that un-freezes it, so
  // that is what the button says, and once the attempts are gone there is no way back and it
  // closes for good. Note this is the Guide only: the objective, the brief and the reference
  // material stay open on the page itself.
  const guideBlocked = locked;
  // Derived from the same two facts as the greying, and never empty while the button is grey — a
  // disabled control that cannot say why is the thing we were trying to avoid.
  const guideNote = noAttemptsLeft ? "Guide closed — no attempts left" : "Click Resubmit for the Guide";
  const hasFeedback = !!(layer1 || review || activity.mentorReview);
  const hasBrief = !!(content?.objective || (content?.whatToDo && content.whatToDo.length > 0));
  const hasChecklist = acceptanceTexts(activity.verb.id).length > 0;
  const checklist = checklistStates(activity.verb.id, values, layer1);
  // Documents with their own Open button (floating windows) leave the drawer: the Reference-material
  // panel keeps only the verb workspace's scripted artefacts (Scope Statement, Asset Register, …)
  // opened via the in-workspace "Open" buttons.
  const stripRefs = content?.references ?? [];
  const references = (WORKSPACE_REFS[activity.verb.id] ?? []).filter((r) => !stripRefs.some((x) => x.id === r.id));
  const taskRefs = references.filter((r) => r.group === "task");
  const docRefs = references.filter((r) => r.group !== "task");

  // Where "Next step" goes. Two rules, in order:
  //  1. the next step of THIS task that isn't locked — so paging forward through a task you have
  //     already finished walks 1.1 -> 1.2 rather than leaping to the next task;
  //  2. otherwise the first unlocked incomplete step anywhere ahead — the real "carry on here".
  // Previously this only ever took each task's FIRST current step and, if that was the step you
  // were standing on, fell through to the next task entirely.
  let nextStepId: string | null = null;
  let nextTaskCode: string | null = null;
  if (learnings) {
    const openTasks = learnings.orgs
      .filter((o) => o.status !== "locked")
      .flatMap((o) => o.projects.flatMap((p) => p.tasks));

    const here = openTasks.find((t) => t.steps.some((s) => s.id === activityId));
    if (here) {
      const i = here.steps.findIndex((s) => s.id === activityId);
      const within = here.steps.slice(i + 1).find((s) => s.status !== "locked");
      if (within) { nextStepId = within.id; nextTaskCode = here.code; }
    }
    if (!nextStepId) {
      for (const t of openTasks) {
        const s = t.steps.find((x) => x.status === "current" && x.id !== activityId);
        if (s) { nextStepId = s.id; nextTaskCode = t.code; break; }
      }
    }
  }

  // Guided walkthrough steps, in order, skipping any target this activity doesn't have.
  const tourSteps: TourStep[] = [];
  if (content?.objective) tourSteps.push({
    title: "Start with the objective",
    body: "This is the goal of the step — what a good deliverable must achieve. Read it first so everything else has context.",
    icon: "target",
    getEl: () => objectiveRef.current,
    onEnter: () => setBriefShown(true),
  });
  if (content?.whatToDo && content.whatToDo.length > 0) tourSteps.push({
    title: "Follow what to do",
    body: "These are the concrete actions to work through. Tackle them in order — each one feeds your deliverable.",
    icon: "list",
    getEl: () => whatToDoRef.current,
    onEnter: () => setBriefShown(true),
  });
  if (references.length > 0) tourSteps.push({
    title: "Open the reference material",
    body: `The facts, rules and artefacts you need to do this step correctly — ${references.length} document${references.length > 1 ? "s" : ""} here. Click it any time to read alongside your work.`,
    icon: "book",
    getEl: () => referenceBtnRef.current,
  });
  if (hasChecklist) tourSteps.push({
    title: "Watch the checklist",
    body: "Every acceptance criterion the mentor grades against. It ticks off live as you type — aim for all green before submitting.",
    icon: "checkSquare",
    getEl: () => (window.matchMedia("(min-width: 1280px)").matches ? checklistHudRef.current : checklistInlineRef.current),
    onEnter: () => { setAtDeliverable(true); setCriteriaHidden(false); }, // force it visible for the tour; the observer re-syncs on scroll
  });
  // A field walk needs a workspace the mentee can actually type into, and there are two ways this
  // is not one. The step may be read-only (`locked`: passed and frozen, or attempts spent — the
  // whole workspace sits in a disabled fieldset, so pointing at a field and saying "name the role
  // here" is worse than saying nothing). Or the field may not belong to the stage on screen —
  // Request's compose fields are gone the moment the request is sent, submitted or not.
  //
  // So the walk is withheld rather than offered and skipped. An `optional` step that finds no
  // target waits 600ms for it before moving on, which is right for a section that renders late and
  // wrong for one that will never exist: five in a row parked the Guide on a dimmed page for three
  // seconds and then closed it. The four steps that still apply on a finished step — objective,
  // what to do, reference material, checklist — are exactly what a mentee re-reads before a
  // revision, so the Guide itself stays available the whole way through.
  const fields = locked
    ? []
    : fieldGuide(activity.verb.id).filter((f) => typeof document !== "undefined" && !!document.querySelector(`[data-guide="${f.key}"]`));
  tourSteps.push({
    title: locked ? "The work you submitted" : "Fill in your deliverable",
    body: fields.length
      ? "This is where you do the work. The next few steps walk the fields one at a time — what each is for, and what makes a good one. You can type as you go: the field the Guide is pointing at stays live."
      : locked
      ? "This is the work you sent for review, held exactly as it was graded. Resubmit blanks it for a fresh attempt — if you have one left."
      : "Do your work here, then Submit for review. The AI mentor grades it and tells you what to improve. You can save a draft any time.",
    icon: "send",
    getEl: () => deliverableRef.current,
  });
  // …and then its fields, one at a time. A single "do your work here" is orientation for someone
  // who has been here before and no help at all to someone facing an empty workspace, so each verb
  // that has a walk authored (lib/guide-fields.ts) carries on into it. Optional throughout: a
  // workspace stage that isn't on screen — Request's compose fields, once the request has been
  // sent — drops out of the walk rather than parking the card on nothing.
  for (const f of fields) tourSteps.push({
    title: f.title,
    body: f.body,
    icon: f.icon,
    optional: true,
    getEl: () => document.querySelector<HTMLElement>(`[data-guide="${f.key}"]`),
  });

  return (
    <div
      className="page-shell"
      // Autosave only after the mentee actually touches the page — workspaces seed their scripted
      // defaults into `values` on mount, and that must not be mistaken for typed work.
      onPointerDownCapture={() => { touched.current = true; }}
      onKeyDownCapture={() => { touched.current = true; }}
    >
      {/* Held shut while the task bundle is in flight: `content` is what the objective and
          what-to-do steps are built from, so a tour opened before it lands is a 2-step tour on the
          checklist that renumbers itself under the mentee a second later. Guards both ways in —
          the auto-run on the first step and the Guide button. */}
      <StepBar
        code={activity.code}
        eyebrow={activity.taskTitle}
        title={activity.title}
        watch={headingRef}
        done={passed}
        score={review ? (passed ? `${review.overallScore.toFixed(1)}/5` : "revise") : undefined}
        onScore={hasFeedback ? () => setFeedbackOpen(true) : undefined}
      />
      <GuidedTour steps={tourSteps} step={bundleLoading ? -1 : tourStep} onStep={setTourStep} onClose={closeTour} />
      <FloatingDocs docs={fw.docs} onClose={fw.close} onFocus={fw.focus} />

      {/* header — description left, submission-feedback trigger on the right */}
      <div className="mb-5 flex items-start justify-between gap-4 flex-wrap">
        <div className="min-w-0">
          <Link
            href="/app/learnings"
            className="inline-flex items-center gap-1.5 text-[12px] text-slate-500 hover:text-slate-700 no-underline mb-2"
          >
            <Icon name="chevronLeft" size={14} /> {activity.taskTitle}
          </Link>
          <div ref={headingRef} className="flex items-start gap-3.5">
            <span className="grid place-items-center min-w-8 h-8 max-md:min-w-7 max-md:h-7 px-1 rounded-[9px] bg-[#191a2c] text-white text-[13px] font-mono font-semibold shrink-0 mt-[3px] max-md:mt-0">{activity.code}</span>
            <div className="min-w-0 flex-1">
              <h1 className="text-[24px] max-md:text-[20px] font-semibold tracking-[-0.012em] text-[#191a2c] leading-[1.25]" style={{ textWrap: "balance" }}>{activity.title}</h1>
              <div className="mt-2 flex items-center gap-2 flex-wrap">
                {/* One "Done", not two: the schedule chip says the same once its day is done, so
                    this pill covers that case and the chip is left to dates only. */}
                {(passed || due?.status === "done") && (
                  <span className="inline-flex items-center gap-1 h-6 px-2 rounded-[7px] border border-[#bfe9cf] bg-[#e8f8ee] text-[12px] font-semibold text-[#15a04a]">
                    <Icon name="check" size={11} strokeWidth={3} /> Done
                  </span>
                )}
                {verb && <DVerb verbId={verb.id} />}
                {due && due.status !== "done" && (() => { const c = dueChip(due); return (
                  <span className={`inline-flex items-center gap-1.5 h-6 px-2 rounded-md text-[11px] font-medium ring-1 ${c.cls}`} title={fmtDue(due.date)}>
                    <Icon name="calendar" size={12} /> {c.text}
                  </span>
                ); })()}
              </div>
            </div>
          </div>
        </div>

        <div className="shrink-0 flex items-center gap-2 flex-wrap justify-end">
          {/* Guide trigger — blinks thrice on open to hint the walkthrough exists.
              On a frozen step it is not a disabled button at all but a chip that states the fact,
              in the same slot and at the same height so the header does not shift. A greyed button
              only raises the question; there is nothing for a click to do, and the answer does not
              belong in a floating layer — a popover here has to out-rank the desk's own panels to
              be seen, and inline help stays inline (form language, law 5). */}
          {guideBlocked ? (
            <span className="inline-flex items-center gap-1.5 h-9 px-3 rounded-lg bg-slate-50 ring-1 ring-slate-200 text-slate-500 text-[12.5px] font-medium tracking-tight">
              <Icon name="lock" size={14} className="text-slate-400 shrink-0" /> {guideNote}
            </span>
          ) : (
            <button
              key={activityId}
              onClick={() => setTourStep(0)}
              className="guide-blink focus-ring inline-flex items-center gap-1.5 h-9 px-3 rounded-lg bg-indigo-50 ring-1 ring-indigo-200/70 text-indigo-700 hover:bg-indigo-100 text-[12.5px] font-medium tracking-tight transition-colors cursor-pointer"
            >
              <Icon name="help" size={14} /> Guide
            </button>
          )}

          {/* submission-feedback trigger — only after a graded submission */}
          {/* The learner's own grade and revision history. A reviewer is forming the decision that
              goes into that history, not reading it back — and the AI's score sitting at the top of
              the screen invites anchoring on it before they have read the work. */}
          {hasFeedback && (
            <button
              onClick={() => setFeedbackOpen(true)}
              className={`inline-flex items-center gap-2 h-9 px-3 rounded-lg ring-1 transition-colors ${passed ? "bg-emerald-50 ring-emerald-200/70 hover:bg-emerald-100/70 text-emerald-700" : "bg-amber-50 ring-amber-200/70 hover:bg-amber-100/70 text-amber-700"}`}
            >
              <Icon name={passed ? "check" : "chat"} size={14} strokeWidth={passed ? 3 : 2} />
              <span className="text-[12.5px] font-medium tracking-tight">
                {activity.mentorReview ? "Mentor feedback" : "Submission feedback"}
              </span>
              <span className="text-[11.5px] font-semibold tabular-nums">
                {review ? (passed ? `· ${review.overallScore.toFixed(1)}/5` : "· revise") : layer1 && !layer1.passed ? "· not met" : ""}
              </span>
              <Icon name="arrowRight" size={13} className="opacity-60" />
            </button>
          )}
        </div>
      </div>

      {/* Stuck with no way forward — the reference answer goes in the page body, not behind the
          feedback drawer. Someone who cannot submit needs to see why and what to do next without
          hunting for it. */}
      {activity.modelAnswer && (
        <div className="mb-5">
          <ModelAnswer
            answer={activity.modelAnswer}
            activityId={activityId}
            onReleased={() => {
              invalidateQuery("mentor-feedback");
              deskApi.activity(activityId).then(setActivity);
              void refreshTree();
            }}
          />
        </div>
      )}

      {hasBrief && (
        <StepBrief
          objective={content?.objective}
          whatToDo={content?.whatToDo}
          objectiveRef={objectiveRef}
          whatToDoRef={whatToDoRef}
          defaultOpen={briefShown}
        />
      )}

      {/* The working sheet (form 06). The folded corner is the most valuable cue in the form
          language: one glance answers "is this mine?". Nothing the mentee cannot edit may wear
          one — which is why this is written here on the deliverable rather than added to the
          shared <Card>, that being the wrapper for a dozen things they cannot touch.
          A clip-path plus drop-shadow rather than a ring, because a ring cannot be notched. */}
      <WorkingSheet
        sheetRef={deliverableRef}
        title="Your deliverable"
        subtitle={
          verb ? (
            <>
              <span className="font-medium">{verb.label}</span> —{" "}
              <Gloss>{verb.when}</Gloss>
            </>
          ) : (
            "Capture your work for this step."
          )
        }
        action={
          references.length > 0 ? (
            <button
              ref={referenceBtnRef}
              onClick={() => setBriefOpen(true)}
              className="shrink-0 inline-flex items-center gap-1.5 h-9 px-3 rounded-lg bg-slate-50 ring-1 ring-slate-200 text-slate-600 hover:bg-slate-100 text-[12px] font-medium tracking-tight transition-colors"
            >
              <Icon name="book" size={14} /> Reference material
              <span className="inline-flex items-center justify-center min-w-[16px] h-[16px] px-1 rounded-full bg-indigo-600 text-white text-[10px] font-semibold tabular-nums">{references.length}</span>
            </button>
          ) : null
        }
      >

        {/* This step's materials, each openable as its own draggable window (the RUA gate renders
            its own per-verb-step strips inside the workspace). Sticky, so the source document rides
            down with the mentee instead of scrolling away above a long table — the Card is the
            containing block, so it pins for exactly the length of the deliverable. It pins 60px
            down, clear of the 52px StepBar, which is always showing by the time it sticks. Width is capped
            on md+ to stay clear of the acceptance-checklist HUD pinned top-right; the shadow only
            appears once we're in the deliverable, so a pinned bar reads as deliberate. */}
        {!isGateVerb(activity.verb.id) && stripRefs.length > 0 && (
          <DocOpenStrip docs={stripRefs} onOpen={fw.open}
            className={`mb-5 sticky top-[60px] z-10 md:max-w-[520px] transition-shadow duration-200 motion-reduce:transition-none ${atDeliverable ? "shadow-[0_10px_30px_-12px_rgba(15,23,42,0.35)]" : ""}`} />
        )}

        {/* Work this workspace cannot read back is shown as a record instead of as an empty
            workspace under "this is the work you submitted" — see lib/workspace-readback.ts for
            the three ways a payload ends up unreadable. Resubmit leaves this branch, so a fresh
            attempt still gets the real workspace. */}
        {readback && !workspaceFits ? (
          <div className="rounded-2xl ring-1 ring-slate-200 bg-white p-4">
            <div className="flex items-start gap-2 mb-3 text-[12px] text-slate-600 tracking-tight">
              <Icon name="info" size={13} className="text-slate-400 shrink-0 mt-px" />
              <span style={{ textWrap: "pretty" }}>
                This submission can&apos;t be loaded back into the workspace — it was made before this
                step&apos;s workspace took its current form, or outside it. Here is what was submitted;
                Resubmit starts a fresh attempt in the workspace.
              </span>
            </div>
            <SubmittedFields payload={{ fields: values, notes: "", attachments: [] }} verbId={activity.verb.id} taskCode={activity.taskCode} rua={bundle?.rua} />
          </div>
        ) : (
          /* A native disabled fieldset switches off every control inside in one go.
             The workspace wears the checklist's R-marks (criterion-mark.tsx) from this provider,
             and whichever part has focus lights its row in the strip. Moving between two fields
             fires blur then focus, so the pair follows without a gap. `ws-rows` scopes the
             focused-row rule in globals.css to the workspace; the judgment call below sits
             outside it on purpose. */
          <CriterionProvider value={{ verbId: activity.verb.id, texts: checklist.criteria, states: checklist.states, graded: checklist.graded }}>
            <fieldset
              disabled={locked}
              className={`ws-rows min-w-0 border-0 p-0 m-0 ${locked ? "opacity-75" : ""}`}
              onFocusCapture={(e) => setPaired(criteriaAt(activity.verb.id, e.target as Element, e.currentTarget))}
              onBlurCapture={() => setPaired([])}
            >
              <VerbWorkspace key={attemptKey} verbId={activity.verb.id} taskCode={activity.taskCode} activityCode={activity.code} value={values} onChange={setValues} openRef={openRef} />
            </fieldset>
          </CriterionProvider>
        )}

        {/* The judgment call sits AFTER the deliverable, not before it: the dilemmas are written
            for someone who has already done the work ("you have drafted the test plan…"), and
            asking for the decision first would invite them to answer it in the abstract. */}
        {activity.judgment && (
          <JudgmentCall
            key={`${activity.judgment.slot}/${attemptKey}`}
            prompt={activity.judgment}
            value={decision}
            onChange={setDecision}
            // A resubmit blanks the answer, so the verdict for the answer they no longer have on
            // screen goes with it — same reason `startResubmit` drops the previous grading.
            result={resubmit && !result ? null : judgmentResult}
            locked={locked}
          />
        )}

        {readback && !noAttemptsLeft && (
          <div className="mt-4 flex items-start gap-2 rounded-lg bg-emerald-50/70 ring-1 ring-emerald-200/70 px-3 py-2 text-[12px] text-emerald-800 tracking-tight">
            <Icon name="check" size={13} strokeWidth={3} className="text-emerald-600 shrink-0 mt-px" />
            <span>
              {readbackIsDraft
                ? <>Your graded submission for this step holds no answers to show{review ? ` — it was still graded ${review.overallScore.toFixed(1)} / 5` : ""}. This is your last saved draft; Resubmit starts a fresh attempt from a blank deliverable.</>
                : <>This is the work you submitted{review ? ` — graded ${review.overallScore.toFixed(1)} / 5` : ""}. It&apos;s read-only; Resubmit starts a fresh attempt from a blank deliverable.</>}
            </span>
          </div>
        )}

        {noAttemptsLeft && (
          <div className="mt-4 flex items-start gap-2 rounded-lg bg-slate-50 ring-1 ring-slate-200 px-3 py-2 text-[12px] text-slate-600 tracking-tight">
            <Icon name="info" size={13} className="text-slate-400 shrink-0 mt-px" />
            <span>You&apos;ve used all {maxAttempts} attempts for this step — it&apos;s now read-only. Your submissions are in <button onClick={() => setFeedbackOpen(true)} className="underline underline-offset-2 hover:text-slate-900 cursor-pointer">Submission feedback</button>.</span>
          </div>
        )}

        {error &&<div className="mt-4 text-[12.5px] text-rose-700 bg-rose-50 ring-1 ring-rose-100 rounded-lg px-3 py-2">{error}</div>}

        <div className="mt-5">
          {passed && !busy && !resubmit ? (
            <div className="flex items-center gap-3 flex-wrap">
              <span className="inline-flex items-center gap-2 h-10 px-4 rounded-lg bg-emerald-50 ring-1 ring-emerald-200/70 text-emerald-700 text-[13px] font-medium tracking-tight">
                <Icon name="check" size={14} strokeWidth={3} /> Submitted — step complete{review ? ` · ${review.overallScore.toFixed(1)} / 5` : ""}
              </span>
              {nextStepId ? (
                <Link href={`${base}/${nextStepId}`} className="focus-ring inline-flex items-center gap-2 h-10 px-4 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white text-[13px] font-semibold tracking-tight no-underline shadow-[0_4px_14px_-4px_rgba(79,70,229,0.6)]">
                  {nextTaskCode && nextTaskCode !== activity.taskCode ? "Next task" : "Next step"} <Icon name="arrowRight" size={15} />
                </Link>
              ) : (
                <Link href={base} className="inline-flex items-center gap-2 h-10 px-4 rounded-lg bg-white ring-1 ring-slate-200 text-slate-700 text-[13px] font-semibold tracking-tight no-underline hover:bg-slate-50">
                  Back to Working Desk <Icon name="arrowRight" size={15} />
                </Link>
              )}
              {!noAttemptsLeft && (
                <button onClick={startResubmit} className="focus-ring inline-flex items-center gap-2 h-10 px-4 rounded-lg bg-white ring-1 ring-slate-200 text-slate-700 text-[13px] font-medium tracking-tight hover:bg-slate-50">
                  <Icon name="refresh" size={14} /> Resubmit
                </button>
              )}
              <AttemptsMeter used={attemptsUsed} max={maxAttempts} />
            </div>
          ) : (
            <div className="flex items-center gap-2 flex-wrap">
              <button onClick={submit} disabled={busy || !hasContent || objectiveBlocked || noAttemptsLeft} className="focus-ring h-10 px-4 rounded-lg bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 disabled:shadow-none text-white text-[13px] font-medium tracking-tight inline-flex items-center gap-2 shadow-[0_4px_14px_-4px_rgba(79,70,229,0.6)] transition-all">
                <Icon name="send" size={14} /> {busy ? "Grading…" : "Submit for review"}
              </button>
              <button onClick={saveDraft} disabled={busy || locked} className="focus-ring h-10 px-4 rounded-lg bg-white ring-1 ring-slate-200 hover:bg-slate-50 disabled:opacity-50 text-slate-700 text-[13px] font-medium tracking-tight">

                Save draft
              </button>
              <AttemptsMeter used={attemptsUsed} max={maxAttempts} />
              {passed && resubmit && (
                <button onClick={cancelResubmit} disabled={busy} className="focus-ring h-10 px-4 rounded-lg text-slate-500 text-[13px] font-medium tracking-tight hover:bg-slate-50 disabled:opacity-50">
                  Cancel
                </button>
              )}
              {savedAt && <span className="text-[11.5px] text-slate-400">Saved {savedAt}</span>}
              {objectiveBlocked && (
                <span className="text-[11.5px] text-amber-600">
                  {blockedHint}
                  {stuck && (
                    <button onClick={() => setOverride(true)} className="focus-ring ml-2 underline underline-offset-2 hover:text-amber-700">
                      Stuck? Submit as it stands — uses an attempt
                    </button>
                  )}
                </span>
              )}
              {override && workspaceBlocked && <span className="text-[11.5px] text-amber-600">Submitting incomplete work — this uses an attempt and is graded as it stands.</span>}
            </div>
          )}
        </div>
      </WorkingSheet>

      {/* Acceptance criteria. Small screens: inline card under the deliverable. A reviewer reads
          them in "What to check" above instead — on their screen these would be the same list a
          second and third time, one of them floating over the work. */}
      {hasChecklist && (
        <div ref={checklistInlineRef} className="md:hidden mt-5">
          <AcceptanceChecklist verbId={activity.verb.id} values={values} layer1={layer1} paired={paired} />
        </div>
      )}

      {/* md+: translucent glass HUD fixed to the top-right. Nothing floats until the deliverable
          scrolls into view — before that both the HUD and the chip are gone, so neither covers the
          brief. Inside the deliverable the HUD opens itself; dismissing it leaves the chip to
          bring it back. Both stay mounted so the swaps fade rather than pop. */}
      {hasChecklist && (
        <>
          <div ref={checklistHudRef} className={`hidden md:block fixed top-[calc(var(--hdr-h,64px)+64px)] right-4 z-20 w-[300px] max-h-[calc(100vh/var(--app-zoom)_-_var(--hdr-h,64px)_-_84px)] overflow-y-auto transition-all duration-200 ease-out motion-reduce:transition-none ${atDeliverable && !criteriaHidden ? "opacity-100 translate-y-0" : "opacity-0 -translate-y-1 pointer-events-none"}`}>
            <AcceptanceChecklist verbId={activity.verb.id} values={values} layer1={layer1} paired={paired} onClose={() => setCriteriaHidden(true)} />
          </div>
          <button
            onClick={() => setCriteriaHidden(false)}
            aria-hidden={!(atDeliverable && criteriaHidden)}
            // The handle that brings the strip back, in the strip's own language: square, steel,
            // mono. Not a rule strip itself — it carries no criteria — so it takes no double rule.
            className={`focus-ring hidden md:inline-flex fixed top-[calc(var(--hdr-h,64px)+64px)] right-4 z-20 items-center gap-1.5 h-9 pl-2.5 pr-3.5 bg-white/95 backdrop-blur-xl backdrop-saturate-150 ring-1 ring-slate-200 shadow-[0_12px_40px_-14px_rgba(15,23,42,0.3)] text-sky-800 hover:bg-white font-mono text-[10.5px] uppercase tracking-[0.09em] transition-all duration-200 ease-out motion-reduce:transition-none cursor-pointer ${atDeliverable && criteriaHidden ? "opacity-100 translate-y-0" : "opacity-0 -translate-y-1 pointer-events-none"}`}
          >
            <Icon name="checkSquare" size={14} className="text-sky-700" /> Criteria
          </button>
        </>
      )}

      {/* ===== Reference material — draggable, non-modal panel (context · documents) ===== */}
      {/* Opens on the left, over the tree: the work being written is on the right, and the tree is
          the one thing on screen you do not need while reading a source. */}
      <DraggablePanel open={briefOpen} onClose={() => setBriefOpen(false)} title="Reference material" eyebrow={verb?.label} side="left">
        <div className="space-y-6">
          {verb?.when && (
            <section>
              <h3 className="text-[11px] font-semibold tracking-[0.12em] uppercase text-slate-500 mb-1.5">When you use this</h3>
              <p className="text-[13px] text-slate-700 leading-relaxed tracking-tight" style={{ textWrap: "pretty" }}>{verb.when}</p>
            </section>
          )}

          {docRefs.length > 0 && (
            <section>
              <div className="flex items-center justify-between mb-1.5">
                <h3 className="text-[11px] font-semibold tracking-[0.12em] uppercase text-slate-500">Documentation</h3>
                <span className="inline-flex items-center gap-1 text-[10px] font-medium text-amber-700 bg-amber-50 ring-1 ring-amber-100 rounded-full px-2 h-5"><Icon name="info" size={10} /> Required</span>
              </div>
              <p className="text-[12px] text-slate-500 tracking-tight mb-2.5">The facts, rules and artefacts you need to complete this step correctly.</p>
              <RefAccordion key={`doc-${focusRefId ?? "default"}`} references={docRefs} focusId={focusRefId} />
            </section>
          )}

          {taskRefs.length > 0 && (
            <section>
              <h3 className="text-[11px] font-semibold tracking-[0.12em] uppercase text-slate-500 mb-1.5">Carried forward from prior steps</h3>
              <p className="text-[12px] text-slate-500 tracking-tight mb-2.5">Data you produced in earlier steps — requested, recorded, or signed off — now available here.</p>
              <RefAccordion key={`task-${focusRefId ?? "default"}`} references={taskRefs} focusId={focusRefId} />
            </section>
          )}
        </div>
      </DraggablePanel>

      {/* ===== Submission feedback drawer (results · revision history) ===== */}
      <Drawer
        open={feedbackOpen}
        onClose={() => setFeedbackOpen(false)}
        title="Submission feedback"
        eyebrow={review ? (passed ? "Passed" : "Needs revision") : "Result"}
      >
        <div className="space-y-6">
          {/* A human reviewer's decision leads — it is the part the learner can actually ask about. */}
          {activity.mentorReview && (
            <MentorDecision
              review={activity.mentorReview}
              onAcknowledged={() => {
                // Acknowledging completes the step and unlocks the next one, so the tree and the
                // activity both have to be re-read — not just this panel.
                invalidateQuery("mentor-feedback");
                deskApi.activity(activityId).then(setActivity);
                void refreshTree();
              }}
            />
          )}

          {layer1 && (
            <section>
              <h3 className="text-[13px] font-semibold tracking-tight text-slate-900 mb-2.5">
                Layer 1 — Acceptance {layer1.passed ? <span className="text-emerald-600">· passed</span> : <span className="text-rose-600">· not met</span>}
              </h3>
              <div className="space-y-2">
                {layer1.checks.map((c, i) => (
                  <div key={i} className="flex items-start gap-2.5">
                    <span className={`mt-0.5 w-4 h-4 rounded-full flex items-center justify-center shrink-0 ${c.passed ? "bg-emerald-100 text-emerald-600" : "bg-rose-100 text-rose-600"}`}>
                      <Icon name={c.passed ? "check" : "x"} size={10} strokeWidth={3} />
                    </span>
                    <div className="min-w-0">
                      <div className="text-[12.5px] text-slate-700 tracking-tight">{c.label}</div>
                      {c.detail && c.detail !== "Passed." && <div className="text-[11.5px] text-slate-400">{c.detail}</div>}
                    </div>
                  </div>
                ))}
              </div>
              {!layer1.passed && <p className="mt-3 text-[12px] text-slate-500">Address the unmet checks above, then submit again.</p>}
            </section>
          )}

          {review ? (
            <section>
              {layer1 && <h3 className="text-[13px] font-semibold tracking-tight text-slate-900 mb-2.5">Layer 2 — Quality</h3>}
              <ReviewPanel review={review} />
            </section>
          ) : (
            !layer1 && <p className="text-[12.5px] text-slate-500">No feedback yet — submit your deliverable to get graded.</p>
          )}

          {/* The judgment call is graded on its own scale by its own prompt, so it gets its own
              section rather than being folded into the Layer 2 rubric it has nothing to do with. */}
          {activity.judgment && judgmentResult && (
            <section>
              <h3 className="text-[13px] font-semibold tracking-tight text-slate-900 mb-1">Judgment call</h3>
              <p className="text-[11.5px] text-slate-500 tracking-tight mb-2.5">
                {activity.judgment.name} · {activity.judgment.competenceLabel}
              </p>
              <JudgmentAnswer
                decision={{ option: judgmentResult.option, justification: judgmentResult.justification }}
                prompt={activity.judgment}
              />
              <JudgmentVerdict result={judgmentResult} />
            </section>
          )}

          {history.length > 0 && (
            <section>
              <h3 className="text-[13px] font-semibold tracking-tight text-slate-900 mb-3">Revision history</h3>
              <div className="space-y-3">
                {history.map((h, hi) => {
                  const r = h.review;
                  const pass = r?.decision === "pass";
                  return (
                    <div key={h.submission.id} className="flex gap-3">
                      <div className="flex flex-col items-center shrink-0">
                        <span className={`w-7 h-7 rounded-full flex items-center justify-center text-[11px] font-semibold ring-1 ${r ? (pass ? "bg-emerald-50 text-emerald-700 ring-emerald-100" : "bg-amber-50 text-amber-700 ring-amber-100") : "bg-slate-50 text-slate-500 ring-slate-200"}`}>
                          v{h.submission.revisionNo}
                        </span>
                      </div>
                      <div className="min-w-0 flex-1 pb-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          {r ? (
                            <>
                              <span className={`inline-flex items-center gap-1 px-2 h-5 rounded-full text-[10.5px] font-medium ring-1 ${pass ? "bg-emerald-50 text-emerald-700 ring-emerald-100" : "bg-amber-50 text-amber-700 ring-amber-100"}`}>
                                {pass ? "Passed" : "Needs revision"}
                              </span>
                              <span className="text-[11px] font-semibold text-slate-700 tabular-nums">{r.overallScore.toFixed(1)} / 5</span>
                            </>
                          ) : (
                            <span className="inline-flex items-center px-2 h-5 rounded-full text-[10.5px] font-medium ring-1 bg-slate-50 text-slate-500 ring-slate-200">{h.submission.layer1 && !h.submission.layer1.passed ? "Layer 1 not met" : "Submitted"}</span>
                          )}
                          <span className="text-[10.5px] text-slate-400 ml-auto">{new Date(h.submission.createdAt).toLocaleString(undefined, { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}</span>
                        </div>
                        {r?.feedback && (
                          <>
                            {/* Same provenance as the full rubric, without the box — a history row
                                is too small to carry a note, but the attribution still has to be here. */}
                            <MachineTag className="mt-1.5" label="Generated" />
                            <p className="text-[11.5px] text-slate-500 mt-1 leading-relaxed tracking-tight" style={{ textWrap: "pretty" }}>{r.feedback}</p>
                          </>
                        )}
                        {/* what was actually sent — newest attempt expanded, older ones collapsed */}
                        {Object.keys(h.submission.payload?.fields ?? {}).length > 0 && (
                        <details open={hi === 0} className="mt-2 rounded-lg bg-slate-50/70 ring-1 ring-slate-200 group">
                          <summary className="cursor-pointer list-none select-none px-3 py-1.5 flex items-center gap-1.5 text-[11.5px] font-medium text-slate-600 hover:text-slate-900">
                            <Icon name="chevronDown" size={12} className="transition-transform group-open:rotate-0 -rotate-90" />
                            What you submitted
                          </summary>
                          <div className="px-3 pb-3 pt-2 border-t border-slate-200 space-y-3">
                            {/* `decision` is a CONTROL_KEY, so SubmittedFields skips it — render
                                the attempt's own answer here instead of losing it. */}
                            <JudgmentAnswer
                              decision={(h.submission.payload?.fields?.decision ?? {}) as DecisionAnswer}
                              prompt={activity.judgment}
                            />
                            <SubmittedFields payload={h.submission.payload} verbId={activity.verb.id} taskCode={activity.taskCode} rua={bundle?.rua} />
                          </div>
                        </details>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </section>
          )}

          {passed && !busy && (
            <section className="rounded-xl bg-emerald-50/70 ring-1 ring-emerald-200/70 p-3.5">
              <div className="flex items-center gap-2 mb-2.5">
                <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center shrink-0">
                  <Icon name="check" size={11} strokeWidth={3} />
                </span>
                <span className="text-[12.5px] font-semibold text-emerald-800 tracking-tight">Step complete{review ? ` · ${review.overallScore.toFixed(1)} / 5` : ""}</span>
              </div>
              {nextStepId ? (
                <Link href={`${base}/${nextStepId}`} onClick={() => setFeedbackOpen(false)} className="focus-ring inline-flex items-center gap-2 h-10 px-4 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white text-[13px] font-semibold tracking-tight no-underline shadow-[0_4px_14px_-4px_rgba(79,70,229,0.6)]">
                  {nextTaskCode && nextTaskCode !== activity.taskCode ? "Next task" : "Next step"} <Icon name="arrowRight" size={15} />
                </Link>
              ) : (
                <Link href="/app/desk" onClick={() => setFeedbackOpen(false)} className="inline-flex items-center gap-2 h-10 px-4 rounded-lg bg-white ring-1 ring-slate-200 text-slate-700 text-[13px] font-semibold tracking-tight no-underline hover:bg-slate-50">
                  Back to Working Desk <Icon name="arrowRight" size={15} />
                </Link>
              )}
            </section>
          )}
        </div>
      </Drawer>
    </div>
  );
}
